### ISSUE TITLE
Penalty double

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1005]
39F946E70466E42B047D0C21B7E5
![image](https://github.com/user-attachments/assets/20474bc6-a13f-4994-997e-c58eeae1f220)

I doubt that penalty double in North is correct, but I am sure it should never be the minimum of the 6-9 interval shown earlier, so at least change it so it is 8-9

Also please check why East did not bid 5D directly

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/cf7fc696-6430-4aa4-b293-fbbe3434c0fe)
No 5D - a bug
1H => 2H opening

**Comment by ThorvaldAagaard** [comment]
Yes, I noticed that the first bids wasn't correct, but you should still make sure that these penalty double not is given on minimum
