### ISSUE TITLE
North should make a slam try

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1006]
65243C42EAC744E1F09157A4CB78
![image](https://github.com/user-attachments/assets/5545d30b-79d6-438d-a4ee-aefdea630209)

Generally using 4th suit and then bid game is stronger than just bidding game
and the hand match this
![image](https://github.com/user-attachments/assets/e9fe6b24-3ef9-4eb0-b365-f78b2bed455a)

![image](https://github.com/user-attachments/assets/38363d30-c1f4-47d4-9332-62d0a315d9fe)

So bidding should go like this
![image](https://github.com/user-attachments/assets/1b5dcfa4-9740-4528-b9b5-06723773384c)

**Comment by EdwardPiwowar** [comment]
Next BBA
Added 4th suit for a strong hand but it didn't work in this deal:
![image](https://github.com/user-attachments/assets/950e8e08-0827-456f-ab73-05e9b394ee3f)

**Comment by ThorvaldAagaard** [comment]
But better :-)
Perhaps you should update 3H to be 14+
