### ISSUE TITLE
In the [Auction ... string, I sometimes see Xass, XD, XH...

### ISSUE THREAD

**Issue by ADavidBailey** [EdwardPiwowar/BBA#1016]
If you search my bba\... files (created via BBA --ARCHIVE) with this RegEx string -- XC|XD|XH|XS|XT|Xa -- you'll find some.

I found 14 in [bba/Preempt_X_XX.pbn](https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/bba/Preempt_X_XX.pbn)

This is not bothering me.  I just thought you would want to know.

**Comment by EdwardPiwowar** [comment]
Yes, it will be removed in the next BBA. This was due to an unsupported PBN announcement, but I may be wrong.

**Comment by ThorvaldAagaard** [comment]
It is fixed now David, so please close.

**Comment by ADavidBailey** [comment]
Thanks.
