### ISSUE TITLE
Calculations gone wrong here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1021]
000B06A09ED6BC958C02AA4640BA
I moved SK to this
000B42A09ED6BC958C02AA4640BA
![image](https://github.com/user-attachments/assets/dcc8da3d-f8d6-478c-96c9-60478a827a1f)

Single dummy get to 13 tricks but I see only 12

Both doubles from West are wrong 

Please also note the range for Souths 4N, that is defined as 11-11 HCP
and Wests penalty double is defined as 3-3 HCP
4C should not show 12-14 but primarily 4 clubs and 5-10 - here 5 Clubs seems defined OK, but 6 and 7 Clubs are alsoi wrong

**Comment by EdwardPiwowar** [comment]
SD is quite difficult for very unbalanced hands but here I could improve a bit.
If any bid (here 4C) deviates from the implemented meaning then all subsequent bids may be incorrect (here 40 HCP exceeded).
I lowered the HCP for 4C. 6C/7C show the maximum HCP that E can have but that does not mean that E will bid 6C/7C with 14 HCP.
Next BBA
![image](https://github.com/user-attachments/assets/3d4d0776-bc27-4a77-8bf1-65f8165093eb)
