### ISSUE TITLE
Overcalling 2C

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1024]
It seems an opening hand is needed to make an overcall after they open 2C

GIB has these definition
![image](https://github.com/user-attachments/assets/f7670ef9-fa4c-4615-bf20-ae47fba6a56b)

26889AD0F7427A6CDAF17704F4C0
![image](https://github.com/user-attachments/assets/8ebe28d7-17b0-4e45-8664-04733b2e438f)

Perhaps a bit optimistic, but any hand that would consider a weak two bid should bid over 2C

**Comment by EdwardPiwowar** [comment]
I added weak 2X and 3C.
