### ISSUE TITLE
Using CLI

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1026]
Only two dots in front of the file
![image](https://github.com/user-attachments/assets/cb15e962-23ea-4c79-afcb-70b583ddc868)

To get it to use 
![image](https://github.com/user-attachments/assets/84fc6780-0511-416c-9e2c-be59f30dbe5c)

I had to append "\\" to the directory
```
 --BBSA_FOLDER "D:\GitHub\ben\UCBC 2024\BBA convention cards\"
```
This seems not to use CURRENT_ARCHIVE 
```
BBA.exe --CURRENT_ARCHIVE "D:\GitHub\ben\" --ARCHIVE_FILE output_6 --AUTOBID --HAND .\input_6.bba --BBSA_FOLDER "D:\GitHub\ben\UCBC 2024\BBA convention cards\" --CC1 RoboSayc.bbsa --CC2 RoboSayc.bbsa --DD 0 --SD 1
```

as output files are written to the BBA-directory

I tried with "\\" and without

**Comment by ThorvaldAagaard** [comment]
No I was wrong BBSA_FOLDER  did not work and I copied the .bbsa to the BBA-directory

Would be nice if I could see where it is loaded from.

**Comment by EdwardPiwowar** [comment]
A bit confusing. *.bbsa files are CCs. Don't use --CURRENT_ARCHIVE. Use the full path --ARCHIVE_FILE file_name.

**Comment by ThorvaldAagaard** [comment]
I want BBA to read the BBSA from one folder an store the output in another

I used
```
--BBSA_FOLDER "D:\GitHub\ben\UCBC 2024\BBA convention cards\"
```
for the cc
and 
```
--CURRENT_ARCHIVE "D:\GitHub\ben\"
```
for the output

I will remove BBSA and use full path, but what about output?

neither seemed to work

**Comment by EdwardPiwowar** [comment]
BBA don't read '--HAND .\input_6.bba', use 'input_6.bba' (or full path).

**Comment by ThorvaldAagaard** [comment]
That is the same, and it is reading ther file fine, and also storing the output, but in the BBA-folder and not in CURRENT_ARCHIVE

**Comment by EdwardPiwowar** [comment]
The new BBA will create subfolders.
https://github.com/EdwardPiwowar/BBA/issues/137#issuecomment-2495513618

**Comment by EdwardPiwowar** [comment]
try --ARCHIVE_FILE "D:\GitHub\ben\BBA\output_6"   (without --CURRENT_ARCHIVE)
or 
manually create D:\GitHub\ben\BBA
or
I don't know

**Comment by ThorvaldAagaard** [comment]
Ok, will use full path on next execution

**Comment by EdwardPiwowar** [comment]
Current exe 8712

**Comment by ThorvaldAagaard** [comment]
Using full path got the files in the right place
