### ISSUE TITLE
Error files created by BBA

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1027]
During bidding of a large set BBA sometime create files like this

![image](https://github.com/user-attachments/assets/73bb5835-c871-4fb1-b078-53a505f291d3)

Should they be reported to you?

The content for those three are:
74203630B7730A4758C01EB8BAF7
02A7A2860198A1FADBC8B025B451
08D55D72C345A18F6CD80317C410

Using the RoboSayc.bbsa convention card

**Comment by EdwardPiwowar** [comment]
These files are saved if the bid exceeds 30 bids. They are not required to be reported, but sometimes indicate an error in bidding (overbidding).

**Comment by ThorvaldAagaard** [comment]
This was a funny board
02A7A2860198A1FADBC8B025B451
![image](https://github.com/user-attachments/assets/72d79d8f-33af-4dc0-adc6-0064f81f7edf)

Runnning from 6NX to 7NX making

And here it is almost impossible to see the entire bidding (and optiomistic bidding)
08D55D72C345A18F6CD80317C410
![image](https://github.com/user-attachments/assets/dc593b9c-5497-459d-8a7d-5a9aed5de0c2)

**Comment by EdwardPiwowar** [comment]
You can use the scroll bar (between rooms) or the maximize button.
![image](https://github.com/user-attachments/assets/fdfbc38d-d88f-41cd-9fa0-56f75594a5d3)

**Comment by ThorvaldAagaard** [comment]
I assume you will not fix the boards, so I close this, and reports the boards individually if needed

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/5d5bdbb7-e200-4d0e-9db8-b069a5382136)
