### ISSUE TITLE
Natural in competition, splinter undisturbed

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1032]
![image](https://github.com/user-attachments/assets/2e788cbd-25d6-4846-8229-b5182c9702a3)

GIB think it is natural
![image](https://github.com/user-attachments/assets/82125757-a97a-416c-afc0-8c42fc7e996e)

I would like to be able to configure it.

My common rule is

In undisturbed bidding an unnatural jump is splinter, but in disturbed bidding we bid natural, as that is more common and better

![image](https://github.com/user-attachments/assets/23348c8d-b31a-4de0-80fb-0ced3c6be330)

And it seems here GIB agree.

**Comment by EdwardPiwowar** [comment]
This combination seems extremely rare, no point in adding an option. 4m will be natural although I think it should be a cue bid.
![image](https://github.com/user-attachments/assets/2488a13a-f244-49b4-a5c1-a4f9faf5ad99)
