### ISSUE TITLE
Why not 2H in West?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#104]
0F7925A5F20E5F344F35E856BA5F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/98d6a30d-e2d7-4b1e-88f8-6f78b7c40176)
I think 2H is SAYC-standard

**Comment by EdwardPiwowar** [comment]
2H means 11+HCP but I will add a -1 HCP correction after pass with 25xx.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3c9f5d41-05f6-4844-ad0f-a83b8ec3fd46)

**Comment by ThorvaldAagaard** [comment]
In SAYC 1N is normally 6-9, so only bad 10 should bid 1N

**Comment by ThePokerDude** [comment]
Fixed in 8137 - 2h is bid instead of 1nt.
I think 4d is wrong (too weak with three card support when partner has a passed hand)
but that's a different issue
![image](https://github.com/user-attachments/assets/68b9d908-e9e1-42dd-b5e2-1fd5cd948587)
