### ISSUE TITLE
Wrong priority?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1040]
0DB3A2E20CAC43547F0E35C94A22
![image](https://github.com/user-attachments/assets/f551f924-8d20-44a9-a4d9-138ddac27311)

Souths hand match a reopening double, but it prefer 2C. Can you describe how it is decided that 2C is more correct than X?

**Comment by EdwardPiwowar** [comment]
Balancing Bids needs to be rebuilt. Do you have a source for this?

**Comment by ThorvaldAagaard** [comment]
I think I have read a book by Mike Lawrence many years ago, but here the problem, probably is that the hand should double even if East opened 1D, but also bids 2C here

With 3-2 in the majors i agree, but with 3-3, I think double is best.

Pavlicek has this page: http://www.rpbridge.net/5e00.htm

Karen Walker: https://kwbridge.com/bal1.htm

and this is also fine: https://www.bridgewebs.com/nwt/Bob%20Hertzog%20-%20Sept%204%20-%20Common%20Sense%20Bidding%20-%20Balancing.pdf
