### ISSUE TITLE
How is openers reverse implemented?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1044]
I think opener way to often pass a forcing bid
00CB13A8DF87FD52761C0B005BF2
Here BBA fails both for 21GF and SAYC

![image](https://github.com/user-attachments/assets/45fd69cf-1d5e-41a8-b9c5-5e6923d9b4f1)

Playing with GIB BBA fails jumping to 2N on a hand that has a natural reverse in 2D
![image](https://github.com/user-attachments/assets/d16a11ec-3601-41e8-ab91-51400f9dd7ab)

Playing on BBO 
![image](https://github.com/user-attachments/assets/fdc46459-c6b8-437d-85eb-b714ce4520e3)

So here BEN corrects openers rebid to 2D, but after the forcing 3D, BEN has learned from BBA that it can pass.

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/70d8c53d-a7f3-4639-bed4-6c4c24c2309e)
