### ISSUE TITLE
I am not sure, what 3C is defined as

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1049]
112E52EF3B4ADF6A102A6FC23E8A
![image](https://github.com/user-attachments/assets/cd540a06-d43b-4a54-ae90-669e24949a34)

Seems to be defined as preemptive, but that hand is not a preemptivce hand

**Comment by EdwardPiwowar** [comment]
In the next BBA it will be as described 6-8HCP and 7+ cards.

**Comment by ThorvaldAagaard** [comment]
OK, so on the actual hand BBA will bid 2C
