### ISSUE TITLE
Urgent. Is there an error in the EPBot86.dll?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#1054]
![image](https://github.com/user-attachments/assets/db28e5db-a45c-4ca2-a0f1-98bf007d45bc)

This was the entire bidding.
Room two is from an actual match, where EPBot86.dll returned 5C in response to 4N

![image](https://github.com/user-attachments/assets/a109fb83-4bb6-4a40-9af3-0efa9b7f7332)

This is what is set as bidding
new_hand position=1 ['Q4', 'AJ95', 'K5', 'KJT73'] dealer=0 vuln=0                                                                                             
set_bid (0, 0)                                                                                                                           
set_bid (1, 8)                                                                                                                           
set_bid (2, 0)                                                                                                                           
set_bid (3, 10)                                                                                                                          
set_bid (0, 0)                                                                                                                           
set_bid (1, 16)                                                                                                                          
set_bid (2, 0)                                                                                                                           
set_bid (3, 18)                                                                                                                          
set_bid (0, 0)                                                                                                                           
set_bid (1, 19)                                                                                                                          
set_bid (2, 0)                                                                                                                           
set_bid (3, 20)                                                                                                                          
set_bid (0, 0)                                                                                                                           
set_bid (1, 21)                                                                                                                          
set_bid (2, 0)                                                                                                                           
set_bid (3, 24)                                                                                                                          
set_bid (0, 0)

**Comment by EdwardPiwowar** [comment]
The bid displayed is interpreted by the BBA, which assumes that the bidder interprets the bid the same way. I think this is Ben's bid, not EPBot's. Am I wrong?

**Comment by ThorvaldAagaard** [comment]
Yes. It is BENs bid, but BEN did use the EPBot86.dll, that gave the wrong answer.

So the error is in the Dll not in the gui version.

**Comment by EdwardPiwowar** [comment]
Bidding from DLL v. 22 (Old22). I think Ben ignored 5H (and also the earlier 4N bid).
![image](https://github.com/user-attachments/assets/5a8b8fc8-69b2-464d-bd22-f2d07c32ecfa)

![image](https://github.com/user-attachments/assets/4f6a8335-9b55-4ca5-b02f-6974b7cda7a0)

**Comment by EdwardPiwowar** [comment]
Maybe N doubled?
![image](https://github.com/user-attachments/assets/7ed460dc-21b0-4c8b-976f-b42d6e5e8541)

**Comment by ThorvaldAagaard** [comment]
No, looking at the input there is no double.

But I call EPBot86 first to get an explanation of 4N, then I call it again to get the answer if it is RKC, could it be some mixup?

Is there a way to rest the bidding and hands without having to reload CC?

**Comment by EdwardPiwowar** [comment]
Ok?
![image](https://github.com/user-attachments/assets/075af40e-b5d6-4751-a72f-08fcc8e227ad)

**Comment by ThorvaldAagaard** [comment]
The problem is that I assumed **Blackwood without K and Q** means, that in certain situations 4N is for aces even though we don't have a trump.

The description is missing, and if it can overrule Blackwood-1430 it should not be possible to select both, at least not without a warning.

I have deselected it for now

**Comment by EdwardPiwowar** [comment]
"Blackwood without K and Q" is just an additional option for Ben. The Blackwood type is always a choice.

**Comment by ThorvaldAagaard** [comment]
How does it work? And when should it be selected?

**Comment by EdwardPiwowar** [comment]
You wanted me to add this option because Ben can't count king trumps.

**Comment by ThorvaldAagaard** [comment]
Sounds more like a misunderstanding, BEN never count anything :-)

I will leave it unchecled for now
