### ISSUE TITLE
Non-leaping Michael

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#108]
01CEEEDB6F2A78DAA0EA1B448A80
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/184ebb8b-f251-45b9-8d65-072d39465493)

It looks like WBridge5 is playing non-leaping Michaels. Will you add that convention?

**Comment by EdwardPiwowar** [comment]
I can add it if you give me a description of the correct version. But this year I probably won't make it, because I still have a lot to do.

**Comment by ThorvaldAagaard** [comment]
https://www.bridgewebs.com/alton/EBU%20-%20Stage%202%20Conventions%20-%20Leaping%20and%20Non-Leaping%20Michaels.pdf

**Comment by EdwardPiwowar** [comment]
I saw it, but I don't know if it's enough.

**Comment by ThePokerDude** [comment]
Fixed in 8137 but description is wrong (it's non-leaping michaels)
![image](https://github.com/user-attachments/assets/f41acd3b-e573-497f-9d7f-da6ccdd058a7)
