### ISSUE TITLE
We do not play high-low doubles, so 2C is forcing 

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#114]
2C01FFF91D4722FCA87E2619AAE5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/85ead9b2-b87a-4287-9e2a-8cfb2d29e4f9)

**Comment by EdwardPiwowar** [comment]
Yas, I plan to add this option.

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/c01e6c38-8bc6-4db5-a4a4-65a4b1e72379)
