### ISSUE TITLE
This is not SAYC-standard

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#115]
2621BC3F900EE2E4357B78964476
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8c56d9d5-a599-47d1-b86d-31099f11c130)

**Comment by ThorvaldAagaard** [comment]
Bidding 1S on 3 card instead of bidding 1N with a stopper in heart is wrong

**Comment by ThePokerDude** [comment]
looks ok to me now
![image](https://github.com/user-attachments/assets/5d2c8912-9d58-4ed5-bc1e-fc60723ea0e1)
