### ISSUE TITLE
Pass to a negative double (#25)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#116]
11B07F0E37964BF58FED9411C82F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/aecb0eb0-91f8-493c-87f4-2048f58aaeda)
Is this as intended?

**Comment by EdwardPiwowar** [comment]
Yes, Bot assumes 2Cx-1.

**Comment by ThorvaldAagaard** [comment]
As a negative double is unlimited and can be made on 5-5 in the majors or better, for me it requires 2 (or preferable 3) down when passed out. So you pass when you have trumps and tricks, and bid if not

**Comment by EdwardPiwowar** [comment]
After removing one of the restrictions
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2c7a2c7d-3b17-43c7-862f-e313de3c9584)

**Comment by ThorvaldAagaard** [comment]
Thx
