### ISSUE TITLE
Multi-landy in balancing situation from a passed hand

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#118]
015AAC8B70F00044F60BEFC7996A
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/56e2b3f0-2f9b-41ac-98b4-38ceb5ee0362)

The requirement of 11 HCP is wrong here especially when opening with 11 and a 5-card major-

I think it should be 10-11 if 5-4 but 8-11 with 5-5 - to Double it is OK with 10-11 if 4-5, but 8-11 if 4-6

**Comment by EdwardPiwowar** [comment]
I think after pass always at least 55
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/7e347334-dc11-4663-9285-36ff501e502c)

**Comment by ThorvaldAagaard** [comment]
OK. Could be interesting with a simulation

**Comment by EdwardPiwowar** [comment]
[compilation 7551](https://drive.google.com/file/d/1pVJZMN4sFMRzI-rTaKV0otcvbt35jluh/view?usp=sharing)
