### ISSUE TITLE
To passive

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#119]
175E82BA47A5E4AFD1048D1D59EA
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1c4d13b1-16f2-4274-a1ca-cbd3a06930f1)
With 2 controls a good suit and 2 of 3 honors overcalling 1S seems pretty normal

Pass in North seems to be an error as 1N is 12-15

**Comment by EdwardPiwowar** [comment]
If S bids pass
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/8004cb61-2fbd-4ebb-a808-682973167f4b)
after corrected 9=>8 HCP for any vulnerability 
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/7cdc4245-2ed0-41b0-9971-cdf264113c4c)

**Comment by ThorvaldAagaard** [comment]
A 15-17 NT should normally bid game after partners overcall, downgrade with shortage in overcallers suit.
This rule can also be used after partners preempt as opening bid.
So 2N is 13-14 hcp, but it is a bad game, so fine to get in the bidding, so I close this.
