### ISSUE TITLE
When closing BBA it kills all instances of WBridge5

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#12]
You should check that only process started by BBA is killed

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3444007e-dc75-45d6-b6da-dbd4352ff7c2)

I had the same problem and used the command line to identify processes I had started

**Comment by EdwardPiwowar** [comment]
Good point Thorvald. Next BBA builds will be limited to their processes only.

**Comment by ThorvaldAagaard** [comment]
Works fine
