### ISSUE TITLE
Negative double and other issues after a preempt

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#120]
0BB593A71BD9D50A1AE050B5E3E5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/95cbea81-60c6-4302-b35c-369d91b482a3)

Playing support doubles I know GIB also is using it after 1C-P-1D-(1/2 any), not jut after Major

Here X of 2H is described as negative. With a void in diamonds, that seems not to be right. Should it be explained as showing 4S?
On the actual hand I think 2S is the right bid, unbalanced with longer clubs and some extra.

3C is explained as 6-21, but I assume it is limited, as it is not forcing, It looks like a 3H bid for me no matter is south bids X or 2S

**Comment by ThePokerDude** [comment]
It got worse.
After south's double north should bid 3h because you want to force partner to game.
![image](https://github.com/user-attachments/assets/0e897a02-ff79-4032-abe5-c6dff8cb89a3)

**Comment by ThorvaldAagaard** [comment]
Agree

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/d36d7d73-5ce4-42cd-8c6c-ddce9bc7347f)

**Comment by ThorvaldAagaard** [comment]
![image](https://github.com/user-attachments/assets/43e3ce8e-884c-453b-a458-141800579294)
