### ISSUE TITLE
System clarification

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#123]
Why jump to 3C, I hope 2C is just normal forcing
02DE5CCEB9A0CA81A12A31235285
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e2f0dce2-abf4-4535-924c-f2b653466921)

**Comment by EdwardPiwowar** [comment]
Because for some systems 2C isn't forcing, I added a new option "1X-Y-2Z forcing".
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a4a72875-3309-4d95-8182-882503a16d47)
Then
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/41bba00b-17f9-45b1-90f5-efa7078ba726)

**Comment by ThorvaldAagaard** [comment]
Fine, this is also why BBA pass here
2C01FFF91D4722FCA87E2619AAE5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e2141fe9-587a-426a-b3e1-6b0228a474b3)
Even when not forcing I would still bid 2N with good stopper and a very useful CK

I think default should be forcing, as non-forcing only is after specific agreement

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/dea923f9-68e5-41c5-ba16-c9b45f192af1)
