### ISSUE TITLE
This bidding style is not OK

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#124]
0C60911A08DBE7CD94079550D2B6
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/6c1d49da-d54a-485a-8383-c78d81193fdd)

1H over call is fine but opposite a passed partner 4H directly could also be OK.

2H in the next round and then followed by 4H is bad. Instead of 2H then 3 or 4H but an overcaller should never bid three times if not partner involved in the bidding

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/96d0647d-b114-4f70-9870-ee90d915907f)
