### ISSUE TITLE
Don't bid 1N with 11

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#125]
And especially not with a fine 5-card suit
014F3B20F81DE5F398D7E7688E38
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/27e0017b-fa8c-4b71-8556-b4e900193500)

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/1523697e-d433-46f1-8e7e-04175ea1b075)
