### ISSUE TITLE
Another wrong penalty

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#126]
046F83C428E0AFC7ECC24BD939CF
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/32b07c18-c589-46f4-85ed-5ec749e2c7ab)
Do not expect tricks from a preempting partner

**Comment by ThePokerDude** [comment]
Better in 8137.
The double to 5h is still questionable.
![image](https://github.com/user-attachments/assets/b264d302-0cbe-4593-a630-7dac794edbea)
