### ISSUE TITLE
Why is this not just an 18-19 hand?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#128]
0D60187FC0886B5681FC7BED2936
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/267f526c-6fe1-44f5-97ad-f74774d87970)

If East overcalls 1S, North never bids again. What would 2N be in this sequence?

**Comment by ThorvaldAagaard** [comment]
I just checked the explanations, and it seems 2N is 17-18, and 3N is 19-20
Can we change that to standard SAYC, where 2N is 18-19 and 3N is a strong hand with long clubs, and typically short in partners suit (To good for 3C and thinking 3N is a good contract)

**Comment by EdwardPiwowar** [comment]
Corrected since [compilation 7561](https://drive.google.com/file/d/1pVJZMN4sFMRzI-rTaKV0otcvbt35jluh/view?usp=sharing)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/180213a1-6066-48cc-b7ee-1f903012138f)

**Comment by ThePokerDude** [comment]
Fixed in 8137
Not sure about the bidding after 2nt but the mentioned problem is fixed.
![image](https://github.com/user-attachments/assets/8b2a1e71-8cb7-445e-9b5a-7652df59cacd)

**Comment by ThorvaldAagaard** [comment]
As 2N can have any 4-card major I think South should Pass or bid 3H. 3D is 6-card
![image](https://github.com/user-attachments/assets/a465806e-74d0-42cd-a7a3-b46336064a42)

**Comment by EdwardPiwowar** [comment]
Yes, 3D = 6+
Next BBA
![image](https://github.com/user-attachments/assets/9e6250d3-7d20-44b0-9d98-6e33bdd62d5c)
