### ISSUE TITLE
Contract should be 4S (#30)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#13]
14E29176C3B96C7E618C56122A67
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/49f209af-36a2-4f82-a70f-4bbf4bd53d55)

It would be nice with a convention to show wee jump to 2N, but here I assume 3S is forcing, so East could just bid 4S

**Comment by ThorvaldAagaard** [comment]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b6cc82ad-76fb-4944-ae63-f2a7fc93da5f)

WBridge5 bids 4S as I would expect is standard in most systems, but note the explanation is 7+ spades.

The jump to 2N showing 18-19 is never with a singleton, as then there is a reverse available

**Comment by ThorvaldAagaard** [comment]
Still a problem in version 7933

**Comment by EdwardPiwowar** [comment]
Maybe 3S should be 6+?

**Comment by ThorvaldAagaard** [comment]
Yes, I think GIB and other play 3C as sort of checkback, so 3M is 6-card

Other interesting options: 
https://bridgewinners.com/article/view/xyz-vs-wolfe-sign-off/
https://bridgewinners.com/article/view/help-please-continuations-over-1x-1y-2nt/
http://www.aeyec.com/bidbase/Notes/New_Minor_Forcing.htm

**Comment by ThorvaldAagaard** [comment]
Fine in version 8105
