### ISSUE TITLE
Has there been a change of T/O doubles?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#130]
09C56224085D21329DFC1E41FB9A
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/19a5dde0-c7fd-45f1-a8b4-86b6d7b12d98)
I think on the 1-level you should stay with 3 in an unbid suit with minimum hands

**Comment by EdwardPiwowar** [comment]
It has always been this way, but if you want it otherwise, give a strict rule.

**Comment by ThorvaldAagaard** [comment]
I would follow https://www.bridgebum.com/takeout_double.php
```The takeout double is a double that asks partner to bid one of the unbid suits. The double usually shows 11+ points and 3+ cards in each unbid suit.```

18+HCP hands can double without the requirements of 3 in the unbid suits.

There are some fine rules on: https://en.wikipedia.org/wiki/Takeout_double

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/14c4083d-903d-40a7-8e28-faf8b4e14bc6)
