### ISSUE TITLE
Following the law

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#132]
0CF8B8630EDC78D1AF7E01C2D5C2
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3c8630d0-3f5f-40a2-8a98-738f29f2cb83)

It seems right to bid 3S in West

**Comment by EdwardPiwowar** [comment]
I'm closing because this situation no longer occurs because E passes.
