### ISSUE TITLE
Bid the game

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#133]
0F41A2863A9B0CD309A2E9E0D818
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/337a2b0f-3f4f-4536-b6c9-f6eaeb91a4d6)

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/a8a91061-e916-437a-8fc1-0bf766b432ba)
