### ISSUE TITLE
This is terrible wrong (#65)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#136]
46B1AF89AE417A055597E43A1035
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9ef92acf-b610-4c88-b746-b4c0f396b56b)

Can you please fix, so 4-card support always support before making bad decisions like the penalty double-

With support to partner, never pass a T/O D if the hand would have bid without the T/O D.

**Comment by EdwardPiwowar** [comment]
There is a problem here with "Support 1NT", which should mean 7-9 HCP and not 10+, which is defined by redouble.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/93bbb2da-d2b7-4ed6-8212-4cc3903a8d24)

**Comment by ThorvaldAagaard** [comment]
With support never RD. And BEN is not using "Support 1N"

**Comment by EdwardPiwowar** [comment]
But 2S is blocking after double, what do you suggest?

**Comment by ThorvaldAagaard** [comment]
On the actual hand 3S is a fine bid. But with no special agreements 2S should be 6-9 with 3 card support -  OK if a bit weaker. But a common rule is: Never pass with support and a hand that would bid undisturbed.

**Comment by EdwardPiwowar** [comment]
2S - 5/6-9 HCP (or 5/6-7 if support 1NT for some systems) with 3 card support:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/fc9303a3-f946-44c3-8b40-db82e1f8047c)

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/0748584a-a04f-4eea-936a-46cae830e09a)
