### ISSUE TITLE
Bidding 3N without a stopper seems wrong

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#139]
0E714064A325D3269419452D30F0
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1c675390-8048-4dee-b741-fb28129f192c)

But I assume it is not relevant, when 2C is forcing 1 round. But  the right bid is 3D

**Comment by EdwardPiwowar** [comment]
Both situations:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3aa8b836-a27a-4fe4-a75c-d96d17681214)
but I will check whether I have not regressed.

**Comment by ThorvaldAagaard** [comment]
Looks fine
