### ISSUE TITLE
Something went wrong here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#143]
22671F27B7437A96C271D1C1FD7F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e7ec580c-f292-4161-a2f4-e374200ca2a5)

Interesting BEN used 4N 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d68a1952-8f0d-4998-a261-d5b88eb986ff)
but the response to 4N was wrong

**Comment by EdwardPiwowar** [comment]
I see that the bot is now bidding 5C, which seems reasonable after 3S. Ben has better intuition.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/71c1d2cc-3a05-47e8-9d89-63b0598b4a6c)

**Comment by ThePokerDude** [comment]
Not resolved yet.
![image](https://github.com/user-attachments/assets/733b8f99-6b13-423a-9b7b-fd1fdcdfb549)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/0a572685-7d98-4c2a-bab9-beda0c80fcde)

**Comment by ThePokerDude** [comment]
Are we playing mixed or 1st round control cuebid?
In case of mixed at table 2 4s insted of 4nt would be correct.

![image](https://github.com/user-attachments/assets/acc96a87-2a7e-467e-ad47-2b7a3d163d2c)

**Comment by EdwardPiwowar** [comment]
4S if Crosswood is on:
![image](https://github.com/user-attachments/assets/c46018b3-2e1d-436f-9c5b-6588b04206ca)

**Comment by ThorvaldAagaard** [comment]
We are playing mixed cue, but I think it is a good rule, when not playing exclusion, that if first cue is at the 5-level it is always first.
