### ISSUE TITLE
20 HCP opposite an opening hand should make more than just a small slamtry

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#144]
2ED189DA6504E3F81EE84483C66F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3269ed80-c560-449a-b20f-cb2ac9b4c23c)

Even after a weak 2S East should check slam
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/4a24b90e-4587-4d80-9761-337ce2992499)

**Comment by ThePokerDude** [comment]
Still not solved correctly
![image](https://github.com/user-attachments/assets/18267506-add7-44f6-8d3d-414e702cb5f8)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/6c72321c-2a9d-4fc6-982b-d39b17f8f81c)

**Comment by ThePokerDude** [comment]
Fixed in 8140
![image](https://github.com/user-attachments/assets/2fc273d5-5b42-48e8-bcf3-41d85360e5b1)
