### ISSUE TITLE
Pass with 5-card support and 10 HCP looks wrong from East 

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#147]
756831306A72C292AB64BA2D0D1B
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e2d8981c-c129-4956-ba90-ef8f2dece871)

Also the explanation for WBridge5 looks wrong

**Comment by EdwardPiwowar** [comment]
I don't analyze it because currently E bid
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/0cb9cc18-4b5b-41cd-8bd9-61dbd6479d58)

**Comment by ThorvaldAagaard** [comment]
OK, and currently East will not open, and if Est open, then West correctly bids 2H
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/714f5887-8837-4e25-a8d3-4a41ca49bd96)
