### ISSUE TITLE
Do not pass for penalty with a weak balanced hand

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#15]
4FAEB2BFB1B1F5B8000297D5F104
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/41dcfdea-242a-413d-a373-96fd098f985b)

But perhaps the problem is the Double in South. GIB just bids 4S and WBridge5 jumps directly to 6S :-)

I think it is a good rule newer to pass a T/O double without any tricks.

**Comment by ThorvaldAagaard** [comment]
And an even worse example
0689FDAF60329EA23C66B65B47DE
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/775f9a0d-8cd8-498f-982a-6095b9ce868b)

**Comment by EdwardPiwowar** [comment]
1. The bot chose the WBridge5 style.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/be9e6704-06b8-4953-bfda-4af7ace8719a)

2. What problem?
3. What suggestion?

**Comment by ThorvaldAagaard** [comment]
I am OK with BOT-style of bidding 6S. In version 7724 it still doubles and North pass with 3343
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0634648c-a43a-47f7-a846-fc319e71ec11)


But do not pass partners T/O Double with 4333 and no points - This is for all T/O Doubles - from 4HX it is more penalty-based and it could be OK

https://bridgewinners.com/article/view/bidding-problem-2-ja084e5ol7/
0689FDAF60329EA23C66B65B47DE

**Comment by EdwardPiwowar** [comment]
This will be in today's update.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/9237d66f-40b9-4107-9c34-00d826da2f18)

**Comment by ThorvaldAagaard** [comment]
Seems to be working fine except
4FAEB2BFB1B1F5B8000297D5F104
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/99e9b15b-eb67-4399-8212-30f3dfbc4cca)

**Comment by EdwardPiwowar** [comment]
Next BBA (for some reason the bot is not bidding on the 6S directly)
4FAEB2BFB1B1F5B8000297D5F104
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2c4a1813-3c19-49b5-be7f-9591f1451004)

**Comment by ThorvaldAagaard** [comment]
Better
