### ISSUE TITLE
XX needs a bit of adjustment

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#156]
31F22FB94F4742D94E38B31CBEA5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/25b5f36c-fe7a-4d49-b5a6-c9de58cd568b)

I prefer bidding like WBridge5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/168b97b0-8466-4c58-a5fc-159169b3b36a)

So bid 1N in North, and adjust SS to 15+HCP

**Comment by EdwardPiwowar** [comment]
Corrected both
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/67412e8b-3e56-4373-b169-8a212b0905c6)

**Comment by ThorvaldAagaard** [comment]
Thx
