### ISSUE TITLE
5-card support not bidding

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#159]
04A3109B801A2831F1344EBF9C43
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/564379f2-81fb-493b-b3ce-6377ba0c1c17)

And the explanation for 3D is wrong as WBridge5 plays it preemptive it seems.

**Comment by EdwardPiwowar** [comment]
3D is strange and may cause problems. N is worth bidding - 3S is from 9 HCP.

**Comment by ThorvaldAagaard** [comment]
3D seems to be competitive, whatever that is
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/a04796a3-ecae-4f01-95a5-e5d2b533721a)

So if 3S is constructive 9+ HCP, what is then required for a preemptive 4S (Often right with 5+ card support)

**Comment by EdwardPiwowar** [comment]
BBA now interprets 3D correctly if there is "1X-(Y)-2Z forcing". But there is double.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/d1e07ca8-5156-4979-a733-178f70f0f2fc)

**Comment by ThorvaldAagaard** [comment]
Ok, lets us just close this for now
