### ISSUE TITLE
The impossible 2S

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#161]
0B1DDFE52A45B7F065DE20F7D36A
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/62dde9c1-7528-4039-956d-c75caa92cc52)

Here 2S from North will show a very good 3C raise - this is common for most players

The NS could bid game.

https://static1.squarespace.com/static/5127d3d2e4b0b304f0b6db24/t/5c8e551f104c7b066eb43ac8/1552831776048/3+%28269%29+The+Impossilbe+Spade+Bid+.pdf

But also worth reading: https://bridgewinners.com/article/view/the-impossible-two-spades/

http://kivabridgeclub.com/images/Impossible%202%20Spade.pdf

**Comment by EdwardPiwowar** [comment]
I added. It doesn't work in this hand 
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/1dfd096f-fa2e-43fe-b3f7-263e7e8abb91)
but
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/0dc473d2-56b3-4b5e-b948-5bed16a9f429)
and
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b8cab8d1-3b64-4f3b-af44-78a9b1ce971b)
