### ISSUE TITLE
Funny hand - Humans are bad to have at the table

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#162]
10DDC699D06240AA19A93ED2B488
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f370a4b0-0cc0-45ef-a324-f21f3994e8a5)

Playing 2NX seems not right with a know 9-card minorsuit.

Doing the same against EPBots, 3N that is the best contract is missed - East should probably bid 3S to ask for a stopper

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f80ea744-584f-41ef-9c21-df800dcc6612)

**Comment by EdwardPiwowar** [comment]
You don't seem to have the latest version.

**Comment by ThorvaldAagaard** [comment]
Latest version contains a virus
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/fcd3e854-905b-4b7b-81c5-26dd798beb72)

Probably false positive, but I am concerned it is another virus than before.

https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=Trojan:Win32/Fareit!ml

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/18257453-53fa-47aa-ad11-1cb244162006)

**Comment by ThorvaldAagaard** [comment]
How do you include the Bridge Calculator?
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/81129ee7-0762-4c7d-8c7b-ac23a43c0989)

**Comment by EdwardPiwowar** [comment]
Bcalc has always been used as DDS and its version does not change. But I noticed that the number of viruses reported varies depending on the compilation parameters and even the name of the file being compiled. I have no idea yet.

**Comment by ThorvaldAagaard** [comment]
Ignore the virus problem and look at the bidding problem
Can EW get to 3N?
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d2b1f66c-d4b4-4fb9-9c31-a5d9307bccc5)

**Comment by EdwardPiwowar** [comment]
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/473e965d-2e08-4d34-9c13-e55e8cff4fb9)
