### ISSUE TITLE
To pesimistic

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#166]
070D0985C96967B483B3A8EF1FDE
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/aa880a38-3978-420f-bf6e-2645fbad06b4)

with 4-card support and two doubletons South has a standard 4H-bid.

**Comment by EdwardPiwowar** [comment]
So it will be.

**Comment by ThorvaldAagaard** [comment]
OK
