### ISSUE TITLE
Bergen and 1M-3M

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#168]
When using Bergen and 1M-3M inviting, is 3M then always exactly 3-card support?

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/896f02c9-3f5f-4c5b-872f-745247b3d234)

Perhaps Bergen should enforve 1M-3M to be preemptive

**Comment by EdwardPiwowar** [comment]
Should be a block. BBA allows you to choose 1M-3M but you decide whether it is an invit or a block.

**Comment by ThorvaldAagaard** [comment]
So when checking Bergen, it should prevent selecting 1M-3M as invite

**Comment by EdwardPiwowar** [comment]
But then I can't test such configuration. I prevent selecting when there is a conflict.

**Comment by ThorvaldAagaard** [comment]
OK
