### ISSUE TITLE
5H looks wrong

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#170]
3AC17F7D6442238285E4CCEA9A4E
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f4b292cf-d2c8-4c72-94a6-d33b29d57de6)

As the description of 2H and 5H seems to be the same it almost looks like 4S is a transfer :-)

South should only bid 5H with some distribution

**Comment by ThorvaldAagaard** [comment]
In latest version South is no longer supporting - strange with 4-card support and 8 HCP

If not a mixedraise in 3D it is a preemptive 3H (Check explanation it should promise 4+ hearts)
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d9fb60c5-8596-4936-b9f9-5a7db022b4cd)

**Comment by ThorvaldAagaard** [comment]
South is now supporting, but North is no longer bidding the game
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d8cdd290-2b78-4dbf-b21f-ccc7ae70e285)

**Comment by ThePokerDude** [comment]
better with 8622
![image](https://github.com/user-attachments/assets/1d6a436c-dee2-4baf-87a3-bed2d757f0df)
