### ISSUE TITLE
Bidding after partners preempt

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#171]
4CACB16430D954FDD4E86FC2CA60
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c0d5c722-5963-42b3-a724-3c83f62813f3)

with 17 HCP it is normally right to bid after the preempt, 3H or 3N could both be right

**Comment by EdwardPiwowar** [comment]
The latest version bids 5C, which does not bring success.

**Comment by ThorvaldAagaard** [comment]
When 3n is an option  :-)
But just getting the common principle it is fine
