### ISSUE TITLE
1N after an overcall

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#172]
As overcalls are pretty sound bidding 1N with a good 14 HCP looks wrong
5CB4266B8EA7C4DC4BEB5A1A525F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3d3df045-a89c-4278-adf7-aac395980881)

Also 2N on 16 HCP is to pessimistic

**Comment by EdwardPiwowar** [comment]
If 1D is 8+ then 2NT is 15+, if 1D is 9+ then 2NT is 14+.

**Comment by ThorvaldAagaard** [comment]
8+15 = 23 So you expect the overcaller to bif again with 10?

I have a common principle, that when you overcall and partner invites, then if you had an opening bid you would accept (ie 12+)

So On the actual hand I would not accept an invite in 2N

**Comment by EdwardPiwowar** [comment]
1NT - 10-13(sometimes 14)
2NT - 14+
But not always with success.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/71bfba13-3aac-49e0-a689-517584536d37)
