### ISSUE TITLE
Wrong explanations

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#175]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9c80c64c-5b76-4e6f-be76-6a18545f2b64)
D is just a good clubs suit (ir T/O of diamond)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/16a6d176-dcc7-4ac4-8dfe-dfdcbc6032f4)

So pass is 4333?
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c13ddb64-a961-4cb4-a5cc-96b969f8a765)

**Comment by EdwardPiwowar** [comment]
Corrected
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/4a572a4e-8a7e-4c25-afee-e372dfc8516f)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/90e67827-4013-464d-9c88-1dc4494dcd5d)

Rebid after 1NT - only if opp are silent:
4333 - pass (but now it shows 2-5 2-5 2-5 2-5)
4432 -XX
5322 - 2X

**Comment by ThorvaldAagaard** [comment]
Fine, You should still consider having an option for escaping from 1NX - especially when playing Acol with weak NT

**Comment by EdwardPiwowar** [comment]
You didn't want to escape from 4333

**Comment by ThorvaldAagaard** [comment]
When I open 1N showing 15-17 I normally just stay there if doubled, when I run with 4432 we often end in a 4-3 fit one level higher.

Playing against robots there is an idea in running as you can escape undoubled or they bid on, but not in real bridge

**Comment by ThorvaldAagaard** [comment]
OK
