### ISSUE TITLE
Asking for Kings

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#176]
06888BEA19AAC51F975ECD4D4C11
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2c58dd70-7c28-4999-9266-98e5f6559cd8)

Asking for kings and then bid 7N when getting 0 kings seems very strange

**Comment by EdwardPiwowar** [comment]
Ok, he won't overwork himself.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/1b0ed988-feed-44e3-9a07-e5332a6f09dc)

**Comment by ThorvaldAagaard** [comment]
OK
