### ISSUE TITLE
XX from opener after 1N-(X)-P-(P)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#177]
1D14ED53B2914710BA4B374FAAE7
I am not sure it is a good idea to play XX as any 4432 when opened 1N, but I know for sure it is bad, when overcalling 1N

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/efe6acd3-808f-4fe0-b45e-c4c60acc17e6)

**Comment by EdwardPiwowar** [comment]
I removed it from overcalling 1N. This has no effect on the results.
