### ISSUE TITLE
Miscounting aces

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#178]
This deal is interesting for multiple reasons

1011893D96A5D95DF399BE1476AF
It was played in a match between BEN and WBridge5, and BEN missed bidding the slam after this sequence
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/fa1f80ca-1210-4bdf-87c6-3de5a2b9b171)

Now to detect the problem I loaded the deal in BBA , and undisturbed BBA easily bid to 6S
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b177ca5b-52ab-4d16-bb5a-3866b88a1c17)

But then when I let WBridge6 bid the EW hands it went crazy and miscounted the aces
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0ddabf91-8cdd-424b-81c9-0475350f9ce9)

First 2S is now 1-6 hcp, and is not correct with 7HCP and a good 6-card suit.

Secondly if keeping 2S as a good suit it could be an idea to use 4N for keycards

Also interesting how GIB bid the hand
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e18350f7-792b-48cc-8fe6-e2c9a72e26a4)

**Comment by EdwardPiwowar** [comment]
The opponents showed too many hearts and the BOT added the king to void. He forgot to lengthen the suite.
```
          AQx
          K
          Axxxx
          AKxx
xxx                  x
xxx                  AQJxxxxx
xx                   Qxx
Qxxxx                x
          KJTxxx
          Tx
          Kxx
          xx
```
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/d88f352a-6004-4c12-a3a3-9badb4fde69c)

**Comment by ThorvaldAagaard** [comment]
OK
