### ISSUE TITLE
Opening hand must bid after overcall of a preempt

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#179]
26BA266E65D7D67124EA218D07BC
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2c0d264b-5481-480e-a70f-7764f1ba9932)

Pass in North is a terrible error

**Comment by EdwardPiwowar** [comment]
Now 3X without jump is 11+ HCP (was 13).
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/9ae21046-f464-4019-9059-3eafd3213b35)

**Comment by ThorvaldAagaard** [comment]
OK
