### ISSUE TITLE
The result is the same

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#181]
But there are some errors in the bidding here
FF3BB8A2D5C23A9226784441EA4D 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2dce4d9c-9064-4e33-82a4-e50742e5ae3e)

Instead of bidding 2H I think D is better

When bidding 2H it is normally showing longer diamonds, so Pass to 2H is very bad

Souths 3C just looks wrong.

Sending WBridge5 into the competition results in
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/99cb9242-c19c-4689-bec2-0d3884a86bca)

I like 3C from North, and in the closed room 3D is also a bad bid. This time D is even more clear,

Also not that if I bid 3C as north, East will support to 3D with the fine 4-card support:
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3accb399-4d3c-45e5-938b-4d1450ee2d5c)

**Comment by EdwardPiwowar** [comment]
Systems from the simplest:
- WJ
- PC / Acol
- Sayc
- 21GF

**Comment by ThorvaldAagaard** [comment]
I am not sure, what you mean

**Comment by EdwardPiwowar** [comment]
Systems from the least complicated to program...:)

![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/97441185-cc14-404d-9f23-7e23bab0d3a2)

**Comment by ThorvaldAagaard** [comment]
Better, but over 3C I think East has a fine 3D bid with 4-card support and 4-5 HCP - 3D from West is ugly :-)

**Comment by EdwardPiwowar** [comment]
I'll work on it some more.
I think ben should play with all available systems.

**Comment by ThorvaldAagaard** [comment]
BEN can play any system, it all depends on the data used for training.
Problem with WJ is that the opponent don't know the system, and BEN is not good at explaining.

**Comment by ThorvaldAagaard** [comment]
In latest version East does still not give preference for Diamonds
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/6fb99fd1-d226-4b14-ba31-b9fd6c04a30a)
