### ISSUE TITLE
This is not SAYC but 2/1

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#183]
5A2CB62AB7BEC3C6ED7BBB9C5888 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/cb22dabd-c063-42ba-80c1-e67317dd8905)
Am I made sure there was no forcing 1NT

**Comment by ThorvaldAagaard** [comment]
05E6ACA6DB83BB8DD91BF0464037 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d23406c1-4bc0-4503-b86e-613b87b0f007)

Even worse

**Comment by ThorvaldAagaard** [comment]
The last is fixed in version 7836, but not the first.

**Comment by EdwardPiwowar** [comment]
I can't bid anything else, GIB bids the same.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/acf86c12-dc52-4762-bec9-a05d53dad43a)

**Comment by ThorvaldAagaard** [comment]
GIB is playing 2/1 - we are playing SAYC - it is a very normal 2C bid followed by a 3S invitational

**Comment by EdwardPiwowar** [comment]
First
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/51d33b32-fb3e-49d4-8b4a-20cd6e91a9f0)
second
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a68bb09f-561e-40b2-be69-9efdaec94191)

**Comment by ThePokerDude** [comment]
8622
The responses to 1s in sayc are fixed.
In the first on table 2 - the jump to 4s is optimistic but I'm fine with it.

 
![image](https://github.com/user-attachments/assets/16550f21-fe12-4c2b-a101-0a31427de52c)
![image](https://github.com/user-attachments/assets/591a771c-89a0-422e-bee4-d037f4254ffb)
![image](https://github.com/user-attachments/assets/5dc09de4-69e1-4405-a8ea-d1fe68246456)
