### ISSUE TITLE
1 Mi - 2N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#185]
325339FFD3576482240E8AB9E994
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/34e254cc-1b25-4c6a-8249-dce36e566687)

As we can have 4 D I think the requirement of 4-5 is wrong

Actually a missed game
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/4b0b0f73-fa4e-4ff4-9b2d-f29fa0149b9f)

But again it is perhaps just the problem with bidding 1N with 11 hcp
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/cb3ba089-ded0-4dbf-bfd3-83741e87e8c6)

**Comment by EdwardPiwowar** [comment]
The bot will avoid 1NT with 11 HCP.
4-5 clubs is just a calculation, not a requirement.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/bfd68f36-6cd6-42b6-b92c-2b18093ff26b)

**Comment by ThorvaldAagaard** [comment]
OK
