### ISSUE TITLE
Blackwood for Hearts

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#187]
0C01202BFB24DC3ABD4DB7956EE1
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/23bc0ddd-fcf7-4891-bb81-a3fdb22095e9)

Terrible bidding
133DAC232BBA5AD84D81A3287632
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/88c02cd1-507a-4953-a86e-77c82526c1aa)

And even worse

**Comment by EdwardPiwowar** [comment]
Some time ago I caused a regression.

![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5c67540e-41c1-4e3c-86a0-1cf17287a7d9)

![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/089cd7b1-b293-408e-8177-156f78596d0d)

**Comment by ThorvaldAagaard** [comment]
Just tried 133DAC232BBA5AD84D81A3287632 in latest version
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/6afa68a6-9d67-4df1-b902-6848d5fd3e1b)

Seems to be a difference between Blackwood 0314 and 1430, where only 1430 is asking for queen

**Comment by EdwardPiwowar** [comment]
Yes, using 0314 there is no space to ask about the queen.

**Comment by ThorvaldAagaard** [comment]
To me it looks like there is space in both situations as there is a relay below trump, and the 0314 is asking but not the 1430
