### ISSUE TITLE
Interesting hand

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#189]
0BF791C51630839262E039293D39
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/78697cc5-0080-4c29-a6ed-b0e7e3c2dd56)
Looking at the explanations I think 3H should be more like 11-14, so 4H is to optimistic.

It is also interesting South is so passive, at least a double of 2S or 3S seems more right.

**Comment by EdwardPiwowar** [comment]
E only sees 9 tricks, but he sees a chance of 10, so he tries 4H.
S is a bit confused, he will bid double.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/33ae7bae-7345-4254-91fe-d78fd22372ce)

**Comment by ThorvaldAagaard** [comment]
It is interesting what West should do over 2SX - Most advanced players (And what I think is best) is bidding the level we are committed to as the weakest response. So here 3H from West would be minimum, pass a bit better and new suit a trialbid.
4S is a bit optimistic, but is OK.

Another issue is the bidding, when the opponents double a cuebid like here, where North pass instead of showing invitational values. It looks like you have a common rule for that. So instead of pass to 2SX north should make a gametry.

**Comment by ThorvaldAagaard** [comment]
OK
