### ISSUE TITLE
Trying to get BBA bid like WBridge5 against WBridge5

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#19]
To get the best results, when letting BBA bid for WBridge5, when training against BEN I have tried letting BBA bid against WBridge5 with comparable convention cards.

There are some differences I hope you will look at

But first we need to have the same system and convention cards.

This [WBRIDGE5.INI.TXT](https://github.com/EdwardPiwowar/BBA/files/13366473/WBRIDGE5.INI.TXT)
should be downloaded and place in the directory with WBridge5, and extension .TXT must be removed.
It is defined as Sayc with the conventions
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/88696b72-5ee8-4395-aca7-d06a4f7a431a)

For BBA use this convention card
[WBridge5 - Sayc.bbsa.txt](https://github.com/EdwardPiwowar/BBA/files/13366507/WBridge5.-.Sayc.bbsa.txt)
should be used. Again remove the extension .TXT

Then bid some boards and compare the bidding
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/79272ef1-344c-441c-bcba-bf00ec2d2517)

What I have noticed is that WBridge5 overcalls much lighter, and WBridge5 will more often open 2C.

For the training I will probably have WBridge5 to bid the hands, but it would be nice with some alignment.

I am also pretty sure, that I haven't got all the checkboxes right in the BBA Convention Card, so please note it, if you find errors.

Looking thru some deals I think WBridge5 is not using Inverted Minors.

**Comment by EdwardPiwowar** [comment]
WBridge5 use 2C more often because 2C contains weaker hands and does not force the game.
Very strong hands are in the 2D opening.
It seems to me that in order for WB5 to read the settings, you need to set:
`Opposant=QUELCONQUE`

No Landy
![no landy](https://github.com/EdwardPiwowar/BBA/assets/150140020/5940b950-a9f7-40bc-8d25-7131e7c22bdc)

Landy
![multi-landy](https://github.com/EdwardPiwowar/BBA/assets/150140020/1d459d34-0e3b-49a0-b07c-1d5c2ab477db)

**Comment by ThorvaldAagaard** [comment]
I think that when playing 2C as strong it is possible to stop in 3Ma, and that means it is not GF,
Will BBA support that?

I have receive a copy of the .ini-files for UCBC and here the Opposant=QUELCONQUE is included - but only for SAYC
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b6527981-4789-4f38-9b13-5710c1f46218)


But the first problem is that when you distribute BBA, there is included WBridge5.bss that might or might not match the setup of WBridge5.

So I attach the 3 ini-files I have received:

- The one that is WBRidge5.SAYC is the his conventions being used in that system for the bots that can't use SEF (Cinquieme Majeure).
- The one called WBRidge5.WB5 is his WCBC championship setup against the bots at the WCBC that are used to playing him like Micro Bridge 13.3,Q-Plus 15.7, and Shark 2.1 2024.
- The last one called WBRidge5.SEF is for the bots that can't use conventions like Rodrigues, and Collante like Meadowlark. 

So I will recommend that we have 3 .bss files matching this and included in the zip-file,

About Landy it looks like WBridge has both Landy and Multi-Landy
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3510c3cb-0d26-40a1-bf5d-69771d168722)

and BBA has only Multi-Landy.
In the zip-file is also the one we want BEN to use
[wbridge5 Conventions.zip](https://github.com/EdwardPiwowar/BBA/files/13378207/wbridge5.Conventions.zip)


I am not sure how this is best handled, but the relation between the WBridge5.ini and the corresponding .bss file is important,

**Comment by EdwardPiwowar** [comment]
BBA supports strong 2D, but I don't think it's enough. 2D is part of SEF and BBA does not support SEF. I think it would be much easier to fight WB5 using Sayc. According to the regulations, we do not have to use SEF.
Then we would only need one INI file, which must have the right name to be loaded automatically into WBridge5 (name "WBRIDGE5.INI" only?).
For me it doesn't matter what files I include in the BBA distribution.

**Comment by ThorvaldAagaard** [comment]
WBridge5 read from WBRIDGE5.INI - I don't think it can take it as a parameter
I suggest you create two files:

- WBridge5-Sayc.bbs and WBridge5-21.bbs and include the WBRIDGE5-Sayc.INI and WBRIDGE5-wb5.INI in your zip-file

Then when SAYC is selected copy  WBRIDGE5-Sayc.INI ->  WBRIDGE5.INI
Then when 2/1 is selected copy  WBRIDGE5-wb5.INI ->  WBRIDGE5.INI
Then we keep away from SEF for now
But we still need to be sure that the .bss-files match the .ini files

**Comment by EdwardPiwowar** [comment]
WB5 does not appear to use 21GF.
In SEF two over one is not GF, but it tends to become; perhaps the majority play it as 90% GF (Mike Lawrence's style).

**Comment by ThorvaldAagaard** [comment]
According to Yves I think WBridge5 is 2/1 GF, but I am not sure
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d88d9988-9de6-44e0-8475-b6d5522db11a)

Do you have deals that contradict this?

**Comment by EdwardPiwowar** [comment]
Maybe I'm wrong. I'll check it soon and let you know.

**Comment by EdwardPiwowar** [comment]
WBridge5 system does not have Jacoby 2NT by default.
[TEST1.pbn.txt](https://github.com/EdwardPiwowar/BBA/files/13380502/TEST1.pbn.txt)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/029da6bd-ba54-49bb-ada1-6f4e4345b63b)

**Comment by ThorvaldAagaard** [comment]
Correct - It should only be ON, when it plays SAYC

**Comment by EdwardPiwowar** [comment]
[TEST2.pbn.txt](https://github.com/EdwardPiwowar/BBA/files/13380590/TEST2.pbn.txt)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2be688c3-91d5-44a0-9638-af6b34ebf226)

**Comment by EdwardPiwowar** [comment]
[TEST3.pbn.txt](https://github.com/EdwardPiwowar/BBA/files/13380641/TEST3.pbn.txt)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/9215d91d-cfc4-45b0-881a-9784963e83bf)

**Comment by ThorvaldAagaard** [comment]
Using the .ini for SAUC I get this:
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c3162692-8588-4a02-9615-72d6ea6315d2)

**Comment by EdwardPiwowar** [comment]
The suggested files are added to new compilation. Contains default WB5 settings for Sayc and for WBridge5.

**Comment by ThorvaldAagaard** [comment]
Fine. When starting WBridge5 from BBA should I copy the ini-file first, or is that done autimatically?

**Comment by EdwardPiwowar** [comment]
Manually.

**Comment by ThorvaldAagaard** [comment]
I will close this for now, and report back with more specific situations.
