### ISSUE TITLE
Strange overcall

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#193]
2C747060164E2CD70C726520F316
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3716aab8-8ad5-449a-b486-c7c8e76de879)

Perhaps we should have a global setting: Bid 6-card minor before 5-card major

Also a problem here
0ADED2A6BC06D1993E1026B0AF4F 
        
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8bb1f9dc-ab1d-45e8-be3d-86ff940bfcbb)

**Comment by ThorvaldAagaard** [comment]
The second is solved in version 7836

**Comment by EdwardPiwowar** [comment]
The first hand is as below, but with opponents 5-0 and 0-5 it does not bring success.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5c49b471-07f4-4a51-b64a-3e124f00ace0)

**Comment by ThorvaldAagaard** [comment]
Fine as long as North bids 2C :-)

**Comment by ThorvaldAagaard** [comment]
OK
