### ISSUE TITLE
Why is BBA showing this as balanced?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#194]
0088A32DC2E04055C7CC9E84E6EA 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/98c61aa0-ce24-428d-bd57-1b2c73883cfb)

Could be right if singleton A or K, but not Queen

**Comment by ThePokerDude** [comment]
Fixed in 8623
![image](https://github.com/user-attachments/assets/c50d9551-a0d8-4114-a6ff-47e45a0228da)
