### ISSUE TITLE
Preempter bids again

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#195]
085AB94AA480B87A28F26721CADE 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3643aaad-05e5-4408-8aad-0c7086b1f9bc)

For me a bid like 3D here is just showing: I made the wrong bid the first time

**Comment by EdwardPiwowar** [comment]
Yes, bot made the wrong bid the first time.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/c1960573-13a5-4069-8a64-d4e7ef619aa9)

**Comment by ThorvaldAagaard** [comment]
Perhaps South should bid 4D over the double? Just following the law

**Comment by EdwardPiwowar** [comment]
A third-hand bid allows for 6+D.

**Comment by ThorvaldAagaard** [comment]
Yes, that is always interesting, that when you add more freedom it restricts partner, that is why I just bid normal, then it it goes wrong adjust the opening bid, not the support :-)

I will close
