### ISSUE TITLE
Interesting 2N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#197]
0FBB77B8245C77565CAF5BA0874D 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f0cd2601-607a-4e75-ab05-2d1a48d5b652)

I assume East is to weak for 3S showing 4-6 and 6+ spades (I would add a point for the 7th spade)

https://bridgewinners.com/article/view/bidding-problem-2-i7xw2g21nt/

**Comment by EdwardPiwowar** [comment]
3C is not a good bid.

**Comment by ThorvaldAagaard** [comment]
In my book it is still the right bid, 3N is just wrong

**Comment by EdwardPiwowar** [comment]
Or maybe E should passes?

**Comment by ThorvaldAagaard** [comment]
Yes, it would be interesting to know what a Pass would mean.
But also it is interesting that we can't show 6-4 in the majors after 2N - I think that is a common problem.

Perhaps in some distant future you will add american stayman after 2N

**Comment by ThePokerDude** [comment]
8623 - basically same.
It is a difficult sizuation as 3c would be probably opponent's suit.
So we are forced to "lie". A smaller lie would be 2h instead of 2nt.
![image](https://github.com/user-attachments/assets/3d6d0d1d-5ea6-4967-99d0-2943d76cc31f)

**Comment by ThorvaldAagaard** [comment]
If no double the bidding will go
![image](https://github.com/user-attachments/assets/905e8dfb-3242-49eb-9db5-ec4a1d05439d)
I think the solution to this is Pass by East allowing opener to XX to show a load of clubs.

So I am closing this, as it is a special board, that even experienced players might not be able to solve.
