### ISSUE TITLE
Something went wrong here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#198]
1745CAB99FFC939630C24B5AA570 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1aabde9d-8512-4c8b-a485-a9aa815f17b0)

I think South should bid 2C as Pass or correct. The RD from East does look wrong with a bad 7 hcp

**Comment by EdwardPiwowar** [comment]
Anything can happen here.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/56782393-cf6e-4cfe-bfd2-109d2deb122e)

**Comment by ThorvaldAagaard** [comment]
Still a problem in 7836
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/09bfbc11-dc22-42fb-8785-6deb5d755f19)

**Comment by EdwardPiwowar** [comment]
XX is penalty 7-11 HCP.  What is wrong?
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b974fa03-5689-4a66-ac3f-bcdf1bb2414e)

**Comment by ThorvaldAagaard** [comment]
X is a 5-card minor and 4-card major or penalty - after XX it is mostly the first, so South should look for the minor.
X is defined as T/O.
But the main problem might be the X from North as 15 bad should not double

**Comment by EdwardPiwowar** [comment]
This will happen if multi-landy is selected:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/6d2aed74-9c81-4cbd-a128-2f9403df21fc)

**Comment by ThorvaldAagaard** [comment]
OK
