### ISSUE TITLE
I think BBA got confused

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#199]
14178E6C20D81213F220B651D56F 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f812fb54-90cf-438b-a8a0-36b908367015)

In a match between WBridge5 and BEN West bid 2D in this sequence, and BEN got confused and passed.

So I entered the 2D and now NS forgot to double and I think 4D (even though West showed 7+ D) is bad bid

**Comment by EdwardPiwowar** [comment]
There will be a double from each of NS.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/26bfeb1f-9994-4a7b-9e3a-9d1630c7cd58)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3e76c7e6-e1c6-4701-8f9d-29cd2040ac3e)

**Comment by ThorvaldAagaard** [comment]
OK
