### ISSUE TITLE
Error in generated PBN-file

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#2]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/570059db-de8d-4b1a-b1e2-1a2674be9ca5)

Room is mentioned twice, and the second should be removed

**Comment by EdwardPiwowar** [comment]
BBA - compilation 7319.
Second  entry is removed. 
Conventions are added to pbn files.

**Comment by ThorvaldAagaard** [comment]
Second entry for room is now fixed, but I did not see the conventions
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c138839c-674e-437e-8377-7b33691c9c1d)

**Comment by EdwardPiwowar** [comment]
The convention is added only if there is a difference in the selected conventions CC1 and CC2.

**Comment by ThorvaldAagaard** [comment]
Nice with the difference, but I would like them all, so it is possible to retest deals with the same conventions

**Comment by EdwardPiwowar** [comment]
Like this?
% PBN 2.1
% Generated by Bridge Bidding Analyser v. 7322
% https://sites.google.com/view/bbaenglish
% 
% CC1 - WJ.bbsa
% CC2 - PC.bbsa
% CC1 - 1D opening with 5 cards
% 1-2 - 1M-3M blocking
% 1-2 - 1X-(1Y)-2Z weak
% 1-2 - 5NT pick a slam
% CC2 - Bergen
% 1-2 - Blackwood 0314
% 1-2 - BROMAD
% CC2 - Cappelletti
% 1-2 - Cue bid
% 1-2 - DOPI
% 1-2 - Drury
% 1-2 - Exclusion
% 1-2 - Fit showing jumps
% 1-2 - Fourth suit
% 1-2 - Gambling
% 1-2 - Gerber
% 1-2 - Inverted minors
% 1-2 - Jacoby 2NT
% 1-2 - Jordan Truscott 2NT
% 1-2 - King ask by 5NT
% 1-2 - Leaping Michaels
% 1-2 - Maximal Doubles
% 1-2 - Michaels Cuebid
% 1-2 - Minor Suit Transfers after 1NT
% 1-2 - Minor Suit Transfers after 2NT
% 1-2 - Mixed raise
% CC1 - Multi
% CC1 - Multi-Landy
% 1-2 - Namyats
% CC1 - Polish two suiters
% 1-2 - Quantitative 4NT
% 1-2 - Responsive double
% CC1 - Reverse Bergen
% 1-2 - ROPI
% 1-2 - Rubensohl after 1NT
% 1-2 - Rubensohl after 1m
% 1-2 - Rubensohl after double
% 1-2 - SMOLEN
% 1-2 - Splinter
% 1-2 - Strength Lawrence structure
% 1-2 - Support 1NT
% 1-2 - Support double redouble
% 1-2 - Texas
% 1-2 - Two suit takeout double
% 1-2 - Two way game tries
% 1-2 - Two Way New Minor Forcing
% 1-2 - Unusual 1NT
% 1-2 - Unusual 2NT
% 1-2 - Unusual 4NT
% CC2 - Weak natural 2M
% 1-2 - TEST
% 
[Event ""]
[Site ""]
[Date "2023.11.08"]
[Board "1"]
% 00AE2E1E53D36822F713E09119DC
[West "EPB 2"]
[North "EPB 3"]
[East "EPB 4"]
[South "EPB 1"]
[Room "Open"]

**Comment by ThorvaldAagaard** [comment]
Looks fine

**Comment by EdwardPiwowar** [comment]
Updated.

**Comment by ThorvaldAagaard** [comment]
Looks good
