### ISSUE TITLE
When opening a file with boards

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#20]
it always open in downloads. (For me at least)

Is it possible to remember last used location, so it starts there for the next file?

**Comment by EdwardPiwowar** [comment]
[compilation 7359](https://drive.google.com/file/d/1pVJZMN4sFMRzI-rTaKV0otcvbt35jluh/view?usp=sharing)

**Comment by EdwardPiwowar** [comment]
It only works for the duration of the session, I will add an entry in the registry later.

**Comment by ThorvaldAagaard** [comment]
It works fine within the session. 👍

**Comment by ThorvaldAagaard** [comment]
Working fine, closing issue
