### ISSUE TITLE
Terrible overcall

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#201]
74AB098F2018D974737C8CEDF38E 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/ba9ccf9f-c92a-4de7-b0cb-68a39995a814)

I prefer T/O-D any time

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/17101088-02df-4e0a-8763-36af514dbe34)
