### ISSUE TITLE
Balancing 1N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#204]
3BBE50AB8D4747D850AB4AB5EF3A 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/a4ea3969-3806-4e80-875b-855a371c8dde)

First it is interesting if East should bid 1N, some might and others might take the chance against 1S. Probably 1 down.

But after the 1N it makes no sense to double in south on a bad 15

**Comment by EdwardPiwowar** [comment]
Currently the bot passes.

**Comment by ThorvaldAagaard** [comment]
I know, but as a human I bid 1N, and the double from south is then not OK (borderline yes, but South should have opened 1N, that would have solved the problem)

**Comment by EdwardPiwowar** [comment]
I do not prefer opening 1NT with a very strong five major and a weak side.

**Comment by ThorvaldAagaard** [comment]
So when will the bot open 1N with a 5-card major? It seems very rare. But when you decide to show a 5-card major as suited, you should not double on a hand like the above (KnR = 14.3)

**Comment by EdwardPiwowar** [comment]
Currently
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/81e46904-1275-40ca-a180-8399b3c7a06d)

**Comment by ThePokerDude** [comment]
Fixed in 8623
pass is chosen instead of 1nt. When confronted with 1nt BBA passes and does not double.

![image](https://github.com/user-attachments/assets/b27081b4-4466-4ba1-8f21-f87c289a46a7)
![image](https://github.com/user-attachments/assets/40d011ce-ad5b-452a-a27a-2b0954f52159)
