### ISSUE TITLE
North is to jumpy

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#205]
024645E396663F5A15E8B036AE93
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/50d74b81-83b0-4f5e-a8b4-18a3e600983d)

After the 1S overcall, North has no reason to jump to 3D as partner did pass over 1S

If no overcall, then jump to 3NT is stretching. 6322 should be treated as balanced, so 2N is more right than 3N, but 3D could also be OK.

**Comment by EdwardPiwowar** [comment]
After the 1S overcall 3D = 7+:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5e1137cc-8243-442b-9b78-55e04071ab7b)
After the 1H
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/00806cce-f8da-440a-978d-0474f6ca50f7)

**Comment by ThorvaldAagaard** [comment]
OK
