### ISSUE TITLE
Pass is wrong here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#207]
4E0C3167692595E35FC5CE78AFE0
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/49cb5739-9e45-4c52-8858-82d8a2d93834)
WBridge5 upgraded the opening hand
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0b149fde-cc3d-4c66-8e06-6f48f9adf25f)

**Comment by EdwardPiwowar** [comment]
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b669d8a0-8357-494d-ba17-18e96189627f)

**Comment by ThorvaldAagaard** [comment]
Seems a bit to optimistic. After opening on the one-level you should never drive to slam after a minimum response
