### ISSUE TITLE
To weak to go for penalty

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#209]
5B15BAFB006D255C300B816E647A
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/4d926746-1812-465b-8fad-de7237913bd5)

**Comment by ThePokerDude** [comment]
Fixed in 8623
BBA bids 1nt instead going for penalty.
![image](https://github.com/user-attachments/assets/f5a83899-123b-4765-820d-27ff899f674e)
