### ISSUE TITLE
Error when importing a PBN-file

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#21]
I have some pbn-files and I merge them into one file

The four files each loads fine, but when I merge it into one I get this error
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3340f442-1a28-4d0b-9246-f6d8fe6c9b38)

Now I assume I made an error when merging the files, but is it possible to get some information about the line/board, where the error is?

BBA stops loading after the error, and here is an example
[All.zip](https://github.com/EdwardPiwowar/BBA/files/13384421/All.zip)

**Comment by ThorvaldAagaard** [comment]
I was thinking about converting the deal to BBA-format before loading it.

Another way could be to remove play and bidding when merging the files, will that reduce the memory-load?

Can you read .BEN files as input (Extension not allowed, when browsing)

I have also been thinking about adding room to the .BEN-file, when playing different systems.

Finally we might just have to split the input in multiple files.

**Comment by EdwardPiwowar** [comment]
I may add support for ben files once the standard is finalized.

**Comment by ThorvaldAagaard** [comment]
For now I will go for the BBA encoding

**Comment by EdwardPiwowar** [comment]
:+1:

**Comment by ThorvaldAagaard** [comment]
With the latest version it loaded my file with 250.000 deals, so I will close this issue for now, even without seeing the new error message.
