### ISSUE TITLE
A missed game

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#214]
2738AE466CDB51E170BAFD995806
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/4567b1c0-1fc6-4732-84cd-27aeb7538f07)
Without overcalls all is fine

But if East overcalls 1S and West supports to 2S, then North is getting in trouble and bids 3C and missing the game

BEN is close bidding 3N
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e5efc3fe-fea4-42fc-9862-ad5b57ee0928)

Perhaps North should have used inverted minor

**Comment by EdwardPiwowar** [comment]
2718A64E64FB51E170BAFD59980E
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a8bba757-9ecd-4ed2-a4d9-4e9cc1237fb4)

**Comment by ThePokerDude** [comment]
8623 - fixed
![image](https://github.com/user-attachments/assets/e8d9989d-0be8-4df1-ac80-23c82f48ee1f)
![image](https://github.com/user-attachments/assets/ca6345e3-3777-4ce0-8807-2354bf05fe13)
