### ISSUE TITLE
Pass is not showing support

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#216]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/81c1ca3c-5161-4d4b-82e0-c2972f91f2a8)

The neural network suggest Pass in South after the T/O double - It should be a common rule, that Pass denies 3+ support and a decent hand

**Comment by EdwardPiwowar** [comment]
679B46AF40F0B60549F04FA7C72E
Manually 1H because bot bid 2H.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/33ab7156-3bda-41dc-914a-ed58128529e8)
I don't know what is wrong.

**Comment by ThorvaldAagaard** [comment]
South should not Pass 2HX (If North bid only 1H it is even more obvious).
Either RD or some forwardgoing

The problem is that when the opponents double negative it looks like BBA just Pass with a hand with support, because it calculates, that 2HX 10 tricks is better than 4H 10 tricks. It is a common robot problem, that ot don't understand that the double will not be passed

**Comment by EdwardPiwowar** [comment]
2H and 3H are weak. RD needs more HCP. Support cue bid is available but bot calculates 8 tricks only then passes.

**Comment by ThorvaldAagaard** [comment]
It calculates 8 trick and yet it bids 3H on the next turn. 2C is the right bid. And 2H should be 8-10 here so that is also an option

**Comment by ThePokerDude** [comment]
8623 - fixed
![image](https://github.com/user-attachments/assets/bddf2f25-cda2-4863-bb8d-dcdeaf192f8d)
![image](https://github.com/user-attachments/assets/08bd598b-49cd-4d70-8947-a0d0834b0264)
