### ISSUE TITLE
What is the requirements for a weak 2-opening in BBA

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#218]
90AED2EB548A598093D1F3F2104A
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0df52d81-3a73-4ce4-aab4-e201dbd0e89b)

WBridge5 will open 2D on the North hand, and 2H on the East hand

**Comment by EdwardPiwowar** [comment]
A good 5 handicap which may be slightly adjusted down if side suit or up if ugly HCP (vide 2H).

**Comment by ThorvaldAagaard** [comment]
It would be nice if we could configure that, as WBridge5 is much more lose than BEN - and I think BEN is fine, but when creating training material we need to bid like WBridge5.

For me 2D seems wrong (to weak, and to long a suit), but 2H seems perfect

**Comment by EdwardPiwowar** [comment]
Referring to the issues with shorter suits, I will introduce third-hand openings at 2 of fives and at 3 of 6s.
Tests show that this can bring tangible benefits, especially in relation to WBridge.

**Comment by ThePokerDude** [comment]
Fixed in 8623
![image](https://github.com/user-attachments/assets/32e89283-5fe9-416d-b111-220d488d3f18)
