### ISSUE TITLE
XX must show 1st round control

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#220]
0C1EBB000ABD9FBB0B9C76A6DED5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0ea7ef11-4642-426b-b010-e67749545d01)

No idea in showing 2nd round control, when partner already has show a control

**Comment by EdwardPiwowar** [comment]
It will be corrected
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b87a397b-9b7a-4e31-81c6-b4f63dec855e)

**Comment by ThePokerDude** [comment]
Bidding is much better with 8623
As you have all controls yourself you can go directly for RKCB.
I do not know if the original issue is fixed or not
![image](https://github.com/user-attachments/assets/feafeee3-7188-455d-901d-b0ed2094d735)

**Comment by ThorvaldAagaard** [comment]
Closing as bidding now is different
