### ISSUE TITLE
Penalty double

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#223]
BBA starts to remind me about a partner, where I removed his X from the bidding box :-)

9DFFAA4604DCD374AB35D8C29247
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/4f83d4e9-26f7-4b9c-8812-0bb81272af10)

Result is fine, but the double from East is really not bridge, unless it is showing singleton.

In general we should never let a bot double based on what partner has shown, Better just to let partner decide

But this board also got other errors. East without controls and just 3-card support should bid 2S. After an inviting 3S South should accept his fate, and not bid on 15 bal, T/O doubles on the 3-level should have distribution or a stronger hand. If 3S was preemptive D could be right.

**Comment by EdwardPiwowar** [comment]
Someone said that if you have successful all your doubles, it doesn't mean that you don't have enough doubles:)
BBA doesn't know the forcing pass yet. 
E calculates 26 pts, which is enough for 3S. E will bid 2S with a slightly worse hand.
I will raise the limit for S to 16 HCP.

**Comment by ThorvaldAagaard** [comment]
I agree that sometimes a doubled contract will make, but the lesson to be learned is that is should mainly be in highly competitive situations.

Here East has minimum, no tricks and if X is extra, then I think East should bid 4S to show minimum.

But looking at the deal the XX is also wrong, we just want to play 4S Red vs green, and not collect 3-500.

**Comment by EdwardPiwowar** [comment]
CLS17 - current version, DLL17 - old bot.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/10e7c633-ca39-454d-b7a2-09d8f0c0d141)

**Comment by ThePokerDude** [comment]
Fixed in 8624
![image](https://github.com/user-attachments/assets/7ac60c04-7df1-4b96-a09f-2242ddad3fac)
