### ISSUE TITLE
Explanation needed

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#23]
When bidding a match the analyses line look like this
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9261faf3-5a12-4d3c-9c4a-37d946e8ebe8)

When both single and double dummy are selected, what is then shown in MP's and IMP/d

How is MP calculated? Looks like it is Board-a-match

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/6e1bd17c-ac0c-41d8-90f2-2626c61df102)

**Comment by EdwardPiwowar** [comment]
MPs and IMP/d are calculated independently for SD and DD.
If you check off DD, the program will stop counting DD results.
Percentages are calculated as per match.

**Comment by ThorvaldAagaard** [comment]
So this means
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/629a44b9-e576-4882-8b41-91122961337e)

Single dummy NS scores 0,804 Imp/Game
and double dummy EW lose 1,196 Imp/Game?

**Comment by ThorvaldAagaard** [comment]
But colors match team 1 and 2, so I expect score to be for the matching color

**Comment by EdwardPiwowar** [comment]
Scores are for the matching color.
More real difference is for 50 000 boards.

**Comment by ThorvaldAagaard** [comment]
Now I think I get it: 
Scores is always for Team 1 and the color is showing who leads, right?
So scores are not for matching color

**Comment by EdwardPiwowar** [comment]
Scores is always for Team 1 and the color is showing who leads, right - true.
I dont know what "So scores are not for matching color" means, but you know I think :smirk:

**Comment by ThorvaldAagaard** [comment]
"So scores are not for matching color"

Normally, when you have two teams with different color you show the score for each team in the teams color (That is matching color) - You always show the score for team one, and use color for who is leading. Just first time I have seen that, but that is fine, now I know. So I close this,
