### ISSUE TITLE
North forgot the system

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#230]
15FC338F2F265A599F8ADD95F734 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/20512cd3-99e0-4a4b-bf7c-572eae8336d3)

Thinking about 3D North forgot to bid 1S

**Comment by EdwardPiwowar** [comment]
I guess he remembered.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/7e0f31b7-cc53-4185-89e6-ebecc28c0143)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/02c161ce-8b4b-4374-9ae0-ed28689c4c6a)
