### ISSUE TITLE
Automated bidding creating a .ben file

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#231]
I was looking at some strange bidding, where BEN did use the WBridge5 convention, and noticed the following in the generated .ben-file

```
T5.A432.QT98653. J94.Q85.AKJ.9742 732.KJT76.72.QJ5 AKQ86.9.4.AKT863
N E-W 3D P P 4C P 5C P P P
T5.A432.QT98653. J94.Q85.AKJ.9742 732.KJT76.72.QJ5 AKQ86.9.4.AKT863
N E-W 3D P P 4C* P 4D* P 4S P P P
```

So we are telling BEN 2 different bidding sequences with the same hands

This match what i see here:
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/706be2ba-52b0-4791-810c-939bc3e4ad72)

It looks like the second bidding only is included if different

It would probably be better to add an option, so only getting first room or both rooms (like for .pbn)

**Comment by ThorvaldAagaard** [comment]
Yes, in a way, but currently I am only training BEN to be NS, so just open room is fine for me.

It is OK with both rooms in same file, I just checked long time ago and concluded that it was only 1 room as all deals were different. So can you make it either both or none it is fine (None will same time)

**Comment by EdwardPiwowar** [comment]
That is:
- first room
- second room
- first + second if different bidding (note that the bidding may be identical but the meaning may be different)

**Comment by ThorvaldAagaard** [comment]
I am fine with just one room, then I can manually switch seats and bid the other room if needed. If both rooms, just include the bidding for both tables without comparing the bidding. Then I will be able to process the file without having to add the missing bidding, and I know odd number are open, and even are Closed.

So 1 room or 2 roooms (What I call alternating)

**Comment by EdwardPiwowar** [comment]
Done
