### ISSUE TITLE
Very strange bidding

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#236]
DADF3108AD38292899380A9835E8
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/11ab85fd-de81-4da5-b072-ef4cfe7cd9d1)

First a preempt, then the prempter bids again, and in the next round it uses exclusion

I think BEN got it right by bidding 5D directly over 1S

Red vs green I think the right bid in North is 4S directly

**Comment by EdwardPiwowar** [comment]
4S is rather preemptive. But BBA needs to start learning from Ben.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/7cdde528-1b32-45c2-9ddf-1b82586b774e)

**Comment by ThorvaldAagaard** [comment]
https://bridgewinners.com/article/view/bidding-problem-2-c9anc0w457/

**Comment by ThePokerDude** [comment]
I think the bidding now is pretty ok.
![image](https://github.com/user-attachments/assets/d1fd4255-688a-4c08-a55a-dbdf6299ed67)
