### ISSUE TITLE
Another strange sequence

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#237]
0621F123A82BDE154446E46FDEEE
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c500991b-162b-4b0d-911d-55a67dacf411)

Normal without the overcall, but after 3S it is just wrong.

Pass to 3S is wrong
After a preempt in 3H South should not bid again
4N is just a joke :-)

**Comment by EdwardPiwowar** [comment]
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/619e1e15-c704-4358-9c65-3d77671aceaf)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b5264031-3a68-44ee-b154-550dc5f80287)
