### ISSUE TITLE
Lebensohl

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#239]
In Lebensohl the idea is to use 2N for weak hands, so any natural bid will show around 8-10 - Not good enough to force, but some values
2FC0D63E661CE1B4CA53FFA7C651
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d718052a-6c95-4730-9118-4ac29f5186b2)
So here 3C is the right bid, and not 2N as transfer and then 4C

**Comment by EdwardPiwowar** [comment]
BBA bids 3C which cannot promise a HCP after a double as in other situations.

**Comment by ThorvaldAagaard** [comment]
In Lebensohl 3C is 8-11-ish, any 0-7 will bis 2N as transfer to 3C

**Comment by EdwardPiwowar** [comment]
Yes. I corrected it. 3m is now from 10-12 HCP.
2FC0D62E761CE1B4CA53FFA7C651
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/4bf5d94a-00db-4cd7-8bbf-cc33c2a82fd2)

**Comment by ThorvaldAagaard** [comment]
3C is invitational, so more like 8-11- and North should pass 3C

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/2902df11-7239-48b6-ba72-8d19be3396c4)
