### ISSUE TITLE
Camrose Board 92

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#248]
5ED719BF42A2F9894CF8AEA90433
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/52e40410-900a-4319-93e2-8520c6cdc5eb)

I think 3N in East is a bad bid.
If I change it to 1S 4th suit, I think 3N should be something else as it is very preemptive
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/ea0b1403-12ad-4fa2-944d-19bfb9c26ac9)

**Comment by EdwardPiwowar** [comment]
Next BBA, but I'm not sure if that's what you expected.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f9907304-e14c-4c36-afe6-e055e14ff9d5)

**Comment by ThorvaldAagaard** [comment]
That was a terrible bid
West should bid 1N showing 11-14, 2N showing 14-16, and 2N showing 17-19

**Comment by EdwardPiwowar** [comment]
First room for the fourth suit GF:
1N - 11-12
2N - 13-14
3N - 15-16
I think W can't have more HCP.
Second room for the fourth suit - F1.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/c1a1dd95-57e6-4c0c-be8e-f416bba8d78e)

**Comment by ThorvaldAagaard** [comment]
An unbal hand with 17 should probably not jump to 2H, But Easts bidding should be the same no matter if playing GF or not.
If not GF you can bid 1S on 10, so why jump to 3N on 13 bad. 
East could have a strong hand, so do not preempt partner

**Comment by EdwardPiwowar** [comment]
Next BBA (CLS players) - F1 like GF
5ED719BF42A2F9894CF8AE6A0433
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/99325e7d-e98a-4d4e-946d-bdfc7988dd93)

**Comment by ThePokerDude** [comment]
8627 - seems ok. I personally would bid 3nt after 2nt instead of 3c but it's not critical.
![image](https://github.com/user-attachments/assets/f5031c79-a2d1-45cc-8c8b-f513d7d47578)

**Comment by ThorvaldAagaard** [comment]
Generally BBA has a problem with just raising 2N to 3N.
I see no reason for 2N from opener as 1N should ve 11 to bad 14.
But I will close this
