### ISSUE TITLE
Bidding with WBridge5

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#25]
I was bidding a long match letting WBridge5 bid the hands
After about 800 boards WBridge5 crashed, and it was now impossible to start the match from that board, and I had to start from the beginning of the set

**Comment by EdwardPiwowar** [comment]
How did it crash?
BBA restarts WBridge if it is not responding.

**Comment by ThorvaldAagaard** [comment]
It was a crash with a popup. Perhaps I just wasn't waiting long enough for the restart
