### ISSUE TITLE
jump to 4 minor in competition

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#253]
![Screenshot 2024-03-11 085210](https://github.com/EdwardPiwowar/BBA/assets/11272970/36d2f322-1cd1-498e-b927-31b52db309cd)
well no idea how to get the pictures hopefully that worked.

So anyway epbot rebid 4 diamonds which should be forcing and a much better hand.

**Comment by EdwardPiwowar** [comment]
Focus BBA and Alt Gr + Print Screen and just paste. If you can also copy the BBA number from the menu, it will be much easier for me to analyze.

**Comment by EdwardPiwowar** [comment]
The W position shows exactly what it has, 3D would be stronger. I have no idea how to improve this.

**Comment by ThorvaldAagaard** [comment]
Why should 3D be stronger than 4D?  Explanation is 8+ diamonds, but interesting to play 4D as preemptive.

**Comment by EdwardPiwowar** [comment]
4D isn't preemptive, it shows 8 (strong 7) diamonds. Do you have any other idea for 3D and 4 D?

**Comment by EdwardPiwowar** [comment]
0FC89A05693A1AB756184E49DEDE
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5a488c3b-1c91-4389-85b1-bc8c41a33d8e)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/293cb303-ed15-4b93-957e-de21a6dbf4a4)
