### ISSUE TITLE
We need to improve the regression testing

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#254]
D479BCFB4DDEBE5C96D5253258A6
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/a23ebc87-e681-4c69-b7e4-9a2b49d30247)
East did not show the singleton in Club
Version 7949

**Comment by EdwardPiwowar** [comment]
Next BBA (maybe today if I solve the previous problem)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/30a1ab57-748f-49d9-90fb-775e38f22da2)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/0575acc7-9857-4b8a-b15f-c7182cdf042a)
