### ISSUE TITLE
After T/O double (#19)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#26]
195B0BF6CA3CA1AB260D8C5C44E6
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1cf284eb-3136-4129-9bc3-98fefbc05a66)
With 4-card support and 8 HCP south should bid something else than Pass

Looks like 2H is defined as 0-5 HCP

**Comment by ThorvaldAagaard** [comment]
Yes, BROMAD is OFF
When BROMAD is OFF I I assume the D is Just ignored = Bidding natural (Truscott still applies if selected)

**Comment by ThePokerDude** [comment]
Fixed with 8137.
I turned off BROMAD and "support 1NT".
8137 now bids 2h.

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/334c3f3b-9178-4ad2-abab-15ffa714f76b)
