### ISSUE TITLE
Virus warning when trying to download from google drive

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#262]
no download from google drive possible
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/1118439b-7523-4963-b3f3-4f695010b519)

**Comment by EdwardPiwowar** [comment]
The thread with updates and discussion (also about virus reporting) is here:
https://github.com/EdwardPiwowar/BBA/issues/137

**Comment by ThePokerDude** [comment]
thanks, downloading from the github link you shred worked without problems
