### ISSUE TITLE
opener often rebids with a minimum even when partner has passed.

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#264]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/52a2cf49-66d7-4347-a2a8-c135ff6bfe36)
09BC9D79035A1BE834321C655B31

this isn't very wrong.   I often see opener make another bid when it is maybe wrong.  I'll add more examples when I see them

**Comment by EdwardPiwowar** [comment]
I don't think it's possible to guess whether pass or 2C.

**Comment by ThorvaldAagaard** [comment]
If we can agree that 2C is at least 5-4, and some length in heart (otherwise South would double) 2S is wrong and a 2D preference is the right bid in North.

East should not Pass the overcall with 5-card support, so we are probably handling the wrong problem, as EW should bid the game without help from NS,

**Comment by EdwardPiwowar** [comment]
Next BBA. Now a problem with WE.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b0ec7e4a-895a-4c99-80cf-08800c6c1e70)

**Comment by ThePokerDude** [comment]
The rule (which here applies to east) "pass with any 0-11" seems wrong to me.
I'd suggest to implement at least two general rules:
rule 1: 3/4 card support with 6-10/11 is always a raise to the (at least) 2-level (for minors and majors)
not sure when to preepmt at 3 level though. So maybe for simplicity we leave out the "at least" statement:
3/4 card support with 6-10/11 is always a raise to the 2-level (for minors and majors)

rule2: If you see a guaranteed minimum of 10 combined trumps in a major suit and you are weak (0-11 as suggested by BBA),
you bid 4M (if not vul vs no vul).
In case vul vs non vul: 3M (preemptive) with 0-7 and 4M with 8-11.
For the vul vs non vul I'm not 100% sure.

**Comment by ThePokerDude** [comment]
It seems ifor BBA it's important if it's 1d 1h p or 1d 1h X
1066B5C29C08F5EA57222BED4D84
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/c74b04f0-32db-45ab-ad20-c952aa92a878)

**Comment by ThePokerDude** [comment]
East does not pass anymore. 
![image](https://github.com/user-attachments/assets/f61de3e7-4629-437e-8ecb-d4f865d39fee)
The 2c bid stays same
![image](https://github.com/user-attachments/assets/a07a2799-5fc6-4022-9834-ae6a1d6fd501)
