### ISSUE TITLE
1N p 2c p 2h p 3d - after this sequence things go really wrong - no matter which convention card

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#267]
The spade fit isn't found
1NT oppener's strength is shown as 19+ at 4NT
For WBridge the computer passes to RKCB

013D43E982BC8611D75A0CB030F0
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/1650fb97-1cc4-4f51-91af-cc62eef48c0d)

**Comment by EdwardPiwowar** [comment]
There will be no ask for aces with wrong trump suit in the next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/e8966879-8e65-43ec-8713-77b4925f3257)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/357f29ce-0519-4a82-a50c-a5e2b270da2a)

**Comment by ThePokerDude** [comment]
fixed
