### ISSUE TITLE
opener rebids 2nt over 1nt instead of dbl.

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#270]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/06b4222b-8162-40ae-9844-03ddc356800f)
0543147F3AF440AE90758859BEF6

opener should dbl 1nt

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/6bed75be-9aed-4f57-87d9-754638d21031)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/e1095f17-56c1-490e-9b0c-0cb2fa5821e7)
