### ISSUE TITLE
I have seen a few 1M 3M pass auctions where 4M is good

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#271]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/ddfae88c-d3fc-4845-8e23-46dbb7f76303)
1F86019B72DF2C1EF6421394EB39

opener often passes 3M where he shd bid 4M

**Comment by EdwardPiwowar** [comment]
I noticed that too. The next BBA will be a bit more willing to bid at 3M, but it won't work in this case. Perhaps S should bid 2C.

**Comment by ThorvaldAagaard** [comment]
BEN plays a hand in about 1 min, but a lot depends on the settings.

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/095bb71c-1072-44c6-9612-b221d51c1fec)
