### ISSUE TITLE
preempts make it hard but...

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#272]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/ef59238f-bf75-426a-803f-3c54ed52091a)
2177E8D2F26951B0821A0C90C831

someone has to bid my guess is west

**Comment by EdwardPiwowar** [comment]
W sees something like this:
```
          AT98
          QT97
          J9
          T98
KQJ3                 765
AJ82                 K65
A                    K87
QJ76                 K543
          42
          43
          QT65432
          A2
```

**Comment by ThorvaldAagaard** [comment]
Seems wrong - following the law they probably have 10 diamonds, so East will have a 4-card major

**Comment by ThePokerDude** [comment]
BBA description of east's X to 4d is 9-10HCP, -4s, -4h, -4d, -4c but east has 4h.
Generally - this description suggests east having a max of 12 cards (each suit max 3 cards).
This assumption has a logical flaw ;)

**Comment by EdwardPiwowar** [comment]
Then it looks better, but what next?
```
          AT98
          QT9
          987
          AT9
KQJ3                 765
AJ82                 K765
A                    K6
QJ76                 K854
          42
          43
          QJT5432
          32
```

**Comment by ThorvaldAagaard** [comment]
West just bid 4-card major, a hand that was strong and wanted to double and bid a suit, must bid something else

**Comment by ThePokerDude** [comment]
in the newest version the bidding got worse.
Both east and west are too passive.
East could/should bid.
But even if east passes west should find a 2nd X with 18HCP

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/78d192bd-f111-4896-809a-ca941354f348)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/8aef6c02-9398-4364-ab67-6a14ecc661a2)

**Comment by ThorvaldAagaard** [comment]
I think that if the hand is to bid 6C now, the previous Pass is an error

**Comment by EdwardPiwowar** [comment]
Compare
```
          KJ8
          KJT8
          KT9
          JT9
Q32                  AT9
A32                  Q964
432                  5
AQ62                 K8543
          7654
          75
          AQJ876
          7
```
and after the second double

```
          J87
          JT8
          KQJ9
          JT9
KQ2                  AT9
AK32                 Q964
32                   5
AQ62                 K8543
          6543
          75
          AT8764
          7

```

**Comment by ThorvaldAagaard** [comment]
The first double with 12 bal and 4-3-3-3 is not a T/O double

Whenever testing for the "correct" bid after a T/O Double you should give partner something like

Axxx
Axxx
x
Axxx

Minimum but right shape

**Comment by EdwardPiwowar** [comment]
Yes, no double with bad 12 HCP.
But after
```
W	N	E	S
	P	P	3D
```
W knows E has some HCP, the less hcp he has, the more E.

**Comment by ThePokerDude** [comment]
Looks ok to me. The manual X from East is interpreted as penalty. So bidding is consistent. 
![image](https://github.com/user-attachments/assets/01b13ffe-49e7-4ec0-acdb-bebf56eff629)
![image](https://github.com/user-attachments/assets/74e9cb1f-4e6b-46ce-b943-2a9dc2824a67)
