### ISSUE TITLE
you cannot pass to 4c when you have bid GF

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#273]
When 2c is GF then 4c is forcing
09035F67F1F3EB9A75405DB884B5
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/744dd39d-f489-4d26-972f-64bcaf4d2eaf)

**Comment by EdwardPiwowar** [comment]
Wouldn't it be better if S bid 5C? S is forced and must bid.

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/2b680055-878a-4f14-bba6-41f1b93fa610)
![image](https://github.com/user-attachments/assets/f841a9f6-17b9-4864-ae61-8ae1cae0bb39)
