### ISSUE TITLE
with  3-2-4-4 after 1d-1s the correct answer is 1nt not 2c

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#274]
1D7ED30FB85EBC510363E0F9B945
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/ddfb6054-8fa9-4224-ba56-9404b9104aa6)

**Comment by ThorvaldAagaard** [comment]
Agree

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/dd4c9817-5e24-43fa-b181-d338ff5c6f05)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/86d3ab0b-3f8d-4b01-a58d-bbeab9517cc0)
