### ISSUE TITLE
Questionable 5c bid. Strange reasoning behind 5c 1st and 6c then

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#279]
I think 5c is too pessimistic.
I don't really get why slam is not the right choice directly after 4d x but after 5d it is.
I see it often in human play but the reasoning there is "I was wrong with my 1st bid, I changed my mind now" :)

Some other strange thing
5c: 6-15HCP, 11+pts
6c: 6-13HCP, 16+pts
to me it seems not logical that a range of average 10,5 HCP is related 11+pts but a range of average 9,5 HCP is related to 16+pts

122103A1B94816777921EAE39B73
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/dd91eaad-85d7-46e6-9c21-1b0e56780b42)

**Comment by EdwardPiwowar** [comment]
The lack of 6C was a bug. 
These are unbalanced hands, it is difficult to rely on the 'HCP', but:
5C as the second bid is 6-15;
6C as the second bid is 8-13 (will also be 15);
6C as the third bid is 6-13.
Next BBA:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/10215b4e-bd2d-4bc6-a67a-cde97e3cbab2)

**Comment by ThePokerDude** [comment]
in the latest version the bidding got worse than originally.
With 29HCP we let the opponents play 4d undoubled,

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/5560a640-82e1-481c-9e8a-6122bf3d52df)

**Comment by EdwardPiwowar** [comment]
Because of N double. Previously X was negative and now penalty. And this arrangement doesn't work.

**Comment by ThorvaldAagaard** [comment]
Whatever Norths double is or has beed changed to, then Pass in South wrong

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3abfbe92-fabb-4075-b997-1dfcf1218d2e)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/085e8234-50cc-466c-b75a-de6ab0d8d735)
