### ISSUE TITLE
1nt p 2nt bug - description correct (8-9) but it is bid with 11HCP

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#284]
East should bid 3nt
08B6CDB45E8A2FE0FC63DD8B1BA7
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/2ca9cc5a-b1d3-4396-bce3-26beed7f8272)

**Comment by EdwardPiwowar** [comment]
Next BBA (CLS players)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/1c0e1371-5f9a-434f-bc15-268758cf0a0e)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/d0e33724-6be1-455d-b2d2-ba0317475a1e)

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/cfb24fd5-e1c5-4d4d-a3da-6fe9b1eb0466)
