### ISSUE TITLE
Why is there an answer to opening with 4HCP

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#285]
The description says 6-29 HCP. I understand that a deviation of 1HCP is ok. But 2?
0AE9916D5F7DB8CA0CEF25D80051
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/bc645bad-a436-45ee-ab15-32dbec02631d)

**Comment by ThorvaldAagaard** [comment]
I think it would be a good idea to start using 6+ HCP as unlimited, as here (And as a general rule as long as partner is unlimited we are in a forcing situation)

**Comment by EdwardPiwowar** [comment]
Following the rule of not making deviations greater than 1 HCP does not change the effectiveness of BBA bidding.

**Comment by ThePokerDude** [comment]
Could you explain how BBA makes it's decisions?

I thought it's like:
if HCP > 5 and
count(spade) <4 and
count(heart) <4 and
count(diamond) >3 and 
count(clubs) <6
then 1d

This obviously is not the case because 1st condition is not met.

**Comment by EdwardPiwowar** [comment]
Add 1 'HCP' if you and your partner have less than 6 cards or have 6+ M.

**Comment by ThePokerDude** [comment]
The 2nd condition: 6+ M is not fulfilled.
I don't get the first condition "Add 1 'HCP' if you and your partner have less than 6 cards".
So for the specific hand:
s xxx
h xxx
d QJTxx
c Jx

for what do I add HCP?

**Comment by EdwardPiwowar** [comment]
You add 1 to your hand to meet the condition that allows you to bid (if you have 1 club then +2 and if void then +3).
If you have 6+ major, you also add 1, if you haven't added it before. I don't know if there is a particularly good method.

**Comment by ThorvaldAagaard** [comment]
I agree with Andreas. North should pass, but I find it worse that South did not bid 3N.

And also after the reverse, how can North show the weakest hand, and I don't think rebidding a 5-card suit makes sense

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/413f1ec5-f69d-414e-98b3-8e6a65d55116)

**Comment by ThePokerDude** [comment]
fixed
