### ISSUE TITLE
2nd example of 1nt p 2nt bug

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#286]
This is less obvious because passing to 1nt is ok.
It's on the pessimistic side (8HCP + 5card minor is enough in my opinion)
But the bid description again does not match with the bidding.

172F29C67879CF8C900D51E272D1
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/bd8e1954-5871-4322-ae83-4fcb7cfeadfc)

**Comment by ThorvaldAagaard** [comment]
I think the bidding and description is within the accepted range. Moving AK to the long suit it would be an invite.
Using KNR the hand is 7,4, and moving the AK the KNR is 8.8

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/83516857-f1b9-4f83-b16b-f44ef628aeed)

So 0-7 HCP is OK. If any change, then it should more be that South denies a 6-card major (and 7-card minor I think)

**Comment by EdwardPiwowar** [comment]
It will be changed to 0-8 just in case. The change only affects the description.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/96927090-b738-4f85-b17c-846abb38c3c8)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/61519bb3-ac85-463b-ad8c-6d4f2a5be54a)
