### ISSUE TITLE
Dubious answer to Michaels Cuebid - general idea of preempts not implemented correctly

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#287]
East should bid 4s instead of 2s

I think there is a pattern. In competitive biddings when a 10 card major fit is known BBA tends to bid 2 in the major suit instead of 4.
This seems not always to be the case
1) if opponent bids directly after partners bid, then we jump to 4
example: 1c 1s X - now we bid 4s.
2) if opponent does not bid directly after partners bid, we just bid 2
example: 1c 1s p - now we bid 2s.

I suppose this would here also be the case
1c 2c p now we bid only 2s.

if bidding would be 
1c 2c something - we would bid 4s

The problem is - in the end in most cases we bid 4 anyway. But we give a lot of bidding space to opponents.
The general idea of preemptive bidding is not implemented correctly - 
"bid fast and high to make it tough to opponents"

137F77E304C7BC55817FC84DF8D3
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/279a1b78-15bd-4479-9174-e535458094d7)

**Comment by EdwardPiwowar** [comment]
Correct. A hand with 9 and 10 trump will be more valuable.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/52abbb08-d6bf-4f08-8d99-8c96233c0269)

**Comment by ThePokerDude** [comment]
Better but I think we should bid 4s and not 3s
![image](https://github.com/user-attachments/assets/3c887baa-5207-4137-9113-72cec74d8728)

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/1ce5df15-cbbe-4e21-a86d-1be3d5ecebf2)

**Comment by ThePokerDude** [comment]
Fixed
