### ISSUE TITLE
bids after 2nt rebid

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#289]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/19583ce5-06a9-49cc-8e7d-fce8c319231a)
09C3E6239ED7BD468E90399CA06F
something went wrong at table 2,

either 3h is forcing or it isn't,  south obviously thinks forcing and north passes.

**Comment by EdwardPiwowar** [comment]
The problem was that 3H was misinterpreted.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/11447865-c70c-426a-adfc-9ca5339d65a8)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/b0752ab3-38d9-4f6b-96e9-88b070503ef6)
