### ISSUE TITLE
both tables

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#290]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/90eb42bf-3bea-40e1-9bce-a93aed8a91d1)
0254FBB41EB8A573151DB4BCAA46

so table 1.  West inexplicably passes.

table 2,   Knowing there is an ace missing east still makes a queen ask.

**Comment by ThorvaldAagaard** [comment]
At table 2, the 4N is also wrong. After the overcall and 4D East has shown his hand, and should pass 4H.

**Comment by EdwardPiwowar** [comment]
0254BBF41BB8A573151DB4BCAA46
I think W is too weak to bid with a singleton K.
There will be no question for a queen if an ace is missing (But 6H is inevitable).
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/60c85e8e-0cc1-4e1d-b152-3d5a6429fd29)

**Comment by ThorvaldAagaard** [comment]
West has an obvious X of 2S, even with 
x
KQTxxx
KJTx
xx

**Comment by EdwardPiwowar** [comment]
Others avoid doubles with 6M.
GIB bids 3H:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/4ec23f5c-b341-4dd5-b0e7-efc8ee12cebd)
WB5 bids 3H:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/9a6a28e5-efc3-453f-83e1-fc294a41adeb)

**Comment by ThorvaldAagaard** [comment]
With the QS I think 3H is OK, and would probably bid 3H without it anyway.

If it is an opening hand bid 3H, if not X with less than an opening and a 6-card

**Comment by ThePokerDude** [comment]
looks good to me now
![image](https://github.com/user-attachments/assets/5f52b94f-99e2-4a55-8bad-63c517a17095)
![image](https://github.com/user-attachments/assets/4f41d0bd-58dd-4bd2-bb5f-1fa08b9844df)
