### ISSUE TITLE
table 2 north has to bid

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#293]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/4c59e151-4866-4ce1-9872-e30ec444b79b)
171B2D879690F90F90BC40C93517

north has to bid at table 2.

**Comment by EdwardPiwowar** [comment]
Yes, but in my current version S just bid.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/45948fae-11d0-43de-9f70-b8fbbb5d1aa1)

**Comment by ThePokerDude** [comment]
Fixed in 8627 - north bids
![image](https://github.com/user-attachments/assets/6f2ab4f7-00c0-468c-acd6-9e6e0d92a52a)
