### ISSUE TITLE
GIB and new minor forcing

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#295]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0f638102-751a-4ee6-8463-f563f99da0a0)

Is checkback the same as New Minor Forcing?

Will you update so GIB is playing NMF on the GIB bbsa-file

https://shorturl.at/rHP67

Also notice, that playing with the same CC for both sides I still get a difference for Blackwood without K and Q

**Comment by EdwardPiwowar** [comment]
Checkback,  New Minor Forcing and Two Way New Minor Forcing these are three different conventions.
GIB explain Retreat from no trump with 5C but has void.
Give me an example for "difference for Blackwood without K and Q"

**Comment by ThorvaldAagaard** [comment]
You can see the in the image that "Blackwood without K and Q" is red, I did select the same CC for both sides (GIB.bbca)

So we need the New Minor Forcing for GIB

I also found that GIB is using 1Ma-3mi as invitational
https://shorturl.at/suKPY
How do I select that?

**Comment by EdwardPiwowar** [comment]
For me it works normally.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/ade2cff4-1145-4813-b8bf-0eca9504f56c)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5417e2c0-0115-4b86-9408-7488e4eaca08)

**Comment by ThorvaldAagaard** [comment]
Also for me after restarting the application, so I assume the problem is that the conventions has not been saved with the cc
After checking and unchecking I see this in the CC
```
Wilkosz = 0
Blackwood without K and Q = 0
1D opening to 18 HCP = 0
Not defined = 0
Not defined = 0
Opponent type = 0
```
But before saving it I see
```
Wilkosz = 0
1D opening to 18 HCP = 0
Not defined = 0
Not defined = 0
Not defined = 0
Not defined = 0
Opponent type = 0
```

When starting using one of the undefined, you should probably update all the CC's

**Comment by EdwardPiwowar** [comment]
The change is effective but is not automatically saved.

**Comment by ThorvaldAagaard** [comment]
And another one to test the NMF 
https://shorturl.at/iuxG4
I think that 2C is the bid here

**Comment by ThorvaldAagaard** [comment]
As we have solved NMF I will close this and create a new issue about the 1Ma-3Mi
