### ISSUE TITLE
everyone likes clubs.

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#296]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/88378853-2ee2-4d77-aafd-6f93d5a69f60)
2041FEB7A7267E531B8A0C317567

I suspect table one had a misunderstanding

**Comment by EdwardPiwowar** [comment]
Current BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/317c6b6f-f6ce-4866-9ef7-cfcef62f9e9c)

**Comment by ThePokerDude** [comment]
looks good to me now
![image](https://github.com/user-attachments/assets/5fecdadb-a8e5-409c-9ada-75aa9ab74a06)
