### ISSUE TITLE
Removing EPBot from the bidding

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#298]
I have a set of hands, where I would like to have WBridge5 to bid all 4 hands

I connect 4 Wbridge5 thru TM, and select output only for room 1,

Then BBA bids both rooms, with this setup
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/79019529-d894-4fb8-bd22-0aa0f98a57c5)

It would be nice if we could have BBA to manage 4 bots at the same table, and the record the bidding.

**Comment by EdwardPiwowar** [comment]
I've already thought about it. I'm going to enable this on all tables. I'm currently adding and testing NMF.

**Comment by ThePokerDude** [comment]
I think it's implemented in the current version
