### ISSUE TITLE
Defence vs weak 2D

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#3]
046189F1666753F40D0712143E54
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/5f457164-d028-44e3-9fbd-476d298c5877)

West forgot to double 2D

**Comment by EdwardPiwowar** [comment]
15
West doesn't counter because of the second queen of spades and four diamonds.
I made small modifications for the next build, but this is a general problem with doubles, which will be analyzed later.
16
9 HCP - 2 HCP for diamonds queen.
Currently unresolved.
17
WBridge5 also passes in this situation.

**Comment by ThorvaldAagaard** [comment]
15: T/O doubles with 18+ should not have any requirements of suit length and stoppers
16: The 4th trump is the key - after a normal 1S overcall we would give a mixed raise, so principle is a mixed raise after a simple overcall should bid on the 3-level after a overcall on the 2-level
17: In the diagram, you can see WBridge5 bid 3C

**Comment by ThorvaldAagaard** [comment]
15 is solved, but 16-17 currently unresolved

**Comment by EdwardPiwowar** [comment]
15
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2301d2a7-a796-479a-aac5-27d7f1f88dc2)

16 but Im not sure
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/d276b13f-db05-434b-bb5c-30348d52785a)

17 BBA bids 3C as 11+ HCP
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/34008168-e425-40ac-8ce8-0d8a1ed24bf4)

**Comment by ThorvaldAagaard** [comment]
I would probably overcall 2N on 16. 16HCP, double stopper, very bad suit

**Comment by ThorvaldAagaard** [comment]
Why are the bidding different here?
0FED1CE6818233508BBBB6E01B01
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/094616b0-e394-44d3-a97e-a1df7ee5019f)

and West is still not bidding 3C (Version 7933)
113E6CAA59FA6657689A13AAB501
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/5efbb20b-0006-4474-baf5-d6e5d85e1f51)

**Comment by EdwardPiwowar** [comment]
Next BBA. No game - write if you have any idea.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/8d7181b1-e316-4c3a-9bf2-f8f2aa4292fc)

**Comment by ThorvaldAagaard** [comment]
With diamonds double stopped I prefer 3N over 3H on a bad suit, but I will test it on BW (I might even have bid 2N over 2D)

https://bridgewinners.com/article/view/bidding-problem-2-us6zymu2w9/

**Comment by EdwardPiwowar** [comment]
Now
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2b2fcd22-82a3-4229-93f9-a189dd935a31)
