### ISSUE TITLE
Error in navigation

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#30]
When I scroll  thru a set, I sometimes get an error like this

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8b0e76d2-1a46-4f49-8721-730ef78311e2)

Then I have to reload the file, jump to the board and all works fine again for some time. I haven't found the pattern for the error.

I could be because I am using WBridge5 for bidding

I could be after having tried to select a specific board

**Comment by EdwardPiwowar** [comment]
Could you give me this set?

**Comment by ThorvaldAagaard** [comment]
The set works fine for all boards, just navigation sometime fail. Mostly because I can't hit the arrows
[match14 - Kopi.txt](https://github.com/EdwardPiwowar/BBA/files/13403965/match14.-.Kopi.txt)

**Comment by EdwardPiwowar** [comment]
Can you check now?

**Comment by ThorvaldAagaard** [comment]
Seems to be working fine.
I will close this as solve and create a new issue of I see it again
