### ISSUE TITLE
another penalty dbl when it should be take out.

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#305]
41594FD3D773F9E5333202D81F10
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/b58e41f6-f939-4206-846d-cf43e4f4538f)

South table one is stuck. 4nt is rkcb.  the second double is penalties but should be take out.  this is admittedly less clear than some of the others.

**Comment by ThorvaldAagaard** [comment]
4Mi should be NF after the negative double.

**Comment by EdwardPiwowar** [comment]
Currently, the bidding is slightly different:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/18ec055e-64a0-49c1-8553-a6bc996aeeaf)

**Comment by ThePokerDude** [comment]
looks better now
![image](https://github.com/user-attachments/assets/433730c2-1126-4b5e-a275-381198d0b098)
![image](https://github.com/user-attachments/assets/b1d0efd6-00e7-4f90-ac6b-d9503f86acb4)
