### ISSUE TITLE
Blunder misjudgment 

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#309]
Partner passes to 2d
Partner passes to 3d
Partner sign offs with 4d 
Partner has shown 12HCP and no extra points.
There is no reason to bid 5d

12FC110FE5BED96CC6598CCC729D
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/a5f9fe4e-8a3b-4a4a-9fa9-3caa53671c30)

**Comment by ThorvaldAagaard** [comment]
Agree, and I would say that even the X of 3S is stretching - It is penalty, so check If you have select Imp or MP (Right-click on a player)

**Comment by EdwardPiwowar** [comment]
Next BBA.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b85f8be0-e2ad-4841-8b08-c6236e2e66c4)

**Comment by ThePokerDude** [comment]
Looks ok now. East is raising spades. I think South should bid 3d instead of 4d. Other than this - ok.
![image](https://github.com/user-attachments/assets/1ff15103-5fe3-4080-86a4-828f092c09a4)
![image](https://github.com/user-attachments/assets/5c1ada71-be78-4c07-a781-8d7071bc3ad0)
