### ISSUE TITLE
Jordan / Truscott 2NT (Two No-Trump)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#31]
https://www.bridgebum.com/jordan_2nt.php
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/38447f34-c1f4-4963-904e-31e42cb44f69)

6B90C7CA5F6C71AFC7D916EA792F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/80058c06-e233-4d7d-b156-417d158442e0)

East should not XX, but should use Truscott 2N

**Comment by EdwardPiwowar** [comment]
In the next BBA compilation
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/1cce0840-8abe-4f32-b188-4c6e951f30b5)

**Comment by ThorvaldAagaard** [comment]
I just tested this, and it works fine if Jordan Truscott 2N is selected.

BUT it also bids 2N, when Jordan Truscott 2N is OFF
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9f8bb176-103b-4155-9bf8-b5f9ce3bd133)
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/ee25211c-728c-4f98-9a0a-b7aed138f9bc)

**Comment by EdwardPiwowar** [comment]
Here is Jacoby 2NT because there is no double.

**Comment by ThorvaldAagaard** [comment]
Ah, I missed there was no T/O-double this time. Closing.
