### ISSUE TITLE
4c after partners multi

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#313]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/4ddc787f-86aa-4698-bcde-c744fdc63546)
0D7B0899255C37D0AE46DAADD95F

4c is normally please transfer to your major.

4d is bid your major.

**Comment by EdwardPiwowar** [comment]
Next BBA
0DBAC856275C37D0AD439FF959D9
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a297b356-d2c6-48c5-a832-d99a53784eee)

**Comment by ThorvaldAagaard** [comment]
What is the artificial 2S for SAYC?

This is how GIB plays it, and I assume it should be the same for SAYC
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b6892d4f-21e3-4da0-adbb-68dae36bcccc)

Responses to 2N is 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/23802ad0-94e1-478e-a0ca-6e7582f9b9b3)

**Comment by EdwardPiwowar** [comment]
Today will be BBA with rebuilded 2M.

**Comment by ThePokerDude** [comment]
looks good now
![image](https://github.com/user-attachments/assets/5c6c2bfb-861d-4447-b4b3-8ea54aa66615)
![image](https://github.com/user-attachments/assets/4d3e4b05-27dc-44c1-a428-b5dd15b42a5e)
