### ISSUE TITLE
A board with multiple errors

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#314]
08C5E961DC77D918011710AF16D2
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/aa7afe92-73b3-4faf-9611-487767872641)

East should either give preference to 2S or bid 2H, Pass is wrong

After the preference BEN will bid 3C in south, and now North cuebids in Spade to show good club-support
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1a1670fa-999e-41ba-a05b-b22c75649051)

But South now pass
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/5acf4374-495c-4a8f-87ee-277d91995ccc)

In BBA 3S is defined to strong, but I assume that we have missed this in training as South pass.

But Pass is defined like this
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/476feebe-8e2c-442b-8376-8c9a4540b96d)

**Comment by EdwardPiwowar** [comment]
It got a bit messy. I'll start from the end to save all the mistakes.
Currently, after the overly optimistic 3S, S will bid for 5C:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/297c4496-41da-44bf-ab4b-adfeddf6078e)
But S folds after 2S, should bid 3C? or double?
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b819200f-f6b1-42ed-b8be-056915e27517)
In the next BBA, however, E will bid 2H, and now from S 3C? or double?
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/72ab7498-feec-4c17-be58-49cc0781dfea)

**Comment by ThorvaldAagaard** [comment]
I think it is close, and Pass could be right, as it sounds like a misfit.

But North should probably act after partners T/O double of 1S.

So 
1C-1S - P - P
X - 2D -P -2H
P - P - 3C all pass looks right to me

**Comment by ThePokerDude** [comment]
Looks good to me now
![image](https://github.com/user-attachments/assets/ac952bdc-57fd-455c-a8c4-f28d1e2326d0)
