### ISSUE TITLE
WJ jump shift is a one round force according to bba but it passed

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#322]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/a6be2bda-b25b-4aa5-9828-3ac2f3ad2e5f)
0BAAA12BC2939D167ADBC8A4C497

now maybe I shd bid 2d,  but anyway i bid 2s.  even if this is not forcing north shd certainly bid.

**Comment by EdwardPiwowar** [comment]
N passes, because he sees the result 2S 140 vs 2NT 120. S is forced by 1D but 2S from S is not forcing. For now, I have no idea how to improve it.

**Comment by Muppet1** [comment]
2NT is definitely a forcing relay in wj2005.

jack does indeed bid 2NT and agrees that 2!s is not forcing,  jack has pass at 0-2.

**Comment by EdwardPiwowar** [comment]
Close the thread if that's enough.

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b5bbf03d-d480-42b9-b980-f0851e72aeae)

**Comment by ThePokerDude** [comment]
looks better now

![image](https://github.com/user-attachments/assets/213958aa-1f8f-4737-a13e-83a33cd01003)
https://jassem.pl/wp-content/uploads/2016/08/Polish_Club-2010.html#
![image](https://github.com/user-attachments/assets/2bccb2ee-e69e-4042-9bb5-a07b0d97df5f)
