### ISSUE TITLE
limited hand decides to use rkcb

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#323]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/a4c249ff-497f-4ea8-9e8d-90f16e235ae4)
0C3A4E8EC742E1C03178D5A46DDB

North limits its hand with 3nt.  I sign off.  it bids rkcb.   I actually have a limit raise which i want to bid through 2nt but that shd not matter.

**Comment by EdwardPiwowar** [comment]
The question occurs because of the expectation of a higher result. I'll limit it a bit for the bonus games and test it out.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a3df7d19-4a11-4bca-96ef-94fe639edac7)

**Comment by ThePokerDude** [comment]
looks good now
![image](https://github.com/user-attachments/assets/4bbdf288-6bc2-4efc-94f0-e6e4347f7378)
