### ISSUE TITLE
multi landy

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#325]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/af91a5c8-fba8-4ebb-8e5d-0034eece2984)
112DACBC912FE4596DCA3631F27B

north goes mad over 2d and doesn't bid 2 hearts.

**Comment by EdwardPiwowar** [comment]
Current BBA bids 2S
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/4b3e6f05-7390-4b25-9ade-8f746252e063)

**Comment by ThorvaldAagaard** [comment]
Yes, and that is obviously wrong

**Comment by EdwardPiwowar** [comment]
Next BBA
112DACBC912FE4596DCA3631F66B
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3e57e1ac-579a-4a28-b978-09934e07cc81)

**Comment by ThePokerDude** [comment]
looks good now
![image](https://github.com/user-attachments/assets/224502f6-b931-4437-9f87-5a7489cfde0e)
