### ISSUE TITLE
bergen and bidding on.

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#328]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/25fcb0a0-216d-48b3-b243-a71a31354d9c)
04A6EBCFF6427E61AD8DCBA4FB5F

The idea of bergen is that it is a limit bid.  You don't do anything afterwards pard either bids 3M or 4M and that is it.

This hand wants to always bid game and has a perfect splinter so that should take preference.

**Comment by EdwardPiwowar** [comment]
Maybe redouble
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/0a874711-2c44-4a72-858c-45ce68823c22)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/01ac31c1-bab6-40de-939d-b17b6e8174fc)
![image](https://github.com/user-attachments/assets/26335458-263d-41f4-9f93-ff82956ba92b)
