### ISSUE TITLE
Update of EPBOT-dll

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#33]
I would like to test how well BBA is bidding against WBridge5 in a match, but the DLL is not updated in the last 2 months.

**Comment by EdwardPiwowar** [comment]
[compilation 7395](https://drive.google.com/file/d/1pVJZMN4sFMRzI-rTaKV0otcvbt35jluh/view?usp=sharing)
DLLs version 15.

**Comment by ThorvaldAagaard** [comment]
Thank you
