### ISSUE TITLE
This should be non forcing

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#332]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/6b4c4d11-343a-4e0b-927c-eea150bcec5a)
21A6118B19E756ECB0E9ED5A5826

table 2 auction shows good hearts and 10-12, you have to bid 4th suit ,

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f37ce3fd-5c7b-4665-bdb0-57999c3cef33)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/d33e148b-352b-46aa-8808-3f7c8467b173)
