### ISSUE TITLE
Drury and being able to bid 2  or 3 hands

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#337]
0223DB89A8521E41D396993E8A0D
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9046f1d4-e4cf-4d1e-a91b-3a0c36a12ee0)

This is with GIB as partner

This is the description of Drury
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/55a729eb-7e83-4dcd-9a5f-47a775d7b0d9)

With a hand, that just want to play game, just bid the game, and do not reveal any information to the opponents

This is from Bridge Bum
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/15022079-9b12-4507-89c7-b3c4b4d6c4f8)

As 2C is normally 10-11 or compensating values, a

Bidding this with BBA is difficult as East will open 2H (but not GIB), and if I bid the East hand West will bid 2N to show minors, so it is difficult to see if BBA would bid something else than 2S or it is BEN that is downgrading.

In my book South has a 4S bid over 2C.

Please also read https://kwbridge.com/drury.htm as that is more how i think it should be played

GIB is playing like this, as it prefers splinters
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8028a5a5-b132-4e6e-b4de-6bae121cc6a5)
so that is like Karen's description

**Comment by EdwardPiwowar** [comment]
No standard: 
"Several Drury rebid variations are used by some partnership, including game and slam try methods, splinter methods, etc.  Partnerships should also consider Drury methods when opening in fourth seat, as well as overcalls by Left Hand Opponent."
I change 2H to 4+ and 13-14 HCP. Splinters are at level 4. Generaly bidding after drury should be natural.
0223DB89A8521E4153B6B93E880D
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/e7ea565d-90eb-4550-a22c-a9044077d67f)

![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2ead4038-a523-49eb-81e2-f80942185819)

**Comment by ThorvaldAagaard** [comment]
When no standard we should follow the other robots, just to make them compatible.

**Comment by EdwardPiwowar** [comment]
Other robots also have different arrangements, it is necessary to introduce the option to CC.

**Comment by ThorvaldAagaard** [comment]
Yes, but until you have the option in the CC, you should follow a robot, and GIB seems to be the expert for 2/1 (and Drury)

**Comment by ThorvaldAagaard** [comment]
I will close this and hope #506 will get fixed.
