### ISSUE TITLE
New Minor Forcing

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#340]
0B25322C5EA5F88E5E2A4AF7C7DC
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/76d1b21f-9e88-47a5-a69c-fa0d76be8b73)

3N is not a possible bid
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/08e094ef-6c4d-47ce-bae3-3434f6892abd)

Actually 2H is the right bid, and you should add the continuations after 1D-1M-1N-2C

I noted that 3N was a calculated bid. Generally you should never use a calculated bid, when responding to a conventional bid.

**Comment by ThePokerDude** [comment]
fixed in 8627
![image](https://github.com/user-attachments/assets/5374fe9b-58c3-4d94-bef8-b4cf18a5bc42)
![image](https://github.com/user-attachments/assets/59b8a869-95df-41c6-af13-2a25e7331a49)
