### ISSUE TITLE
passes  even though it correctly knows it is a void

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#347]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/f9c16668-d35d-4dfa-9aa2-3419d2965380)
44A08A6EE9CDDF6CA39321DD7F8A

6d void it says .  pass.

**Comment by EdwardPiwowar** [comment]
It's just like with humans:
"Don't you understand? - pass"

**Comment by ThorvaldAagaard** [comment]
I assume 3S is setting Hearts as trump (Splinter), so even a human would no pass here :-)
And according to the description it is funny to make an exclusion in a suit, and then the rebid shows a rebiddable suit

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/e47a424b-a060-49c5-bdc1-ac24f90546bf)

**Comment by Muppet1** [comment]
The point is it should bid 7.  I didn't just bid 6 hearts.
    On Saturday, 6 April 2024 at 13:21:19 BST, EdwardPiwowar ***@***.***> wrote:  
 
 


Next BBA
image.png (view on web)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/a48581ff-6cd8-4fb9-812b-bcefe657e119)
![image](https://github.com/user-attachments/assets/79634775-4589-4472-925d-b9d735ca2c2c)
