### ISSUE TITLE
Bug in response to 1d - 1nt response should exclude 4card M

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#348]
The correct response is 1s instead of 1nt.
Bidding does not fit the desciption on the right side.
19FE9FC9C5087A31252D6E43EE46
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/1e340abb-b7bd-4363-bc99-3eac676042c7)

**Comment by EdwardPiwowar** [comment]
This is one of the recently introduced bugs.
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/479185cf-a70d-4f7d-9f5b-a0c2d49912e7)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/22be9a34-28fc-4d8e-88fc-ed1dc00e5d39)
