### ISSUE TITLE
bidding ok, but explanation wrong - probably not critical

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#349]
1c p 1s p 1nt 

it should be 
s -3
h 2-4 and not 2-5 with 5 hearts you would open 1c only with a club heart two suiter
d 2-3 and not 2-6 with 4+ diamonds you would open 1c only with a club diamond two suiter
c 3-5

1c p 1s p 
1nt p 2h p
2s 

The description says 2-3h but we have 4.
Probably pass is better than 2s but 2s is ok.
262791BCF25EA160531AFBE0C7FA

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/6956d7e0-e7e1-42ba-ad36-677ab463b1d3)

**Comment by ThorvaldAagaard** [comment]
We have discussed this before. 4-4 is probably better than 5-3, but when the 5-card is on the weak hand 5-3 could be better. So as long as we find our 8-card I am fine.

**Comment by ThePokerDude** [comment]
yes 2s is ok for me.
But 2s is explained as max 3h which does not fit the actual hand.

**Comment by EdwardPiwowar** [comment]
Next BBA
Description corrected, escaping from the 4 of hearts is unnecessary.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/588ad7d0-d417-42dc-b888-7e1b77b4b3e3)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/80818aee-adf0-4487-bdc0-ded5bd667d5d)
