### ISSUE TITLE
crazy pass of dbl

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#352]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/01fd8734-3efa-4d58-a062-cceae09c5fa6)
0FD6E947413F9E3F6A0F420DCDC9

fairly insane raise at table 2 aswell.

**Comment by ThePokerDude** [comment]
Yes, the pass is wrong. The description indicates the west should pass always with 11-15 (as the possible distributions did not change compared to the opening).
With following rule we could eliminate some of the wrong passes:
if the last two bids are x (negative) pass
and we have a guaranteed fit in one of the other suits we are not allowed to pass.
We either bid the suit where we have the fit or we cuebid in oppenents suit or we bid RKCB.

**Comment by EdwardPiwowar** [comment]
Currently this error does not occur and I cannot check it. I'll check if it happens again.
0FD6C967413F9E3F6A0F420DCDC9
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a2d500ef-5016-41f3-a4a6-150b7a53b307)

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/18a1d054-4e32-4bbe-b2b4-0988f1691e73)
