### ISSUE TITLE
south fails to open 1NT

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#353]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/184e6566-e52e-4e92-a928-cf997db0df67)
032598EAA5F94FD061AE311A433B

south at table 2 fails to open 1NT and then has no rebid.

**Comment by ThePokerDude** [comment]
It depends on the setting of 1NT.I checked for BEN-UCBC and the description says:
15-17 HCP 15+pts 2-5s 2-5h 2-5d 2-5c - NT style
So following the description 1NT should have been opened
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/23cc3c4b-6301-4457-b99f-92507199168d)

**Comment by EdwardPiwowar** [comment]
BBA requires side stops if it is 5M, but there are different arrangements.

**Comment by Muppet1** [comment]
Ok can we remove any side stoppers being needed ?

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/a7efb655-08ef-4338-8430-026b80d8bf29)
