### ISSUE TITLE
Multiple errors: 1 defintion of weak 2 in major, 2 defence vs multi, 3 super accept of transfer

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#356]
1) With 6-5-2-0 10HCP I think we are too strong for week 2.
I have seen a lot of very weak 1 level openings with clearly worse hands.
For me this is a 1h opening

2) Does 2NT show 16-18 HCP and promise stoppers in both majors?
For me ok. Then we cannot bid 2NT
Depending on what direct double means we should
double - if it is a general take out OR
pass and double in the 2nd round - if 1st round double is a take out of spades
The 2nd double is definetely wrong.

3) This refers to table 1 - In this situation there should be no super accept as it puts us on 4 level even though partner could be weak.
It's different to the situation where we open 2NT. Here we are 3-4 points weaker.
So the danger to get too high by super accepting is much higher than the danger to miss out of a game.
Super accept is always a trade off. In this situation it definetely does not pay off.

4B68702925FF5127C2EBE95E0375

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/810f728d-88b7-4511-888b-9b6a8238b8c5)

**Comment by ThorvaldAagaard** [comment]
1: Opening 3H  (5 loser hand) seems better than 1H. We do not want to open to light at the 1-level, when training
2: Overcall 2N seems to be the right bid, also after Multi.
3: Agree, no super accept after a 2N overcall - should probably also be dropped after a 1N overcall.

**Comment by EdwardPiwowar** [comment]
ad 1 You can 1H, 3H or pass (GIB). 2H sells 6H and blocks it at the same time, which also has its advantages. Tests showed that 2H was not bad.
ad 2 It is not clear whether double or 2NT.
ad 3 Next BBA without SUPER ACCEPTANCE when 2NT weaker 19 HCP.

**Comment by ThePokerDude** [comment]
current version still passes to 2d and 2h alter on

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/2f2482c3-0533-497c-8991-965a75a91124)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/d3b0572a-7f90-4ff3-9b9f-2ba4a40c0ee0)

**Comment by ThePokerDude** [comment]
fixed in 8627
![image](https://github.com/user-attachments/assets/10f9dec8-caae-4a37-b5d5-cfe172c7809e)
