### ISSUE TITLE
Wrong reaction to a sign off after 2nt jacoby

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#361]
On table 2 west should pass to 4h.
West has only 13HCP and 3c has shown a club shortness without saying anything about strength.
Partner signs off.
So we have minimum strength and no extras in distribution.
We should accept the sign off and pass. 4nt is a clear mistake.

The only reason why 6h makes is because partner's sign off is pessimistic.
Partner could have a hand where even 5h is hopeless.

48FD573392CBA612100A42B575F3
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/958c0ca8-3a6b-49cd-8851-45df3b7bbaae)

**Comment by EdwardPiwowar** [comment]
Andreas, it's nice to analyze the problems you describe because I don't have to guess anything. In this case, however, I have a problem because I have to spoil a good result. I have no idea yet.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/60900dbd-3239-45ea-9bbd-47d6d8f712da)

**Comment by ThePokerDude** [comment]
The auction as shown now is much better.
When east does not sign off you can definetely continue with a hand with a cuebid in each suit.

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/400a40d1-eed8-4d87-a033-83f8f06ed954)
