### ISSUE TITLE
we still don't seem to understand lebensohl

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#368]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/5b9029c6-9cb9-42e4-8665-c8d2baeb7f56)
01F2322A6E2C529E53AA0802354F

East bids 3 diamonds showing values not 2NT showing rubbish.

Interestingly Jec did not use lebensohl at all in his matches.

**Comment by EdwardPiwowar** [comment]
In BBA should be a direct double of the partner so in this situation lebensohl is off.

**Comment by ThePokerDude** [comment]
looks good now
![image](https://github.com/user-attachments/assets/298eef38-9c30-49a9-a831-f418a613dde9)
