### ISSUE TITLE
13 HCP 6card suit and a 6-4 hand is definetely enough to bid on 2 level after opponent's opening

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#370]
West has to bid 2d. Passing is bad.
East is also too passive so opponent is allowed to play 1s with combined 13HCP

19AEDA9CDEF9C42F578E4B83A36F
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/9c4b4273-3105-4e1a-af8a-56f9068e38fe)

**Comment by EdwardPiwowar** [comment]
This hand is not easy for GIB and WBridge5 either.
What's next?
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/bcf0ad13-fce0-448b-9003-ac35ba6d38cc)

**Comment by ThorvaldAagaard** [comment]
I think it would be OK for South to pass 2D, as partner did not have a negative double, and we can see he can't have a penalty double.

So 2D would here be the final contract.

But what about the Pass in East with a very good opening hand, it looks wrong. 2S is a limit+ raise asking for more information, so I would probably bid 2S, but the overcaller might just bid 3D to show the minimum overcall.

So bidding 3N is difficult

**Comment by EdwardPiwowar** [comment]
Now BBA calculates at least 8 nt tricks
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5a0836b3-b2d8-4700-b660-0e326e196c69)

**Comment by ThorvaldAagaard** [comment]
I will post on Bridgewinners what East should bid as step 1
https://bridgewinners.com/article/view/bidding-problem-2-45esc2i2op/

**Comment by ThorvaldAagaard** [comment]
After an overcall 2/3 minor I think it is common, that Cue bid the openers suit is primarily looking for 3N, But after major it is showing support.

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2675a121-6da2-47c0-b593-01e9c90e1189)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/e4eaadd1-6ec6-4749-a55b-fe0a426d32a7)
