### ISSUE TITLE
penalty doubles without any trumps continue

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#371]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/c0e2339f-0677-4115-913a-53da4517ead0)
217D64AACD4E05D38EB3EA48DFAA

east makes a penalty double with 2 small trumps for some reason.

**Comment by EdwardPiwowar** [comment]
Currently no double
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/230a7099-130f-4e83-9758-5d36254652d6)

**Comment by ThePokerDude** [comment]
This one is difficult. For sure we cannot let EW play 3h undoubled.
If we trust the opponents to have 9hearts probably east should bid 3s.
![image](https://github.com/user-attachments/assets/b3832af3-77e8-4709-bc37-c6efa900cbe7)
![image](https://github.com/user-attachments/assets/8d9621f1-3d96-4da2-bf14-8439f03ebbd6)
