### ISSUE TITLE
2-2  fit

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#382]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/285670b7-3cb0-4dc4-a650-44a7f61d220c)
05CC3578D448C9415EAA6240308F

2-2 fit can't be good.

**Comment by ThePokerDude** [comment]
General rule should be - if a bid is marked as artificial, pass is not allowed

**Comment by ThorvaldAagaard** [comment]
Also a good rule to implement
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0a28585c-0077-4e1f-9d02-7d7f462ea222)

**Comment by ThePokerDude** [comment]
Not fixed in 8092

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/b06ca290-1de1-4357-a89f-f8157fbb3e5c)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/6d21a2f8-81d7-450e-991c-8a114f7a48d7)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/5a89a108-6d31-46c4-be2e-24d4b9c91513)
