### ISSUE TITLE
4th suit not gf problem

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#388]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/d86a28d9-be0d-4632-b502-cf5909620737)
263AB80DC759E81A55C9C01A4475

table 2 4th suit not gf disaster.

**Comment by ThePokerDude** [comment]
looks good now
![image](https://github.com/user-attachments/assets/0838218d-be05-4b8b-a21b-3c5a16b79137)
![image](https://github.com/user-attachments/assets/8c4ef192-f637-4656-8f5e-4cad652a65f5)
