### ISSUE TITLE
pre-empts are still hard

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#389]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/fa87a48c-e8b3-4e15-b350-c55047b41ede)
01FC60C9ADEDED6B48192476F6A3

someone has to bid I guess east.

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/9fc3eab5-4645-4f6d-841c-f64e284fdf3b)

**Comment by ThePokerDude** [comment]
looks good now
![image](https://github.com/user-attachments/assets/3d6ee6d7-e81b-4e83-9cc8-93e3c201a7e6)
