### ISSUE TITLE
2nt nat over their transfer is insane

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#391]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/01b5a8dd-6753-4392-bee0-872de0b2ea62)
186D9A6906F07B80B18EC8D27FC8

second one of these 2nt bids.  this one was going for 1100 which is pretty common.  Thorvald agreed 2nt was bad.

**Comment by EdwardPiwowar** [comment]
2NT will be removed.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/19a3ae34-ae64-4eee-96f6-b5f380886926)

**Comment by ThePokerDude** [comment]
looks good to me
![image](https://github.com/user-attachments/assets/0de333a4-6c83-4dbd-8aed-7cf8d39c33b7)
