### ISSUE TITLE
BBA selecting wrong trump suit

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#4]
034569368E42AEA8C19AF92638A8
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/435ea31d-8dbe-456a-84ca-fdcb18e55054)

North should prefer 4H to 4S.
Terrible bidding by WBridge5

By the way, when Smolen is selected I think 3H is showing 5-5

**Comment by EdwardPiwowar** [comment]
N doesn't know about 5 hearts, so he calculated that 4S is better. 
I agree:
"When transferring to a major and bidding the other major, some partnerships require that you are 5-5 in the majors."

**Comment by ThorvaldAagaard** [comment]
It is common knowledge, that 4-4 plays better than 5-3, but with double diamond 4S is actually better :-)

**Comment by EdwardPiwowar** [comment]
I think there are too many options for 55 which may cause problems.
https://bridgewinners.com/article/view/respond-to-1nt-with-5-5-in-the-majors/

**Comment by ThorvaldAagaard** [comment]
I know the problem with 5-5 but this sequence can't be 5-4 when playing Smolen

**Comment by ThorvaldAagaard** [comment]
Dropping this for now
