### ISSUE TITLE
3C is more correct than 3N (#34)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#40]
268C8250FA479FB944405EEEFB8D
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f0b34240-6530-44d8-976e-c767db615471)

I Agree with BEN that North should bid 2H, but the rebid of South should then be 3C as 3N is showing 18(17)-19 balanced.

**Comment by EdwardPiwowar** [comment]
Ok
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/4f007c70-9763-4587-8bf9-5c27957b5f3a)

**Comment by ThorvaldAagaard** [comment]
Thx
