### ISSUE TITLE
Failed to get anywhere near this game

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#402]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/a4947b33-a8d8-4ca2-b75c-9d3dff918f9f)
1BBE17281E5E9F95DC84B0D80FF3

See table 1 for how south should bid.

see table 2 for how south misses game twice.

**Comment by ThorvaldAagaard** [comment]
Well I would open 1D in South
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2668e96d-d924-4d39-8ec4-1052f754cb38)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f0c10aba-11bc-4fb0-a1f2-5c1bc632c589)

Now you can discuss if 3 or 4S is right (As we have 4H to show a good raise to 4S), but as long as we can fix the opening bid I am OK with the rest.

Interesting that 4S shows exactly 16 HCP and 20+ points

**Comment by EdwardPiwowar** [comment]
4S shows exactly 16 HCP because you have available 4H, what you don't like.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/b1622d44-3735-4c24-921f-255712efc294)

**Comment by ThorvaldAagaard** [comment]
Opening 1D should be obvious
After 1S and the preempt 3H I agree that 4H is showing a hand to good for 4S, but doing that on 17 HCP seems wrong.
So 4H could be the hand that would bid 4S undisturbed - but that bid is also described very wide
1D-1S
2S = 11-16 HCP
3S = 13-18 HCP
4S = 15-29 HCP

I know it is difficult with ranges on distributional hands, but it should be
12-14, 15-17, 18-19 allowing for up- and downgrades.

After the preempt south should pass on minimum hands even with 4-card support, so 3S is like 13-14(15) and 4S is like (15)16-17

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/6b969809-1299-4888-a141-4c467fa08804)

**Comment by ThePokerDude** [comment]
looks good now
![image](https://github.com/user-attachments/assets/fbe1a72d-0e8b-40f4-b1ab-930810cdeff3)
