### ISSUE TITLE
This is a splinter

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#411]
0C1AA6066B9A47DAB8EABC1DF75D
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/bce5a7c6-64f0-4a34-8d13-0c0af0d04d7b)
When 2S is forcing (2C is GF), then 3S is a splinter agreeing diamonds

GIB definition
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/cc96c1c8-e0e0-4865-9cb6-19dbfa74c139)

**Comment by EdwardPiwowar** [comment]
Next BBA:
```
W	N	E	S
P	1D	P	2C
P	2D	P	3S*1

*1 Splinter
```
The same for 3H.

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/8938a991-095f-4e87-8bf8-bd2e30cf21d0)
