### ISSUE TITLE
We do not play signoff over 3N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#415]
Version 8071 (and in version 8069 East passed)
40E2EF3F009825393C54EE5C280B
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/48bebd84-6d43-4499-89b7-45ae057c3adf)

Note that West is answering majors

This is an error in both SAYC and 2/1 - and probably any system

As 3N after a 3X-preempt is wide range, it could be an idea to play 4C as range check, and transfers (or just the normal 3N system, that is missing in BBA)

Just as inspiration, this is how GIB has it defined
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/5491ccb8-47f1-4cb7-a4bd-8c552c97126d)

**Comment by EdwardPiwowar** [comment]
4C was a bug. BBA treats 3NT as NT style so some bids are different.
Next BBA.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f0239337-7661-430f-a66d-979541dbfe24)

**Comment by ThorvaldAagaard** [comment]
Working in 8105
