### ISSUE TITLE
Tims-c bridgewhiners hand

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#418]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/f419d3f7-d0de-486b-a09a-e1f132cd3bc2)
002BC16D35D86DE9DA55CB9E1CB5

So this is M. Rosenberg's bid for south the 4!c bid.  He obviously thinks it is forcing.  EPbot doesn't

If you bid it how some of the other posters are where south bids 3!h then 4!c epbot realises this is forcing and happily gets to 7c.

On its own epbot as south meekly passes 3NT.

**Comment by ThorvaldAagaard** [comment]
I think it has been mentioned before: Unless we have made a probe for 3N, that failed, then 4Mi is forcing.

**Comment by ThorvaldAagaard** [comment]
4N could be OK, but after 5S, South must bid 5N to promise all keycards - a good example of why 5N not should as for number of kings.

**Comment by Muppet1** [comment]
It did consider 5NT

**Comment by EdwardPiwowar** [comment]
I'm testing it right now
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/8463a7fe-d233-47f4-84f2-30e1f1bc3a92)

**Comment by ThePokerDude** [comment]
8091 bids 6c

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/328f01b2-abfe-4840-bd2e-2809e2ca9dca)

**Comment by EdwardPiwowar** [comment]
8092
[BiddingAnalyser.exe.zip](https://github.com/EdwardPiwowar/BBA/files/15142660/BiddingAnalyser.exe.zip)

**Comment by ThePokerDude** [comment]
thx, Windows defender was not complaining this time :)
The bidding with 8092 is the same as with 8091

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/6d957364-af51-4f5f-b594-419061a3d369)

**Comment by EdwardPiwowar** [comment]
Ok, 7c if crosswood is on.

**Comment by ThePokerDude** [comment]
8101 bids 3nt. Somehow the fix of 8091/8092 is not there any more.

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/6a3753b0-8ca8-4356-9b25-b0fe3fd15af2)

**Comment by EdwardPiwowar** [comment]
Second room with Crosswood convention.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f30d2fe0-681f-469a-9653-14edba12135f)

**Comment by ThePokerDude** [comment]
Looks ok to me. To find 7nt is not easy.
![image](https://github.com/user-attachments/assets/1d7f5bf2-1ae6-4dcf-9776-f45693983806)
