### ISSUE TITLE
Double of a transfer after 1 NT opening

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#419]
057A7C25C5726A8E33ECA55120C3
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/5cf51218-f7e6-4d5b-ac12-8250b44150a2)

Q9xxx is not a Double of a transfer, when less than an opening hand, there should be suit quality requirements.
I think minimum is 2 of 3 top, or 3 of 5

**Comment by ThorvaldAagaard** [comment]
Using version 8069 there are some more bids you need to take care of.

First question is if super accept is off after the Double? I see no reason to drop it.
2N (and 3N) = 17 hcp and double support
3Mi (2S if transfer to hearts) = Nat, 17 hcp and double
3 in the major transferred to is still 4-card support - but max

**Comment by EdwardPiwowar** [comment]
I raised the requirements to at least 2 honors and strength depending on the situation. Here the double also shows first lead for nt, not necessarily to play. Super accept still works after X.

![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/97627c53-c088-4732-99c3-168b7985aad7)

**Comment by ThorvaldAagaard** [comment]
Double at the 2-level should normally show the suit. Lead directing from 3-level and up - as passed hand more for lead, but still the risk of playing a XX contract at the 2-level is important

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/477ddb12-22fe-40f4-9460-53a47598f6bf)
