### ISSUE TITLE
Wrong use of cue bidding their suit

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#420]
If we open and they overcall, a bid by partner at the 2-level is normally 10+ and a 5-card. With 3-card support and minimum we just raise one, and with some extra we bid game.

We do only cuebid in the opponent suit with stronger hands, that might have slam interest.

5C7CA86970A93E45C42601FF61E7
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2a2f76dc-d39b-47b7-9499-8a94e64d0478)

2S is wrongly defined, and 3H is here defined almost the same but lower range and can be double

4H seems right, but should be limited to about 17 hcp as with 18+ a cue in their suit can be used

**Comment by ThorvaldAagaard** [comment]
Another good example of the wrong cuebid
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/ccc64f2d-61f9-4627-a8ff-c627e8e2b6be)
0BAF5832BEF2112595FC8A2B7604
2H is wrong 2S (or 3S) is the right bid

**Comment by EdwardPiwowar** [comment]
I'm not convinced because cuebid in the opponent suit is limit raise or better, it does not invalidate the slam and is convenient in bidding. None of hands is minimum and none is maximum.

**Comment by ThorvaldAagaard** [comment]
Only cue with extra (18+). Always best to limit the hand if possible.

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/45334214-134c-46b5-a4f2-306885fca758)

**Comment by ThorvaldAagaard** [comment]
I think I would bid 4H in south, but NV and minimum except the 6th heart I can live with it,
