### ISSUE TITLE
Bug after stayman

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#421]
South bids 2nt after 2d which is invitational and shows 8-9 HCP but has 12 HCP.
South should bid 3nt instead.

0F25A5F43E9ADDEA70B983475234
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/7c60b8ed-d2fa-47e6-8693-f59dc42f1ac3)

**Comment by ThorvaldAagaard** [comment]
Agree, but should opener show a 5-card major, when accepting?

**Comment by ThePokerDude** [comment]
I did not get the question. The opener declined 4 or 5 card M.
So which bidding sequence do you mean?

**Comment by ThorvaldAagaard** [comment]
Ahh, I was just thinking invite. Ignore my comment.

**Comment by EdwardPiwowar** [comment]
Ok, I just want to know if there are exceptions for hands like below, where the responder, despite having 12 hcp, knows that 3NT is lost?
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/fe6fcf62-27dc-43c3-a1a2-15c69c65cc70)

**Comment by ThorvaldAagaard** [comment]
2N just looks wrong. Even knowing partner has at most 3H, 3N is clearly odds on.

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/dfea0590-8166-4956-8c86-18ee0ed31b57)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/90422b71-fb7c-4914-8f9f-03dc96c49816)
