### ISSUE TITLE
11 HCP should be an inviation when partner opens

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#422]
Better auction would be 
1d p 1s p 
2c p 3d (11-12)  p
3nt p p p

0A64CD1715CFA01D7C605C523675
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/44fe61d8-5779-41e9-83fc-fd79ea8c7686)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/cae8b5cf-46b9-46f0-85d2-eb1f980bf225)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/eb4e892a-2cc8-4538-90cf-84b674e26ba7)
