### ISSUE TITLE
1m p 1M p 1nt p 2M is to play

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#426]
After the bidding
1m p 1M p 
1nt p 2M 
opener should always pass.
Especially after
          p p
1m p 1M p 
1nt p 2M 

So 3M is a mistake and leads often to 3M -1
11F2A91F26943FACC0F9FC5D032A

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/13be7e15-f705-432b-91c3-f748f356145c)

**Comment by ThePokerDude** [comment]
pass is especially correct when p p 1c p 2s shows maximum and 5s as in
601AA963375D7E7023FBD6160F85
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/21518624-ebfb-44dd-99d3-eab0c6ef2487)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/bf34deb6-65a4-49e1-a5c5-be280c7df51c)
but the second example is not clear.

**Comment by ThorvaldAagaard** [comment]
The second example is not an error but just to confirm, that opener should not bid, as North would have bid 2S directly with a maximum hand,

So this is fine

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/eef3e262-9ae8-4c71-982d-f3d8a6c9f66b)
