### ISSUE TITLE
Rubensohl - bidding and description don't match

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#428]
Description says 12-13HCP, bidding 20HCP
I do not know Rubensohl but 3c seems wrong to me, if the responses are similar to Lebensohl.
Probably 3h asking for stopper would be correct.

9636222596D23E79707C44E8E4D4
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/5c7dcef1-6bae-428f-baa4-482e26e03554)

**Comment by ThorvaldAagaard** [comment]
In Rubensohl Doubler must break the transfer with 17+, so accepting is like 13-16

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/fc126a2e-2154-4963-b128-b571fd4dfee8)
