### ISSUE TITLE
Passed hand T/O double (#47)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#43]
2A19209B23D1A86A4E00F98D4084
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/27546a43-b9e6-41f2-8a7f-9f6f33eaf35f)

As a passed hand south has an ideal T/O D of 1D,

**Comment by ThePokerDude** [comment]
Fixed in 8137. South now finds the TO double.
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/1e9a3687-2615-45a1-9aa4-7b4d971315bb)
