### ISSUE TITLE
rebid not 1NT with a balanced hand in range

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#439]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/acb24ca7-42a5-4d15-837c-8a06a89f2cd7)

rebid 1NT it doesn't even have a singleton heart which some people don't like for some mad reason.

**Comment by ThorvaldAagaard** [comment]
Please test it first in BBA with the BBA code, to make it simpler for Edward, and include the BBA code as text

0C14D10E29BD64C896FDEBEA70BE

**Comment by ThePokerDude** [comment]
BBA 8101 bids correctly

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/8e3f8bb4-f94c-4302-b0d6-79c113cc0c02)

**Comment by EdwardPiwowar** [comment]
This is probably one of the last fixes.

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/4cead731-e65a-4e7f-9633-35f382cf7fa1)
