### ISSUE TITLE
BBA did not splinter

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#444]
0B57CDBDE7E0D431E046B3A35B4C
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d2e47ac1-b474-4235-ab22-05ce23003e40)

The splinter in 3S match Norths hand. After the splinter I think 3N looks wrong with only Qxx

After the inverted minor South should bid 2N with stopper in all suits and minimum

**Comment by EdwardPiwowar** [comment]
BBA would need for splinter 1 pts more...
Next BBA avoids 3NT.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/895bbf44-463e-492a-963e-5bf7cb5ed550)

**Comment by ThorvaldAagaard** [comment]
The description is 11-19 HCP and here is 14HCP. A good rule is it is an opening hand with shortage

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/b949f882-f11a-43f5-965b-381c35b6c444)
