### ISSUE TITLE
1d p 1h p 1nt p - with 6h you have to bid 2h instead of passing 1nt 

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#445]
South should not pass but bid 2h
0E016F17E879376FDEEEAD60D085
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/1e6ab2ce-bed3-4ec2-b08a-67b1541d2d1d)

**Comment by EdwardPiwowar** [comment]
Next  BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/54b0530a-8e18-40f6-8cd8-c7f2c6809e97)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/f7117e74-4ebd-45c8-be4c-debe84547ee0)
