### ISSUE TITLE
Missed 4nt quantitative bid

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#446]
I think 16 HCP and a 5card minor is too strong for 3nt. 4nt seems quite right.
The description is wrong - it says 9-13 HCP

0A305A48E3651E88D9A324CC2FB9
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/ec9ee79d-87d9-4b5a-a3c8-c7e38d41d945)

**Comment by EdwardPiwowar** [comment]
Bug after corrections. E can't bid 4N here because he already knows it's a slam.
Next BBA:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/798bbe90-3c48-488e-b1fc-1189bd73958f)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/8481eb2c-3e72-4d42-a761-01a749a505e5)
