### ISSUE TITLE
Missed slam

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#447]
Slam is very good and we miss.
So I am pretty sure that 4nt is wrong at table 1.
It does not give you the needed information.
But I'm not sure what to bid instead.
How is 2nt and 3nt defined?

1494AE0EF552F931B693689A4BEE
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/13b6c6fe-e887-40d7-9f17-0a28caefdb61)

**Comment by EdwardPiwowar** [comment]
To read the meaning of all offers for a selected player, you need to select him. 
2N is defined as 15-17 and 5=S
3N as 18 HCP -  that is, it is not meaningfully defined.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a7721a65-4f3b-47c4-9530-26fc1f35820f)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/b282a536-1a6f-4d09-a4b6-e7d544142f45)
