### ISSUE TITLE
Not sure which table has the worse bidding

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#453]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/15331f7d-5c8d-4d9c-b1f0-bcd95bc25e10)
012F8BCE086ED463DFE527CE2D16

So first question:

What does bidding 3NT mean?  Does it say I have extra but I don't care about cue bidding?

Then 4NT asks for aces,  ok.  But the problem is I have enough aces and then north stops.  Somehow you have to make RKCB ask for aces and then if you don't have enough pass is allowed but if you do have enough it is not.  I have no idea how you do this as BBA doesn't have a look ahead when it makes a bid it just bids what it thinks is good now.

Somehow RKCB has to just be confirming the controls you need are there to bid the slam,  or not there so you stop.

**Comment by ThorvaldAagaard** [comment]
At table 1: After 3N the right bid is 4D denying the club control
After the wrong 4N, the right bid over 5H is 6H 4 Aces + trump Queen is enough after asking

At table 2: 5N is wrong. South miscounted the aces.

**Comment by EdwardPiwowar** [comment]
3NT is a cue bid to show surplus 3+hcp, good trumps and all stoppers. 3NT is forcing. N can't pass. 
Currently
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/6f10442d-1c2e-4128-a3a3-ad144415c118)

**Comment by ThorvaldAagaard** [comment]
```3NT is a cue bid to show surplus 3+hcp, good trumps and all stoppers. ```

What do you call this convention? And I would like to be able to deselect it.

It could be fine to have this sort of agreement, but then it should be serious/unserious

**Comment by ThePokerDude** [comment]
Fixed with 8140
![image](https://github.com/user-attachments/assets/37c9364d-c831-43f5-bab1-453a2d88e286)
![image](https://github.com/user-attachments/assets/65def5d8-b2a6-4919-80d8-4f52e43e3cb5)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/a066806b-0099-4c0d-a0c6-50df3905daf0)
