### ISSUE TITLE
We do not have requirements for stoppers when opening 2N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#454]
02E3774FAB9DB9CA5510083E73C4
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2ff63ad0-415d-4c8b-bb24-4cecc8363db5)

So this is a pretty standard 2N opening

**Comment by EdwardPiwowar** [comment]
Explain pls.

**Comment by ThorvaldAagaard** [comment]
Wrong board
