### ISSUE TITLE
Counting to 13 is difficult

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#459]
055C2CCC5C3D561BEAF10EF34FCA
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e202be14-1763-4f28-9498-e33292489541)

I could only get to 11,5 

4N is quantitative after 3N, that is OK.

With North 5-6 odds are bad for North having Ace of Hearts

**Comment by ThorvaldAagaard** [comment]
This looks right
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9350b0fa-1426-431c-90c1-2ba6d6db8f27)
4N denying a control is a fine bid

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/e36ce262-d0cf-419d-b48f-d2288a7bffd2)

**Comment by ThePokerDude** [comment]
looks ok to me
![image](https://github.com/user-attachments/assets/e3d10807-995b-472b-855f-b23ce33e7097)
