### ISSUE TITLE
Why hiding all hands?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#461]
When I want to bid all 4 hands BBA hides all the hands
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/92c1a01d-1da2-4072-b537-bf094b2098ce)

**Comment by EdwardPiwowar** [comment]
Because they usually don't match your bid, especially if you haven't entered any deal. But I'll think about it.

**Comment by ThePokerDude** [comment]
I think this is fixed now
![image](https://github.com/user-attachments/assets/c1f9fb81-bf56-482e-a924-379137f23874)
