### ISSUE TITLE
Gerber with a hand wich is too weak

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#466]
Even though we have a 6card suit 12 HCP is not enough for Gerber.
The correct bidding is 1nt p 3nt
After hearing that only one ace is missing BBA stops at 4. So why Gerber at first place?

068398E2FF9C610193FA51D7E836
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/29987b13-0925-464a-810d-4c8ca0bb8ae6)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/ffe406ca-8cd0-45cb-ab8c-67bb28059100)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/e37a53f6-9117-4cc3-85e5-99376bec7574)
