### ISSUE TITLE
Hand to bad for a penalty double

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#467]
05B76F1F68F22B3400A6399FC941
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/bbdcbb9a-f613-4f39-ad00-4efb5189703a)

Without a lead it is wrong to make a penalty double of 1N

**Comment by EdwardPiwowar** [comment]
Currently double 15+HCP.

**Comment by ThorvaldAagaard** [comment]
Ok, better but it could be interesting to compare
14+, 15 and 16+
and adding a requirement for having a lead (Defined by 3 in a sequence, or 5-card)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/9c766fd5-44eb-461f-ac74-f24e4f2c734f)
