### ISSUE TITLE
Disaster of the day

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#473]
0F3505492AE9C3E38E65A9EB8210
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/ca6b3424-5470-4b02-80ba-837272d19c1d)

With 4H showing 2-5 going for slam might be optimistic, but the real problem was that GIB did not ask for aces, but cuebidded 4S

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3f17bff9-e5f4-40a0-9130-2d1a01f050fe)

South should now bid 5H without any controls.

As BEN has not been trained with cuebids, it passed 4S

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/315e3ba2-ace3-4ccb-9fea-72f5a606e5b5)

**Comment by ThorvaldAagaard** [comment]
No overcall by East?

**Comment by ThePokerDude** [comment]
Still no overcall.
Now north bids on after 4h.
![image](https://github.com/user-attachments/assets/24907a0c-d9b2-4fa8-b154-7ab9b05d46b3)
