### ISSUE TITLE
Wrong response to 4th Suit Forcing

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#474]
0406B6C3B9982A45440074CB7113
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/7fe2d28e-2168-4116-bade-f72b0ed01322)

With KJT in the 4th south, south should bid 2N.

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/dfe989d3-555c-4510-a1a2-19fae0eb8785)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/6ac1af65-2a3f-4265-8b68-32b14e540b9f)
