### ISSUE TITLE
Forcing 1N with 6-card support

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#477]
096FCAB1882C9C1F06189412249D
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/40d4b82f-6ddf-42a8-ac4b-07216bb8f142)

**Comment by EdwardPiwowar** [comment]
Next BBA
4S if SEMI_FORCING_1NT
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a04440ca-4ff7-441d-aab3-a742b6db6a89)

**Comment by ThorvaldAagaard** [comment]
I am not sure, what is best, but I am convinced that 1N denies 4 Spades, no matter the system

https://bridgewinners.com/article/view/bidding-problem-2-0xk9mda2e6/

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/cb1d9c49-8c8d-401c-9005-d37c35a2a364)
