### ISSUE TITLE
After overcall you should try to limit the hand

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#478]
05A610517475B1248FD2AA39CF95
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/87227f36-4739-471c-8f75-d98d185e81bd)

No need to go past 4S, I think 3C is wrong, but also OK with 4S directly after 2D

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8ed79fac-b6e3-4a25-be12-0bba8e324c4f)

**Comment by EdwardPiwowar** [comment]
Currently
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/c5ed83d0-545d-49d4-b9b8-9e34eedd0eca)

**Comment by ThorvaldAagaard** [comment]
Better, but still 2 bidding rounds to many without any specific reason.

Is 2H game try or GF? If it is a gametry, I prefer 4S, and if it is GF, the hand is too weak.
After 2D we expect to play in Spades, so we only show stoppers if slammish.

Same with 2N. Game try or GF? 
And 3C 
And 4C

**Comment by ThePokerDude** [comment]
looks good to me now
![image](https://github.com/user-attachments/assets/66c8b4b5-2342-4b9c-bae5-763a62ce1afa)
