### ISSUE TITLE
Ups, some strange bidding

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#480]
084148A855ECB830497F942A4699
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/18a81c14-f03c-4aaa-98db-b4e53b0622fd)

It seems 3D is unlimited, then it should be forcing.
I do not think 3D should be forcing, so the right bid is 3H, that is GF - and South can bid the natural 3N

**Comment by ThePokerDude** [comment]
looks better now
![image](https://github.com/user-attachments/assets/1744187c-640f-48b7-a1fa-74d6e08739c9)
