### ISSUE TITLE
Bid what you think you can make

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#481]
With an 8-card spade and a partner, that opened it seems right to bid game
02941A25B0F695A8D9B79CB1A2D5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/a0841e25-7b78-4373-9f77-a7c7092fbe5a)

**Comment by ThorvaldAagaard** [comment]
3E620DEF42A8EA7D02E7693C4BE1
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/fd550e6c-5609-459b-8524-fd3434e7a8ef)

Interesting if North should bid 5H (I would)
X from South showing it was a good 4H and not just penalty

**Comment by EdwardPiwowar** [comment]
1 Currently
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f459adfe-2606-4f46-9832-5a667210637c)

2 Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/8f93cdc7-6e3a-4fc5-a7a4-6df8aa89a020)
and I don't ask bots why.

**Comment by ThorvaldAagaard** [comment]
It is two different boards - 8-card suits (or longer) are never a weak 2, not as opening, and not as 1x-(1Y)-2Z weak

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/4df627f9-8902-40a4-8a19-a57a4f79129b)
