### ISSUE TITLE
I would accept the invite

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#486]
1D17A251F3D47BAB7E04799760F7
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9bc0d40a-f96a-424e-9e38-e8b0fa881b02)

Actually it will probably go down, but still looks like 4H is the right contract

**Comment by EdwardPiwowar** [comment]
Because you play better
```

          AJT
          AKT8
          KJT
          T98
Q532                 976
Q43                  6
A32                  Q764
432                  AQJ65
          K84
          J9752
          985
          K7

```

**Comment by ThorvaldAagaard** [comment]
No, I just need 40% chance of success too bid game :-)
