### ISSUE TITLE
New minor forcing

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#490]
22B484E17E552BF89D29B8491EA0
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/6f829a17-a305-4643-9bc6-bd2e5f5f4b3e)

Playing NMF 2H is non-forcing, and limited to 11 HCP
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d3058726-ea8a-4ec2-92b9-a86869a1b25a)

**Comment by EdwardPiwowar** [comment]
Corrected

**Comment by ThorvaldAagaard** [comment]
Fine
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d64e06c9-de9a-4c00-a7c4-f2068907e904)
