### ISSUE TITLE
Missuse of 2N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#491]
24452E56BE9188B913E81A62BDB9
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/ef84c303-0f94-492f-883b-9bd1a9c3f331)

Even with max North should no go for slam, and with minimum North should still bid game.

So 2N is just helping the opponents - just bid 4S

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/731c7214-1c1e-458b-b2ec-b9341faaa9ce)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/18197223-a5fc-4b7c-b82e-9256e6c5866d)
