### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#492]
308F6136B318B9D542EA4CCC7968
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/6311898c-da2e-462a-940b-2c69392255d7)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/bc20146f-f59f-44b4-8f19-bec142fc1cbc)

I think South should just bid 3N instead of 4th suit.

The jump to 2N looks odd, yes, there are 13, but no real stopper, so 1N is fine (in lack of better bids)

After2N from North 3D is a terrible bid (It is slammish and should be at least 17 or equivalent)

**Comment by EdwardPiwowar** [comment]
Currently
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/1fdb1666-1fc8-4f28-a2e6-6241cbaa79b9)

**Comment by ThorvaldAagaard** [comment]
Better, but why is north bidding 3D?

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/c08d3d84-2747-4a77-9f1f-dab66e3c6461)
