### ISSUE TITLE
Bidding a grand with a missing King and max 34 HCP seems wrong

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#497]
492B4923DEB47D5CBCD953A29332
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3a11384d-b7b1-464f-b826-245c3d7617a9)

**Comment by ThePokerDude** [comment]
looks fine to me now
![image](https://github.com/user-attachments/assets/8126fe58-5397-4c17-bc0d-6d1e09367a68)
