### ISSUE TITLE
Exclusion can NEVER start in a bid suit

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#498]
4186226505AA4D5C62EE782242B8
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e1b8b0ed-875e-45a9-85cb-1a9878da69b0)

So South will have to start the slaminvestigation by cuebidding 3S.

1C-1H
2H-3S
4H
As North are missing CAK and DA South might go for slam

After 4C I am not sure it is right with a penalty double in North, but now South should drop all slam ambitions

**Comment by EdwardPiwowar** [comment]
Currently
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/78a0d76d-3590-4e43-a5f5-d174604e1d80)
BBA treats C as unbid in this case.

**Comment by ThorvaldAagaard** [comment]
To much Polish Club :-)
In SAYC and 2/1 1C should be treated as natural

**Comment by ThePokerDude** [comment]
looks ok to me now
![image](https://github.com/user-attachments/assets/59a4818f-4a31-40e5-83be-ca048d9b7980)
