### ISSUE TITLE
1Ma-X-XX denies 3-card support

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#499]
4887D03D61B106B6DB1C987B855F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2ca9eeef-dc88-4dba-8c5e-a5a227ff5d4a)

The problem might be that XX is 10+ HCP, but 2N is 11+ HCP

Here 3C is GF

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/480d7e4b-424d-4cf7-b8d7-db1d2c25bde7)

**Comment by ThorvaldAagaard** [comment]
81419D9A25003CB75630B62AED90
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2ceb1f41-5cc3-4e39-b260-adc4c87eb97f)

Seems to be the 10 HCP again

**Comment by ThePokerDude** [comment]
looks good to me now
![image](https://github.com/user-attachments/assets/fd3e5d4e-1ccd-4a87-9ad1-1488427d06c7)
