### ISSUE TITLE
Generating deals fro BROMAD

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#5]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/64f0bd33-1405-4a14-9bcf-121f15230a0a)
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1b99ea9e-9986-4f5f-aaeb-0028ad2e44b2)
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/911d3c8d-8eb8-4555-a458-9831c721e7be)

After 50.000 deals it found none

Same problem with 1D with 5 cards
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c0c2b387-24ae-4c2a-a735-6ff2c0c96236)
 ![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/db2cf591-6bac-4b40-b136-9b8e64b3cf0e)
But this perhaps only work if Polish Club

**Comment by EdwardPiwowar** [comment]
The bug has been removed.
If "Fit showing jumps" is on, BROMAD level 3 is disabled.

https://sites.google.com/view/bbaenglish/description-of-conventions/bromad

1D applies only to WJ - as shown on the label.
