### ISSUE TITLE
Difficult hand, handled badly

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#500]
4EB6F4BE9293436D3D9C4A09DDE0
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/017baa4d-3dd6-45c1-8f09-1e7b8ec358c3)

The second double is missleading and getting NS into trouble
If feeling to strong for 1S then 2S is an option

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/dfa05d92-601f-4360-8b41-e3c1f83d68cd)

**Comment by ThorvaldAagaard** [comment]
It could be an idea to label an issue with the version number, when you think it is solved, then it will be easier to check and close the issue. So here you label this one with 8131 - labels are searchable

**Comment by EdwardPiwowar** [comment]
But the next compilation may appear with a higher number, omitting e.g. 8131.

**Comment by ThorvaldAagaard** [comment]
Yes, but you can still use a the label to see if it is expected to solved, so we can close the finished ones
