### ISSUE TITLE
2N is just a wrong bid

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#502]
4D5B393ACD62C7DE52F4C00AEC42
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/df14b9fa-75aa-4193-8fb2-6cbeebf00148)

I am ok with bypassing the 1D response on a bad 4-card suit, but after 2D North should either bid 3N or 3D, not 2N

After a 1D response South should be able to splinter in 3S, but it is defined as 5-card spades.

After 1C-1D opener has these bids
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c4c93d51-6d7c-4d33-a2ec-a2477b0e857b)

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/2453dc0d-8bc3-4588-a2ca-84d15be930f7)
![image](https://github.com/user-attachments/assets/8f845f49-b344-4185-96f4-ede188abc940)
