### ISSUE TITLE
Lebensohl

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#507]
What is a set without Lebensohl error
6624DAC262686F513D6C30354BBF
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e8369a64-7a07-4384-8e0d-f655bfe85bc3)

3D is 8-11 HCP
3S is also an option planning to pass Souths 5-card 4 H or raise a 4 Minor bid

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/ac59224e-3a64-48cd-84f8-04d5a9099391)

**Comment by ThePokerDude** [comment]
looks ok to me
![image](https://github.com/user-attachments/assets/6a6ef1b4-34cd-4059-a364-78a9bf012784)
