### ISSUE TITLE
Forgot to ask for trump Queen and missed the slam

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#508]
652C12A627EB61775FE5C57FC8CD
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0482b321-367b-4d92-8d88-99cf4e4d4f92)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/d3e1c9f7-f7e6-46de-ac45-7db5921172a5)

**Comment by ThePokerDude** [comment]
looks good to me
![image](https://github.com/user-attachments/assets/21e7ec97-5132-4400-8215-0b474a0f463c)
