### ISSUE TITLE
2S is wrong

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#516]
85AA10C02F95BBB3F4C54D378154
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/faceabb8-9ed5-4122-9098-c9b36a666171)

with 3-card support and 10 HCP the right bid is 3S
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/bbeca257-7b0c-4a72-904c-03d2d681a73b)

**Comment by ThePokerDude** [comment]
Looks ok to me
![image](https://github.com/user-attachments/assets/3936047f-3523-499c-b2d7-3ba8e84496bd)
![image](https://github.com/user-attachments/assets/4553fad4-bd4c-4ca9-b92d-668b1e5e6592)

**Comment by ThorvaldAagaard** [comment]
It still has the Stayman problem, but I will be closing this.
Opening 1N can be OK, but it would be nice if we as user could define the rules
