### ISSUE TITLE
Not allowed in the ACBL

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#520]
20C3143012EED8742EBA41886BCB
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1ac53dec-0ad8-49d7-b696-5ac12675bcd0)

Seems strong enough to open 1D, and then a reverse

**Comment by EdwardPiwowar** [comment]
This is a bug after the conditions for opening 1NT were loosened.
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3795e8b1-ced4-45bc-9cfa-5617b768aa2b)

**Comment by ThePokerDude** [comment]
Looks fine to me
![image](https://github.com/user-attachments/assets/37a933f4-9da8-4539-a08c-41c8a0ba044e)
