### ISSUE TITLE
response to dbl often in wrong suit as here

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#521]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/bcf00267-35a3-4c63-a2af-05f6fcab8bcb)
029F531AA1F51A5E9D8D3316EA19

So we should be bidding spades not clubs for example.

**Comment by ThorvaldAagaard** [comment]
Funny board :-)
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0fb6ca5e-60bc-4f04-856c-4bd73babc401)
What should South bid after 4H?

And even if we bid 4S, East will bid 5H.

But there is an error as X of 4H should not promised 20+ HCP 
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2d9c57cc-85c7-4207-bed1-bc68bec63745)

**Comment by Muppet1** [comment]
The problem is north bids clubs not spades this is what I am trying to correct.

**Comment by ThorvaldAagaard** [comment]
No clear direction after 4H (When the 1S is fixed)

https://bridgewinners.com/article/view/bidding-problem-2-d8iccah14a/

**Comment by ThePokerDude** [comment]
The original issue (2c intead of 1s) is fixed in 8635
![image](https://github.com/user-attachments/assets/37a68c3f-e4eb-4648-8433-93a17fde0942)

**Comment by ThorvaldAagaard** [comment]
I think it is an issue, that South don't double 4H, and X should not be 20+ HCP
