### ISSUE TITLE
Another missed game (#82)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#53]
592D0C20D6F159BB34A270D5428A
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/dfa73fe7-f6c1-464b-87e8-e274211f5b8d)

With a very heavy 2D and clubs very well stopped I think 3N is the right bid.

**Comment by EdwardPiwowar** [comment]
WB5 does not use strong double. This may be the key to good results.

**Comment by ThorvaldAagaard** [comment]
I agree with the 1D-overcall, but I would probably bid 2C in response showing a limit+ raise. Having bid 2D and seen partner making a gametry 3D is just really bad.

**Comment by ThorvaldAagaard** [comment]
Ok, I will live with 2N as in version 8105
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/58515bda-d873-4898-9b5b-6210d4770115)
