### ISSUE TITLE
Make version of BBA visible permanently

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#532]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3b619914-65a7-4d61-8b5e-7f622667a6a8)

This is fine to see the version, but when looking at old screen shots we can't see the version number. 

Perhaps you could add it to the header?
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/37fe1d8c-d21e-4531-9f15-69b1548209f3)

**Comment by EdwardPiwowar** [comment]
OK

**Comment by ThorvaldAagaard** [comment]
Nice
