### ISSUE TITLE
Act with 5-5

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#535]
0C693B3C404664D157E061BA3721
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/97d62c87-1113-44c9-860f-02cd974a942f)

South should bid 2H over 2C, NS was lucky, that EW did not take the money against 3CX

GIB thinks X of 2S is penalty, probably based on Pass first followed by X is normally penalty. I think that is a good rule

**Comment by ThePokerDude** [comment]
Yes, 2h non forcing is correct (about 4-8 HCP).
Let's say the bidding is
p 1nt 2c 2h
p p 2s

we can bid now 3d as partner knows we are weak.

**Comment by EdwardPiwowar** [comment]
It seems that transfers are used here
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/473b62ca-ba2d-40dd-a64e-3f60887c530a)

**Comment by ThorvaldAagaard** [comment]
Yes, after a 2C overcall it is system on - D = Stayman all other as without the overcall.
