### ISSUE TITLE
BBA is not following system

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#539]
088042CAACB34986462712D597F6
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/fbe3e25a-825b-4ade-b43f-fff88168fd4f)

When playing 3H as invitational it makes sense to use that bid, and finding the right contract

**Comment by ThePokerDude** [comment]
at table 2 I think the correct bidding would be
1s p 1n p
2s p 3h p 
4h p p p 
3h = inviational with 6card h suit

With this very good hearts I think even 1s p 2h GF is ok

**Comment by EdwardPiwowar** [comment]
"Shape Bergen structure" and  "Strength Lawrence structure" aren't implemented yet (To do), so I can't correct table 2.
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f6d90926-8a02-46d5-bfdf-36a73e7e3b95)

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/95ba26c7-de92-4dd2-8bf9-a4febf3a173b)
