### ISSUE TITLE
Bad T/O

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#547]
0CE5AB6B9D98D2FACA3B01D07C56
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c6f39df7-59b9-4a9d-be36-dcd6774890e4)

I am not sure it is right to XX on a minimum hand, but after XX the rule should be: Either we play or they play doubled. (That is why 13 is not enough to XX)

**Comment by ThePokerDude** [comment]
And please increase requirements for X after this auction.
There can be multiple resons for a T/O double
1) we could have enough for game
2) we want to bid competitively to either make part game or let opponents play to high and go down
3) partner could have penalty and had to pass

When opponents open (opener is not limited to a weak hand - can still have 19) and opener's partner responds (about 5-10 HCP, 5 with good distribution) 

1) the probability for game goes massively down, so we should not worry about it.
2) to bid comeptitively we should have shape
3) partner cannot have penalty in spades

I'm aware that it's pretty hard to define the 3 mentioned situations properly.
But I think it's worth it. Then we have an easier time to formulate rules for the double.
If BBA would know it's in a "fight for part game situation" it's 1st check would be - do I have the correct shape? Answer - No -> pass

**Comment by EdwardPiwowar** [comment]
Next BBA
The requirements for X increase in the cases described.
Opener XX will be 14+HCP.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/40219c06-22bf-4541-b59b-133097d48066)

**Comment by ThePokerDude** [comment]
Looks fine to me now. No double and no redouble.
![image](https://github.com/user-attachments/assets/02783d48-5e77-4c5f-80e8-4fb8b6e76d29)
![image](https://github.com/user-attachments/assets/df4259ad-0f43-47d6-a773-fd86527c2309)
