### ISSUE TITLE
Miscounting Easts hand?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#552]
6CF27F58A64F8992BD0FFC06A748
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/520ffae6-2b90-485c-839a-138a02fda34c)

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/5c2fbdcd-bbbf-492c-aa1b-f9e9f3c9327f)
