### ISSUE TITLE
After 2C the weak hand should only take control with own suit

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#556]
68F5E7CD7CCAA9C8EEAA4F2E0C61
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1805f573-2db3-4d26-8472-78826bb2cefc)

5H is a maniac bid,
4H as splinter should always have at least 1 control
4S as 3-card spade an 0-1 control is fine

**Comment by ThorvaldAagaard** [comment]
Agree, I would normally expect 3S to show 2+ control, and 4S to be 0-1, so East should bid 4S even with the void.
And splinter should also show 1(2)+ controls

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/60a10523-32db-4f66-9fe5-2e700d602e98)
![image](https://github.com/user-attachments/assets/5c72c120-b20e-4c59-b19d-5d0616b75303)
