### ISSUE TITLE
Dummy analysis

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#562]
When a filter is applied like

```
1N-P-P-X
```

Then dummy analysis should only be executed after the filter is matched and not before as now - disabling double dummy helps, but really no need for the single dummy until a match
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d60a092b-b021-483a-9920-af4f8ba437db)
Single dummy can't be disabled

**Comment by EdwardPiwowar** [comment]
SD only slows down the loop by 5%, but in the new BBA (currently preview) there will be an option to turn it off.
I don't think everyone may like the automatic disabling of SD and DD, apart from introducing some confusion.

**Comment by ThePokerDude** [comment]
I could now disable SD.
I do not fully understand the filter.
The bidding in the example does not look like the filer setting.
But as I do not understand the filter, maybe it's working fine.
![image](https://github.com/user-attachments/assets/fb1e35ab-e121-442c-9042-0db7bb06ffaf)

**Comment by EdwardPiwowar** [comment]
Andreas, 
there are three filters operating simultaneously:
- IMP;
- loop count;
- convention or sequence.

In your example the second filter worked (4000 mod 2000).
https://sites.google.com/view/bbaenglish/program-description/automatic-bidding
