### ISSUE TITLE
I think I have reported this before (#121)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#57]
Making a penalty double with 4-card support and 7 hcp looks very wrong
77F132978CD6CD872D9D90BB0E03
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/bdc69e61-5c2e-425c-aae1-c0c69b367034)

**Comment by ThePokerDude** [comment]
Fixed in 8137 - I checked all systems and none of them bids penalty double. All bid 2s.
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/640be5c5-621e-4364-8460-fe45af11c3d4)
