### ISSUE TITLE
Weak opening in 3rd hand

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#581]
02A90873B046E0C9086CAEB3F503
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/bf3bd19a-38cb-4484-8bb4-e37de6ab4a16)

I know BBA opens very light, but I think rule of 20 should be applied (HCP + 2 longest suits should be 20)
Here in 3rd hand opening 1C is to light in my opinion.

**Comment by ThePokerDude** [comment]
At least we stop now in 3h
![image](https://github.com/user-attachments/assets/61589000-f809-441a-9709-37f1a4e583e4)
