### ISSUE TITLE
No negative double for 2/1, but OK for SAYC

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#585]
0C3398D051940CA2EF559FC6F803
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/275aa073-a644-45cd-90b7-0c4f4e54b7da)

X on souths hand is right

**Comment by ThorvaldAagaard** [comment]
Of 35 players BEN was the only one not to double ending in 3S for a score of 100% :-)
But only because BBO BEN kept open with a T/O double, and that would BBA not bid

**Comment by ThePokerDude** [comment]
seems fixed with 8128
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/ff3e0f3f-4ead-47c6-a5f2-28b6c8b6d1fd)

**Comment by ThorvaldAagaard** [comment]
Seems to be related to cc
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/14c4241a-ca69-428c-9324-2e9f23921134)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/26eb9539-3864-4b22-b824-0dfc0f167f73)

**Comment by ThorvaldAagaard** [comment]
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3c1c8e4e-3847-4147-97c2-8f93967359da)
