### ISSUE TITLE
The impossible 2S not implemented

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#590]
06BBC3A29465FA01DE6FFE6A512B
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/5ad0c288-54ef-44e7-a87f-a32f9c3932f2)

As north has denied 4S 2S is showing a good raise 10+ in diamonds.

Mentioned often on bridgewinners, but the site is down, so you just get the words from Mike Lawrence
http://kivabridgeclub.com/images/Impossible%202%20Spade.pdf

This is for both 2/1 and Sayc

**Comment by ThorvaldAagaard** [comment]
And a new example
00DA03871FEC0A93DE49FD574A17
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8325b823-cc1c-477f-a5b3-d0fc1432ed5e)

But here I prefer bidding 2C instead of 1N, and if forced to bid 1N, then either the impossible 2S, or just the simple 3N

In Sayc 2 or 3N seems better than rebidding 3C - It is a normal opening hand

**Comment by EdwardPiwowar** [comment]
In the next BBA I will enable impossible 2S also after forcing semiforcing 1N.
1
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/ede8cfcf-6a8c-4755-85b3-cd5e9816a6ab)
2
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a82aff60-be20-4b5b-ab80-2af3a17e9a29)

**Comment by ThorvaldAagaard** [comment]
Still some work to do 
3D is a terrible bid here
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/08a691a9-3d93-4847-85e7-93f42df0ade0)
2N to show min and bad clubs are better, then I think South should bid 3N

**Comment by ThePokerDude** [comment]
Looks fine to me
![image](https://github.com/user-attachments/assets/80d03aca-4799-4437-abba-d814136b06c6)
In the 2nd hand 2c is correct. I would prfer 2nt over 3h.
https://www.bridgebum.com/1nt_forcing.php
![image](https://github.com/user-attachments/assets/4a16dfe6-9c0c-4fd6-ad85-06cba444872e)

**Comment by ThorvaldAagaard** [comment]
I agree, but we have a problem with the north hand, as 2C should promise at least 3. With 4522 I prefer 2H.

**Comment by ThePokerDude** [comment]
Hi,

everywhere 4-5-2-2 was explicetely mentioned - they say 2c is correct. 2h is always 6+.

https://longbeachbridge.com/1-nt-forcing/
https://www.bridgebum.com/1nt_forcing.php
https://www.larryco.com/bridge-articles/1nt-forcing
https://tommybridgeblog.blogspot.com/2013/08/bidding-continuations-after-1nt-forcing.html

![image](https://github.com/user-attachments/assets/9dbb3210-edc1-4764-90ec-9e4555962362)
![image](https://github.com/user-attachments/assets/85d8b0b6-4978-4559-a8b1-2ecffd6662c6)
![image](https://github.com/user-attachments/assets/361b5742-ad0c-4720-a720-a74fb915c8f9)
![image](https://github.com/user-attachments/assets/b75f42c7-9c10-48bf-83c7-16f0198c6cc2)
