### ISSUE TITLE
This is a mild slam try, when playing Texas

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#593]
8C09AE8E981D556594B23B83C7FB
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/cef90616-1a79-49f2-8a50-782dfae51d4a)

I think I have reported this before, when playing Texas and Jacoby there is a difference between transfer 2H and transfer 4H

https://bridgewinners.com/article/view/rock-solid-6s-missed-by-80-of-the-field/

**Comment by EdwardPiwowar** [comment]
This is how it is implemented, but S forgot that it cannot ask for aces.
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3b56e1e9-a2b8-4e2a-b641-919a7295109c)

**Comment by ThorvaldAagaard** [comment]
So shouldn't North accept the slam try?

**Comment by EdwardPiwowar** [comment]
```

          AT5
          AQ43
          AJ52
          J7
2                    J98
K52                  JT98
7643                 KQT
AT432                Q98
          KQ7643
          76
          98
          K65

```

**Comment by ThorvaldAagaard** [comment]
That is not a slaminvite, just a texas.
You use transfer to 2H and bid 4S if Partner should accept the slam try with non-min and 3 aces

**Comment by EdwardPiwowar** [comment]
I will increase the HCP for 4S to 10, but BBA will not bid 6.

**Comment by ThorvaldAagaard** [comment]
Ok, closing for now until it happens next time :-)
