### ISSUE TITLE
Hand to weak for a jump to 3C, and 3H is forcing (It is unlimited)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#597]
0834AD1FD4C310878F90A82CD35E
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/5c7400c1-c1c5-4789-8fcf-9d2755267aad)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/604d3dab-ee77-41ad-a92e-bf9704a55f44)
