### ISSUE TITLE
Missing overcall (#144)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#61]
801A1571322E67A7FA0495C6ABDD
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3163a2c0-47f5-4951-801a-fa6cf9c6b0df)

Looks like a normal 2D-overcall

**Comment by EdwardPiwowar** [comment]
It will be corrected.

**Comment by ThePokerDude** [comment]
Fixed in 8137.
But I had to enter 1s manually beuase BEN and Wbridge now open 1nt.
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/ff289378-3aeb-4c14-8adc-910352f5cec2)
