### ISSUE TITLE
This should not be BEN-style

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#610]
0C8AB62B15ED964AFE368CFB1D1E
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8370b4ad-b08c-46ce-88d3-bdb69cbf799b)

BEN managed to bid like this
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e46cc65e-da4a-4de0-a230-ea273048cc30)

**Comment by ThePokerDude** [comment]
South is much too strong for the bidding at table 1.
If we want to start with 2c we should later continue with 2sas we are forced to game.
I like the 5d bid from table 2. But south should continue with 5nt after 5s.
After an answer which shows Qs we should bid 7s.

Is BBA capable of counting tricks in the bidding already?
If yes - then we could reach 7s when we apply rules for trick counting.
We have 5s tricks
Ah
AKxxxxx is worth 6 tricks
diamond ruff

5s
1h
1d
6c

for a total of 13

**Comment by EdwardPiwowar** [comment]
1
Previously, lifting the opening suit always promised fit:
https://www.larryco.com/bridge-articles/two-over-one-gf-part-11-responders-rebid
I think we need to come back to this.
2.
Only N and the table manager know about the ace of diamonds :) so S can see 12  tricks.
Next BBA
I agree that the qeen ask should be 5N but I left 6C for now.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f17d7ef3-3e4f-4db5-8a16-53e3a0cdca1e)

**Comment by ThePokerDude** [comment]
still not quite there. The description does not match the hand.
![image](https://github.com/user-attachments/assets/603a5461-3e4b-4d23-8661-4441ffd3de6c)

**Comment by ThePokerDude** [comment]
Quite ok, but description wrong.
![image](https://github.com/user-attachments/assets/3636a83f-5d4c-4fc1-ad89-9c2ac81a656c)

**Comment by EdwardPiwowar** [comment]
Next BBA 3-4S
![image](https://github.com/user-attachments/assets/0180965e-8418-4e7b-bce8-d574d91a5095)

**Comment by ThePokerDude** [comment]
Looks good to me
![image](https://github.com/user-attachments/assets/e0ba6ca9-077c-437c-bf54-0d4e3804c794)
