### ISSUE TITLE
This is signoff, not strong

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#616]
058D8C3E599F1E2EC76A9575597B
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/67e339a3-5e44-4a0c-91e3-ad563b884192)

3D is minimum and 6+ diamonds

In room 2 2S is showing extra and GF

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/26b9eaa1-523f-4629-8ac6-643ef1e5db8f)

**Comment by ThorvaldAagaard** [comment]
I think you have switched the correction
For 2/1 3D is sign-off, so South must bid 3S to show a slammish hand
For Sayc there is establish a GF with 2S, so here 3D is trong

Ignore diamonds 4-0 and it is a great slam, so it is OK to at least make a try for slam

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/d46ad4a4-60c6-4c22-9134-e57aae73c1ad)
