### ISSUE TITLE
Wrong opening (#154)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#62]
98E51F3564124B8D29581C75EC25
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0e2fc521-25ab-48c7-aaa3-06823c391883)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8f84bb53-93fc-44b8-9a33-dd81b6f9a127)
Why open 1H?

**Comment by ThorvaldAagaard** [comment]
No, I agree it is an opening hand in almost any system. But I do not like the idea of bidding a 5-card major before a 6-card minor.
So it is 1C-opening.

And in Sayc any 12 hcp should open

**Comment by EdwardPiwowar** [comment]
This one version would be any 6M5m and 11+ HCP.

**Comment by ThePokerDude** [comment]
Fixed in 8137

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/4e408e9b-60a0-46c8-90f5-e13b38e188fb)
