### ISSUE TITLE
Strange bidding after weak 2

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#620]
00B3287BE19A5C755228FEC071A1
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/814b6ec8-2f5b-47c0-b49f-5ecfce0830f5)

https://bridgewinners.com/article/view/bidding-problem-2-tfzol4io1u/

I would normally just bid 3N

But in room 2 it makes no sense to use RKC unless planning to bid slam getting an ace. North can't have 2 aces.

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/46e0a99f-05db-4894-9674-94482c355652)
