### ISSUE TITLE
Not a penalty double

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#636]
04B769E50339A72D8576C3895E5E
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b7be636a-f997-404e-b229-bcf1b5f383b5)

Or more correct, the double is a penalty double, but 3433 with no tricks can't make a penalty double

**Comment by ThePokerDude** [comment]
Still same. Double is described as penalty showing 4-5 hcp but we have only 2.
![image](https://github.com/user-attachments/assets/b17e31eb-61ce-4e75-bc21-6af55da53564)
![image](https://github.com/user-attachments/assets/3b070fc3-7e17-4ee1-bfda-8572bc70da6b)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/0c60244f-1ea2-45e4-8419-b523b62d9b58)

**Comment by ThePokerDude** [comment]
Fixed in 8643
![image](https://github.com/user-attachments/assets/7c917eda-841c-475b-ad3f-1b9d84fe634c)
