### ISSUE TITLE
Should overcall 1N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#64]
0F0F78A845F10CBE6C9F65297377
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/31e15bf8-4b5b-42e0-ac19-aee395f83178)

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/3b0825e8-6604-4a1a-ba38-11c3d470772d)
