### ISSUE TITLE
Preferring a 3-3 fit for a 4-4 fit

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#641]
0FAFCFE178E0F68903944C51B84E
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d6002fb3-5e30-4b0b-80e6-7377fe9b1fab)

Why is East bidding 2C?

If we let East respond 1S we get another error
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e43aa465-642c-4cdf-84e3-dc960ad906be)

Where support double should be 3 spades, so either pass or 2S is the bid

**Comment by ThePokerDude** [comment]
This is realy strange. The description of 2c says -3s but we have 4.

**Comment by EdwardPiwowar** [comment]
Both bugs corrected in the next BBA
1. 1S also showed 5C incorrectly.
2.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/a302be00-8af6-47d1-abbf-1e78c99d7da9)
