### ISSUE TITLE
Another deal with multiple errors - including the usual - this is not a limit+ raise

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#646]
002E0A054AE6DA1BFFE7075198D5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/124099ad-1876-46b0-98eb-86ad92768e06)

Start by looking at the wrong T/O double at table 2, if the intention wqs to show 17+ or better, then at least bid 2H after 2D

Now if North correctly bid 2H, then South finds a strange 3C

**Comment by ThePokerDude** [comment]
Looks ok
![image](https://github.com/user-attachments/assets/0876dae6-595c-4bd8-818e-3156a7c29ba2)

**Comment by ThorvaldAagaard** [comment]
With 2 shown suit (Spades and clubs) any T/O double with a single in red is wrong. Yes, I knowwe might have strong hands and a problem like this, but it T/O can be single, then it will be impossible to find a 4-4 fit in hearts.

https://bridgewinners.com/article/view/bidding-problem-2-hcvwskggpy/

**Comment by EdwardPiwowar** [comment]
It was a negative double - it will be removed.
Next BBA
![image](https://github.com/user-attachments/assets/d9d6698a-05b4-40fb-8fa2-e28d3171b2eb)

**Comment by ThePokerDude** [comment]
8643 - implemented as described.
I think it can be closed.
![image](https://github.com/user-attachments/assets/6c904ced-bd2d-4a45-b682-2dc183825b43)
