### ISSUE TITLE
Preempt on 1-2 HCP and 6-card suit is to narrow

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#647]
09451780E6BF139DCF64391D796C
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/9750d7d9-b234-4a32-b394-8c09c673ade9)

Perhaps the hand is to strong for 3C, but range should be 6-9 for 2C and 0-5 for 3 club

I don't agree with the penalty double in West

**Comment by ThePokerDude** [comment]
8643 - looks good now
![image](https://github.com/user-attachments/assets/25c96cfb-e269-4135-ada4-6657464e54ea)
