### ISSUE TITLE
2NT opening can have 5-card major

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#651]
0C62649A6F349BE209C937F51DA9
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/cc627e3b-7c16-4822-912d-230e775839d5)
I prefer the 2N opening, and according to system 2N can have 5-card major.

**Comment by ThorvaldAagaard** [comment]
0CE2429314FF94CBCD17ACB949A9
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/86d501ac-b6f4-41f3-9f3f-ff25c5430216)
And the same for showing a 22-24 NT
especially with a very bad suit

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/37171cc3-7692-4576-8fde-3ba0380ec060)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/fac9f3b7-640b-4efa-8eae-5fe490e3dc15)
