### ISSUE TITLE
This is just a weak two

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#653]
0B3F2A63F5282A95DA4CB576E663
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e0f09ae5-352d-416a-b1dd-a9039a02f03a)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f9a17444-1579-482b-aadb-c103f5280764)

Rule of 20 must be obeyed, no exceptions (Rule of : HCP + 2 longest suit)

**Comment by ThePokerDude** [comment]
Fixed in 8643
![image](https://github.com/user-attachments/assets/d39b13af-4ae3-4a2c-b604-b912cc7ded67)
