### ISSUE TITLE
When fit is sure, add points for void

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#656]
1CF87F03A9E2ED4072BBC911305F
Fit is certain, so you have to add some points for the void.
West's hand is strong enough for game.
1h x 1s 2d 4s is the practical bid.
Both opponents show some points so a slam try has very low prospects of success.
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/26d1c47b-2172-4c21-8d7b-b21b3b23977f)

**Comment by ThorvaldAagaard** [comment]
Norths first double is OK, but the second seems wrong as we don't play stolen bid.

West 3D is as usual wrong as Opener can't use cue for showing a limit raise or better, but only for slammish hands.
Only alternative to 4S is 4D in my book

**Comment by EdwardPiwowar** [comment]
BBA counts void in a rather complicated way, here in the third bid W did it not very well. 
"Opener can't use cue for showing a limit raise or better, but only for slammish hands" - opponents showed 15+HCP and this is a sufficient reason to bid 4S immediately.
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/3ea4adc4-d75a-456b-a9cc-d1d586fbd6ce)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/66723c0f-fe2e-49cf-a439-7ab551861f10)
