### ISSUE TITLE
This double must show extra, and a terrible 3D bid

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#660]
0223E8C42AFCD543D75C4996BBA5
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/28382b25-a7f9-42b8-915f-6bb60530f019)
Notice the double, where BBA describe it as negative.
Partner has denied 4H, so negative to what?
Forcing partner to the 3-level also requires extra, so I am on the GIB side

Now BBA bids 2D, where I prefer 1N, but much worse is the 3D bid
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/cfe0ab67-b576-4615-bb08-d4c884db2e73)

**Comment by ThePokerDude** [comment]
Fixed in 8643
![image](https://github.com/user-attachments/assets/c445348e-b724-44fd-85ce-65b0d3401b79)
![image](https://github.com/user-attachments/assets/9af067af-0ff0-4528-92f7-58a976a4ebe2)
