### ISSUE TITLE
Todays disaster - 4N is ? (And another this is not a limit raise)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#667]
000FBF08ED7D83D7943F969D4196
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/4ac217a4-6f7f-481d-8240-684ac722d549)

I am not sure, what 4N is in this sequence, but RKC with clubs seems wrong

And GIB did not have clue
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/a3e3b9bb-5d71-4e77-9d9a-7ff15e1583f8)

Now letting GIB bid the hand I noticed that the explanation of 3D was wrong
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1bdfc448-27fc-4923-be7e-23a9a134b3e0)

3D is just GF looking for more information - mostly stopper for 3N

**Comment by EdwardPiwowar** [comment]
Next BBA
3D will be treated as "strength cue bid" not "limit raise or better". BBA will bid 3D with slightly more HCP.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/47ca5afa-0890-457f-b3eb-be2603939668)

**Comment by ThePokerDude** [comment]
looks good to me
![image](https://github.com/user-attachments/assets/8b8f753c-6d7f-4d06-950b-e497b2063581)
