### ISSUE TITLE
Will this be fixed in next version

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#668]
09A2B80DA2EE9F05C36ED55EC50C
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b8431f66-3239-4bb5-a723-aaeecc5a10ba)

Opener is showing a strong hand by cuebidding, and not a limit+ raise

And also cuebids showing a stopper i another suit should be avoided - 4C must show club-stopper (and implicit the spadestopper)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/05069db4-1302-47c8-bbc1-35bcba7408e1)

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/8067f843-486e-4663-b245-36bab22a7e2e)

**Comment by ThorvaldAagaard** [comment]
If fixed, then please close the issue

**Comment by ThePokerDude** [comment]
@ThorvaldAagaard I don't have the privileges to close issues I did not open.

**Comment by ThorvaldAagaard** [comment]
Ok, I will close, the ones you test and find OK - I am getting notifications on any updates
