### ISSUE TITLE
4!H?  I'd rather bid 7!H

### ISSUE THREAD

**Issue by ADavidBailey** [EdwardPiwowar/BBA#676]
![Screenshot 2024-07-06 at 7 04 24 AM](https://github.com/EdwardPiwowar/BBA/assets/146357155/96eb06a9-8149-40db-8a2c-77b69f789d0d)

**Comment by ADavidBailey** [comment]
How 'bout 4N.  Once you learn about 2 aces and the K!D, 6!H is a lock.

**Comment by ThorvaldAagaard** [comment]
I think 4H is wrong, and North should just bid 2H
But when posting a board, then please copy the identifier for the board
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/24932038-6373-4e5b-8735-eb1ab93386bd)

Copy the hand with is correct number

Then we can paste that into BBA and try different biddings.

Here is is the number: 0889C1D0448DCA5A6041D40242F7

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/dc50ab06-7eb2-479c-9fd8-1330848b8d44)

Now 4N is RKC but for diamonds, that is strange
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/88e03f17-fd4f-4561-be90-e7f9403700e1)

**Comment by ADavidBailey** [comment]
Here's another similar hand.  Hopefully, I'll post it with the number:
0FD31B2894DF12A2B89B245A9A05

**Comment by ADavidBailey** [comment]
Hmmm, it'didn't post a screen-shot of the hand.  What did I do wrong?

**Comment by ThorvaldAagaard** [comment]
Same hand just rotated 90 degrees
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b89d2838-59a2-440d-b5ac-b1dc1a07f2a5)

But fine with the number

**Comment by ThorvaldAagaard** [comment]
You need to copy paste the number, and then the scrreen

**Comment by ADavidBailey** [comment]
It's wierd that I got the exact same deal -- moved from 11 to 4 -- after I rebuilt the lin-rotated-... file.  It never occurred to me that it might be the same board.

**Comment by EdwardPiwowar** [comment]
Very interesting hand, David.
It may be like below, but these are very unbalanced hands and it is difficult to locate key cards.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/4082a863-d5ac-4644-93b5-539385a5f37a)

**Comment by ThePokerDude** [comment]
I think it's ok now
![image](https://github.com/user-attachments/assets/4c6079a4-abad-40bb-af78-d3a0d7fa9cc0)

**Comment by ADavidBailey** [comment]
This is interesting...

This morning I woke up thinkin' 'bout vulneribility and I see you closed this post, that's 'bout vulnerbility.  My nightmare deserves a post of it's own.  Stay tuned...

**Comment by EdwardPiwowar** [comment]
Then close it yourself if you think it's ok.

**Comment by ADavidBailey** [comment]
Thank you!
