### ISSUE TITLE
Making a GF, then passing partner in a partscore

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#679]
0C2EE238E75AB95997BF8BDA4A1F
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/27d58f95-1f6b-4ccc-971c-288beca42ce0)

Due to the bad spade suit I am more a 1S bidder, but after 2S (GF), Pass to 3D is wrong (And looks like the most normal 3N)

**Comment by EdwardPiwowar** [comment]
BBA suggests 3H instead of 3D
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/03b3a6d5-3d82-4586-a078-949c5bac93c1)

**Comment by ThorvaldAagaard** [comment]
BBA would open 3D in North, but that is not interesting. Jumping to 2S is GF, so if the hand is going to Pass later, it is just a 1S bid

**Comment by ThePokerDude** [comment]
Looks better.
![image](https://github.com/user-attachments/assets/9800b61e-7d33-434f-827b-ea115be43e01)
and after manually passing with north
![image](https://github.com/user-attachments/assets/60d1de74-c5a5-46a5-8ed1-0fca79f223cd)
