### ISSUE TITLE
Isn't this hand too strong to open 1N

### ISSUE THREAD

**Issue by ADavidBailey** [EdwardPiwowar/BBA#680]
0809C1D8B44F456D27CFE272907F
<img width="1204" alt="Screenshot 2024-07-07 at 9 21 17 AM" src="https://github.com/EdwardPiwowar/BBA/assets/146357155/61110fd1-3222-48e1-aafe-a3fe27931a06">

**Comment by ThorvaldAagaard** [comment]
I agree, but I am more focused on getting all the agreements in place, before we add the up- and downgrades.

**Comment by EdwardPiwowar** [comment]
For shape 5422 there will be a limit of 16 HCP.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/7dd9942b-fa0c-458a-ab5d-dabbf44fbbeb)

**Comment by ThePokerDude** [comment]
8643 - fixed
![image](https://github.com/user-attachments/assets/a6a8b0dc-21dd-458a-a035-97eef5e022ee)

**Comment by ADavidBailey** [comment]
Thanks.

**Comment by ThorvaldAagaard** [comment]
If it is OK. David, then close the issue.

**Comment by ADavidBailey** [comment]
Thanks.  I'm closing the issue.
