### ISSUE TITLE
Just bid game, when, no slam and no need for trial bid.

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#684]
0CA8C573E07C3B45C63D6EAE2649
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/4839fb60-3918-4fef-afc9-98087e1e6c80)

**Comment by ThePokerDude** [comment]
Fixed in 8643
![image](https://github.com/user-attachments/assets/37310b1c-aa0a-4c05-b493-a693103d2c3c)
