### ISSUE TITLE
Why has the same contract different number of tricks in the analysis?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#698]
4AB4392FD507E2E4DA58FD076A3E
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f850f185-a663-4c67-bbc7-3efb2d74a240)

**Comment by EdwardPiwowar** [comment]
This is the imperfection of SD analysis. 
N incorrectly deducted non-taking spades.
