### ISSUE TITLE
grand slam with missing ace without any opponent intervention

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#705]
At some point you need the possibilty to ask for aces.
I think 4c as described her is not optimal - should be asking for aces.
This hand is also shown in issue 143.
https://github.com/EdwardPiwowar/BBA/issues/143
![image](https://github.com/user-attachments/assets/08fed5c4-6765-4925-b153-fa7c19ecd82d)

**Comment by ThorvaldAagaard** [comment]
6N is a final bid, so North should not calculate anything, but just pass.

**Comment by ThePokerDude** [comment]
Say bidding is ok. 2/1 bidding is wrong. We should not pass to 5d.
![image](https://github.com/user-attachments/assets/ad6bdbd8-e6e3-4c85-a1bb-94f3305c108c)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/de5de128-38cb-487b-ac55-41823b7dcc91)

**Comment by ThePokerDude** [comment]
Are we playing mixed or 1st round control cuebid?
In case of mixed at table 2 4s insted of 4nt would be correct.
After 4s south can bid 6c instead of 5c.
![image](https://github.com/user-attachments/assets/e6856cae-4cc6-4448-8eb1-85a400a17cba)

**Comment by EdwardPiwowar** [comment]
I'm lost, if there's anything else, repeat (Crosswood is important here).
Next BBA
22E71F27B7437A96C271D1C17D7F
![image](https://github.com/user-attachments/assets/12eb9c49-b637-4f72-9e68-fe3a99b1a4ee)

**Comment by ThePokerDude** [comment]
8643 - problem fixed
Especially the bidding for 2/1 GF I like a lot.
I think the bidding with 4s instead of 4nt in 8642 perfectly solves it for south as south now knows there are no two losers in spades and can bid 6c.
![image](https://github.com/user-attachments/assets/3e1d90d9-d574-4f22-b9bc-e2a836c9c997)
