### ISSUE TITLE
Response to a weak 2D (#85)

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#72]
Why is West not bidding 2S here?
55C6DDC3C34CC522BC62F17E9D80
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/b6b49f73-bef3-4330-903f-1fd67a68caf5)

Now I changed a few cards to make West strong, and now it bids 2S
55C6F1C3C34CC5229C62F17E9D8C
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/68b5ec37-aedd-4e32-8ea6-03a8dc630562)

But look at the explanation for 2S 12-34 HCP

Also interesting that 2S after passing first now suddenly is showing 15-15 HCP

The Double of 4H is way out, but probably due to the wrong description of 2S

**Comment by EdwardPiwowar** [comment]
Select a player and hover your mouse over the bid to see the meaning.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2ec5d2eb-b36e-4323-8b9e-47e272f4c1d4)
Generally from 15, but with some hands from 12.
But I see that a minor adjustment is required in hand evaluation.

**Comment by EdwardPiwowar** [comment]
N + E + S show 26 HCP
W should have 18, but no more.

**Comment by ThorvaldAagaard** [comment]
I think 4S is 7+ spades and could be on 
KQJTxxxx
It could also be a hand asking for Spade-lead preparred to run to 5C when double
It is not a position where points are relevant

**Comment by ThorvaldAagaard** [comment]
Looking fine
