### ISSUE TITLE
Is the menu for manual bids removed intentionally? 

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#725]
The menu made it possible to check whether bugs have been fixed, when the start of the bidding deviated.

For example it the lower sreenshot you see a hand from issue 152
https://github.com/EdwardPiwowar/BBA/issues/152
As originally BBA bid 1h instead of 1nt I can only test if the issue has been solved by manuallyentering a 1h opening.

![image](https://github.com/user-attachments/assets/fb02076b-f0f1-4efb-98af-416ddb6fca87)

![image](https://github.com/user-attachments/assets/f51daec9-9725-45e7-9217-330d2e78b648)

**Comment by ThorvaldAagaard** [comment]
You can right-click on a play in the bidding diagram, and select whatever you need - A huge improvement :-)

![image](https://github.com/user-attachments/assets/37fdfb9d-9458-472c-a4c1-ebc1db4d39fb)

**Comment by ThePokerDude** [comment]
Thanks. Yes it's really cool.
After playing around with it a little I figured out how to use it:
1) Mark player(s) as manual
![image](https://github.com/user-attachments/assets/ea619d10-46c1-4e99-9941-d77433655df5)
2) Paste in the file
![image](https://github.com/user-attachments/assets/00b4efe4-dd93-41b8-be1e-3c30c98d0ad7)
3) manually bid
![image](https://github.com/user-attachments/assets/c3d123dc-37a8-4e9e-bbdd-de2d03fa9e9c)

**Comment by ThorvaldAagaard** [comment]
If you paste the board first and then change one or more players, you can use F& (reload game) to start the bidding all over again.

Sometimes it will not enable all bids, so I have to complete the bidding first before pressing F6 (Typical when BBA doesn't make the bid I expected, so I change the bplayer). Seems to be an error in F6

**Comment by EdwardPiwowar** [comment]
This bug should go away in 8623.

**Comment by ThePokerDude** [comment]
Options in new version are very good. All manual bids possible.
