### ISSUE TITLE
Bug: After bidding manually and reloading the bidding box is not reset

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#733]
![image](https://github.com/user-attachments/assets/e5665ffc-9a5a-4977-a242-2fa520574f1b)

**Comment by EdwardPiwowar** [comment]
This bug should go away in 8623.

**Comment by ThePokerDude** [comment]
Thanks, works perfectly fine with 8623.
Issue can be closed.
