### ISSUE TITLE
Is it possible to hand over to automatic bidding after having bid manually?

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#734]
To check if the issue
https://github.com/EdwardPiwowar/BBA/issues/152
still occurs I had to manualy bid 1h and 3d.
Now I'd like to see if BBA passes to 3h (issue fixed) or bids 4h (issue still exists).
How can I hand over the bidding to BBA?
When I press F6 the bidding restarts from the beginning.
When I change from manual to EPBot the bidding also restarts from the beginning.
03E75180640DEDDEFB72664EA804
![image](https://github.com/user-attachments/assets/486fdb71-5fd0-4760-8f0f-21f62a8b8552)

**Comment by EdwardPiwowar** [comment]
1. Next BBA should automatically complete manual bidding after changing to EPBot.
2. "Now I'd like to see if BBA passes to 3h (issue fixed) or bids 4h (issue still exists)." - you can also press Hint to see what the bot wants to bid.

**Comment by ThePokerDude** [comment]
Thank you for the fix. 8623 works perfectly fine.
Thanks also for the information about the "hint" option.
You can close the issue.
