### ISSUE TITLE
I don't think South should pass here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#752]
5F24DE5247EFE9157785C67D8B6F
![image](https://github.com/user-attachments/assets/984b185e-1846-4804-9555-2d84082e86a1)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/128e30cc-8f94-4803-bff0-1d94adb8d5e6)

**Comment by ThorvaldAagaard** [comment]
Better, but 4N seems a bit optimistic.
I will close, when new version released
