### ISSUE TITLE
Bug in 8623 - After bidding the no more possible bids are not grayed out. When clicking an impossible bid strange things happen

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#755]
06888BEA19AAC51F975ECD4D4C11
I also chose 1h as Thorvald did in
https://github.com/EdwardPiwowar/BBA/issues/211
![image](https://github.com/user-attachments/assets/854078ae-7421-4883-9dc6-5095ed9c3982)
After 
p 1h p 3d
p
I clicked on 1s. It was interpreted as a pass but also as a bid. 
So the bidding goes on after 3 passes
![image](https://github.com/user-attachments/assets/4c415807-e9e1-4752-be70-fe12c311a358)

**Comment by ThePokerDude** [comment]
I have found a hint 
0B26F6BE4ECAC2A4A2736F38C92F
If the first bid is done manually the gray out does not work
![image](https://github.com/user-attachments/assets/647e2a7e-c20d-4ad7-9abc-92f88a7bce3c)
If the first bid is done by ebot the gray out works
![image](https://github.com/user-attachments/assets/55671a96-c18e-4d76-bf06-980233a7cd64)

**Comment by EdwardPiwowar** [comment]
I think I fixed it in version 8624.

**Comment by ThePokerDude** [comment]
fix confirmed 
![image](https://github.com/user-attachments/assets/af069dc6-dc59-4708-a41e-93fca1b41d6b)
![image](https://github.com/user-attachments/assets/022aa502-a630-4bab-a80c-eb87f3bb4516)
![image](https://github.com/user-attachments/assets/339c1a5e-0032-4f1b-b553-0848eee683c2)
