### ISSUE TITLE
Bug in 8623 - double is falsly grayed out

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#757]
When investigating
https://github.com/EdwardPiwowar/BBA/issues/223
9DFFAA4604DCD374AB35D8C29247
I wanted to reproduce the bidding but double was not possible
![image](https://github.com/user-attachments/assets/1e81daae-5a62-45c0-95d9-0aef75fc5cdd)

**Comment by EdwardPiwowar** [comment]
I think I fixed it in version 8624.

**Comment by ThePokerDude** [comment]
Fixed in 8624
![image](https://github.com/user-attachments/assets/d1c7fddc-869c-4bb4-a26f-f94465d96938)

**Comment by EdwardPiwowar** [comment]
If you created an issue you should be able to close it. Is that right?
