### ISSUE TITLE
Error in generated PBN

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#765]
If I deselect both dummy analysis the PBN-file record the score as 0 tricks for declarer
```
[Event ""]
[Site ""]
[Date "2024.08.05"]
[Board "1"]
% 00A4774D0B62FCAE1469CF074EB1
[North "EPBot1"]
[East "EPBot2"]
[South "EPBot3"]
[West "EPBot4"]
[Room "Open"]
[Dealer "N"]
[Vulnerable "None"]
[Deal "N:J74.QJ543.T2.Q62 KQT63.7.AK74.A97 A82.AT86.J6.KJ54 95.K92.Q9853.T83"]
[Declarer "E"]
[Contract "1S"]
[Result "0"]
[Score "NS 350"]
[Scoring "MP"]
[Auction "N"]
Pass  1S    Pass  Pass
Pass
[Play "S"]
*
[BidSystemEW "Sayc - Standard American Yellow Card"]
[BidSystemNS "2/1GF - 2/1 Game Force"]
```

If I deselect only Single it is the same problem, event when the double dummy is calculated.

**Comment by EdwardPiwowar** [comment]
After the changes I entered SD instead of DD, it should be fine in the next version.

**Comment by ThorvaldAagaard** [comment]
So DD if selected, else SD if selected and no result if none selected?

**Comment by ThorvaldAagaard** [comment]
Still not fixed in 8629
![image](https://github.com/user-attachments/assets/59599dc9-1ebc-4ec9-b2dc-3c3f4797c73f)

![image](https://github.com/user-attachments/assets/0b791c35-91b2-4171-bb12-0ea8a0a85fce)

**Comment by ThorvaldAagaard** [comment]
I have just testet this:
```
BBA.exe --ARCHIVE_FILE output_10 --AUTOBID --HAND .\input_10.bba --CC1 GIB-Thorvald.bbsa --CC2 GIB-Thorvald.bbsa --DD 0 --SD 1
```
And it save this
![image](https://github.com/user-attachments/assets/c4bccdd6-7b26-4692-8367-c240fdee5a61)

**Comment by EdwardPiwowar** [comment]
"So DD if selected, else SD if selected and no result if none selected?" - would that be correct?

**Comment by EdwardPiwowar** [comment]
[BBA.exe.zip](https://github.com/user-attachments/files/16551632/BBA.exe.zip)

**Comment by ThorvaldAagaard** [comment]
Let me try again

If SD select insert the SD result
If DD selected and not SD selected insert the result from DD
If SD not selected and DD not selected, do not enter a trick count and score

Currently it seems SD is inserted if selected and if not, then 0 tricks is assumed with a wrong result

**Comment by EdwardPiwowar** [comment]
The above exe:
- if play is selected then the result is from play, regardless of SD and DD
- if DD is selected then the result is from DD, regardless of  SD
- if SD is selected then the result is from SD
- if none the result = ""

**Comment by ThorvaldAagaard** [comment]
That is not how it work in 8630
![image](https://github.com/user-attachments/assets/ed6f404b-29f7-4e08-b49b-3f526c669286)

**Comment by EdwardPiwowar** [comment]
8632
[BBA.exe.zip](https://github.com/user-attachments/files/16563975/BBA.exe.zip)

I corrected **Score**, for me **Result** was ok.
BBA does not overwrite the archive with the same hand (you have to change current hand or reset).

**Comment by ThorvaldAagaard** [comment]
I started BBA selected only Double Dummy analysis.
Selected Archive (pbn) and clicked start
![image](https://github.com/user-attachments/assets/3961e889-e527-4b62-ae88-8a703fca02ef)

The generated file sometimes (Board 5,7 and 29) had a result, but other times not

[BBA - 15.08.2024 21.56.pbn.txt](https://github.com/user-attachments/files/16629775/BBA.-.15.08.2024.21.56.pbn.txt)

**Comment by EdwardPiwowar** [comment]
[BBA.exe.zip](https://github.com/user-attachments/files/16630371/BBA.exe.zip)

The above BBA 8637 counts DD results for equal results on both tables (what takes more time).

**Comment by ThorvaldAagaard** [comment]
Looks OK
