### ISSUE TITLE
I really need some help here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#769]
I am looking thru the deals autobid from the command line

This is the board
23CB2CA44618CF2F7C26FA4972B3
and I get this result
```
[Event ""]
[Site ""]
[Date "2024.08.08"]
[Board "66"]
% 23CB2CA44618CF2F7C26FA4972B3
[North "EPBot1"]
[East "EPBot2"]
[South "EPBot3"]
[West "EPBot4"]
[Room "Open"]
[Dealer "N"]
[Vulnerable "All"]
[Deal "N:KT86.AJ94.K987.4 J743.T.AT54.KQT7 Q2.KQ86.QJ6.A982 A95.7532.32.J653"]
[Declarer "S"]
[Contract "4HXX"]
[Result "11"]
[Score "NS 1480"]
[Scoring "MP"]
[Auction "N"]
1D    Pass  1H    Pass
2H    X     XX    3C
Pass  Pass  4C =1=    Pass
4H    Pass  Pass  X
Pass  Pass  XX    Pass
Pass  Pass
[Note "1:artificial"]
[Play "W"]
*
[BidSystemEW "2/1GF - 2/1 Game Force"]
[BidSystemNS "2/1GF - 2/1 Game Force"]
````

If I paste the BBA code I get the same
![image](https://github.com/user-attachments/assets/b26af9f1-a39e-4fef-8b90-83f51ff151d1)

But if I paste the PBN I get this
![image](https://github.com/user-attachments/assets/12fbde9e-c0d2-4411-b81f-b99b71a16b60)

Now the real interesting part is if I paste the BBA-code I get the result as the first, but if I then paste the PBN once again it show the same result as if I pasted the BBA-code.

It is the board number and vulnerability, that is the problem.

23CB2CA44618CF2F7C26FA4972B3 is the 66 board in the inputfile

**Comment by ThorvaldAagaard** [comment]
When that is cleared you might have a look at the bad penalty double

**Comment by EdwardPiwowar** [comment]
Paste the source pbn that has vulnerable = none.

**Comment by ThorvaldAagaard** [comment]
I don't understand

I play a BBA, and use the genrated PBN from BBA and paste that, as you can see above it is "Vulnerable"
So why it show a board non-vulnerable could be caused by play number or something else.

When decrypting a BBA-code it should always have vulnerability corect

**Comment by EdwardPiwowar** [comment]
ok, I see a problem

**Comment by EdwardPiwowar** [comment]
8631
[BBA.exe.zip](https://github.com/user-attachments/files/16562467/BBA.exe.zip)
I think it's okay now.

**Comment by ThorvaldAagaard** [comment]
Looks better. I assume you will look at the penalty double generally, so I will close this.
