### ISSUE TITLE
When using triggers the generated board in the PBN-file is wrong

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#773]
```
% PBN 2.1
% Generated by Bridge Bidding Analyser v. 8631
% https://sites.google.com/view/bbaenglish
% The source file name: "1 boards found"
% CC1 - GIB-Thorvald.bbsa
% CC2 - GIB-Thorvald.bbsa
% 1-2 - 1m opening allows 5M
% 1-2 - 1M-3M inviting
% 1-2 - 1X-(Y)-2Z forcing
% 1-2 - 1X-(1Y)-2Z strong
% 1-2 - Blackwood 0314
% 1-2 - Cappelletti
% 1-2 - Cue bid
% 1-2 - DOPI
% 1-2 - Drury
% 1-2 - Forcing 1NT
% 1-2 - Fourth suit game force
% 1-2 - Gerber
% 1-2 - Inverted minors
% 1-2 - King ask by 5NT
% 1-2 - Lebensohl after 1NT
% 1-2 - Lebensohl after double
% 1-2 - Maximal Doubles
% 1-2 - Michaels Cuebid
% 1-2 - Minor Suit Stayman after 1NT
% 1-2 - Minor Suit Stayman after 2NT
% 1-2 - Minor Suit Transfers after 1NT
% 1-2 - Mixed raise
% 1-2 - New Minor Forcing
% 1-2 - Quantitative 4NT
% 1-2 - Responsive double
% 1-2 - ROPI
% 1-2 - Shape Bergen structure
% 1-2 - SMOLEN
% 1-2 - Soloway Jump Shifts
% 1-2 - Splinter
% 1-2 - Support 1NT
% 1-2 - Support double redouble
% 1-2 - Texas
% 1-2 - Two suit takeout double
% 1-2 - Unusual 1NT
% 1-2 - Unusual 2NT
% 1-2 - Weak natural 2D
% 1-2 - Weak natural 2M
% 
[Event ""]
[Site ""]
[Date "2024.08.10"]
[Board "1"]
% FBC4FC2202FAA34ECF05EE6E186C
[North "EPBot1"]
[East "EPBot2"]
[South "EPBot3"]
[West "EPBot4"]
[Room "Open"]
[Dealer "S"]
[Vulnerable "All"]
[Deal "N:QJ63.AJ876.A6.97 842.3.QJ9.QJT854 9.Q9542.K87542.6 AKT75.KT.T3.AK32"]
[Declarer "W"]
[Contract "3S"]
[Result ""]
[Score "NS 500"]
[Scoring "MP"]
[Auction "S"]
Pass  1S    Pass  1N =1= 
Pass  3C    Pass  3S
Pass  Pass  Pass
[Note "1:forcing 1NT"]
[Play "N"]
*
[BidSystemEW "2/1GF - 2/1 Game Force"]
[BidSystemNS "2/1GF - 2/1 Game Force"]

[Event ""]
[Site ""]
[Date "2024.08.10"]
[Board "2"]
% 6E3CE4211526F8D08AC238AB7579
[North "EPBot1"]
[East "EPBot2"]
[South "EPBot3"]
[West "EPBot4"]
[Room "Open"]
[Dealer "W"]
[Vulnerable "NS"]
[Deal "N:AQJT5.76.A.AK985 32.J8.97542.QJ32 74.KQT4.KJT3.T76 K986.A9532.Q86.4"]
[Declarer "S"]
[Contract "3N"]
[Result ""]
[Score "NS 630"]
[Scoring "MP"]
[Auction "W"]
Pass  1S    Pass  1N =1= 
Pass  3C    Pass  3N
Pass  Pass  Pass
[Note "1:forcing 1NT"]
[Play "W"]
*
[BidSystemEW "2/1GF - 2/1 Game Force"]
[BidSystemNS "2/1GF - 2/1 Game Force"]

```
Score seems to be wrong
On the second board Score could be right
![image](https://github.com/user-attachments/assets/65ba63e7-b9ce-482c-a55b-4cd6882ae95e)

But as I have none selected from dummy analysis I would expect [Score ""]

I think I have mentioned it before, but will you add the trigger on the PBN-file

**Comment by EdwardPiwowar** [comment]
Next BBA as in #765
What do you mean ".... but will you add the trigger on the PBN-file"?

**Comment by ThorvaldAagaard** [comment]
I mean you should document then trigger used in the PBN-file like this
![image](https://github.com/user-attachments/assets/43c0f933-a9cb-42f8-ba81-87df139e3d96)

Or whatever format you like. Filename is still a fine approvement, but it wopuld be nice to have it on each board

It also looks like the counter no longer is beeing updated
![image](https://github.com/user-attachments/assets/a3770c0e-e1c8-4e63-a6e1-3b68347ef9bd)

**Comment by EdwardPiwowar** [comment]
[BBA.exe.zip](https://github.com/user-attachments/files/16573538/BBA.exe.zip)
[Event ""]
[Event "Sequence: 2*-?-p"]
[Event "Convention: 1M-3M inviting"]
https://sites.google.com/view/bbaenglish/program-description/archiving-deals
Specify "the counter".

**Comment by ThorvaldAagaard** [comment]
Look at image: 0 deals found
And look at the size of 2C.PBN where you can see it has found some deals

**Comment by EdwardPiwowar** [comment]
Should be at least
2C-

**Comment by EdwardPiwowar** [comment]
I'll check it right away

**Comment by EdwardPiwowar** [comment]
The counter works (archive must be checked to make sense)

**Comment by ThorvaldAagaard** [comment]
![image](https://github.com/user-attachments/assets/8191d191-1172-402f-bc92-9b4d07ae718a)
![image](https://github.com/user-attachments/assets/ed2dafbe-08d4-4d36-8e27-c349ebd05c38)

So counter seems to be related to "-"

In the first example it find some deals, but it is not clear how they are selected.

Another point is that when aechive is selected for only one room, you should only look at deals from that room

**Comment by EdwardPiwowar** [comment]
Counter isn't related to "-". Documentation says:
`To archive hands with a selected bidding sequence, enter that sequence as in example (3). The sequence must contain at least one "-" character.`
https://sites.google.com/view/bbaenglish/program-description/generating-hands-with-the-chosen-convention-or-the-selected-bid-sequence
The second idea is a good one, for now you can set up both rooms the same.

**Comment by ThorvaldAagaard** [comment]
If I set both rooms identical will it then only take one but bid both? (Bad performance as no need to bid the same board twice with the same cc's)
If "-" is required it would be nice to include it in the validation
Then you don't have to fix the counter

**Comment by ThorvaldAagaard** [comment]
I will close and live with the bad performance
