### ISSUE TITLE
With 4-card support use Jacoby

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#78]
1897CA2111508D358657B85C048C
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/185b4059-3e28-4591-b3ff-95b40dc757a4)
Always important to establish the fit (Unless the hand is so strong it can control the bidding)

**Comment by ThorvaldAagaard** [comment]
08D54653A9E59B3DC95442EB50C7
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/8efda173-e768-4bf8-a3ff-ee9ea6a5c981)
Also a problem with 5-card support

**Comment by EdwardPiwowar** [comment]
But WBridge5 bids the same way
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/93753945-e0f2-4f58-8fd4-102291186cb9)

![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/4705a2e2-c97a-4c91-a4a2-e1595bee5db8)

**Comment by ThorvaldAagaard** [comment]
Yes. WBridge5 has many errors :-)

**Comment by ThorvaldAagaard** [comment]
GIB gets it right
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/2ead5a56-685e-4dbd-b739-b92503299ecf)
Playing Sayc I am not even sure 3S is forcing

**Comment by ThorvaldAagaard** [comment]
There are more issues with this board, when you look at GIB's bidding

4D from opener is defined as a 5-card side suit, and not as BBA states a splinter.

Another issue is that 4D from responder is defined:
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/a3c22e34-8ccb-4281-be82-3979016d63c2)

So the range is to wide (11-13 HCP is more correct)

**Comment by ThorvaldAagaard** [comment]
https://bridgewinners.com/article/view/playing-sayc/?cj=1418825#c1418825

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/cc401d8d-9b5c-4c9f-b661-ec0de9a04bd1)
