### ISSUE TITLE
Out of string space

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#79]
I tried to load a large PBN-file, and got this message:
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/eef5e96b-ae96-452e-b6da-50f74ceb2ce3)

**Comment by EdwardPiwowar** [comment]
I don't think I can handle this. PBN files are too large.
But you can attach this file to me.

**Comment by EdwardPiwowar** [comment]
It works for me
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/56148d0a-d658-479e-8a23-74ca5724749f)

**Comment by ThorvaldAagaard** [comment]
Strange - The error is consistent for me and I have 64 GB of ram and a swapfile of 64GB

**Comment by EdwardPiwowar** [comment]
I have 16 GB and it works once. BBA files should work better. I am converting this file to bena format.

**Comment by EdwardPiwowar** [comment]
[All to Ben.zip](https://github.com/EdwardPiwowar/BBA/files/13621130/All.to.Ben.zip)

**Comment by ThorvaldAagaard** [comment]
Thx, I have checked my old laptop, and it can read the file.
I am using two different cc's at the moment
