### ISSUE TITLE
With 5431 and shortage in a preempted suit T/O double is better than a bad 5-card suit

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#81]
07162CE95378F2F87FF2BE8E2D68
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/156d322e-f1d2-4cc9-94ef-3c2f227fb1d1)

3H from south is also just a bad bid, unless North should bid 3S to show a stopper, so 3N can be bid.

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/a79755a8-2bca-49cd-9bb6-bb3456a74c1a)
