### ISSUE TITLE
I think this is a bad (and wrong) implementation

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#817]
04969791273A3EB1E95F7CA909EE
![image](https://github.com/user-attachments/assets/696dcf51-45d0-4d33-89c5-eb90766be197)

It seems that any spade bid from South is limited to 16 HCP and South must Cuebid 2D for no reason

After 1S South will pass with a minimum hand
2S should be about 14-16 and 4-cardmsupport
3S should be 17-19 and 4-card support
4S is 20-22

Stronger hand must cuebid to establish some force

Even with the current implementation it is also bad, that North does not accept the invite
![image](https://github.com/user-attachments/assets/e5e006b7-e5f8-4874-9d52-b411457a3cb3)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/user-attachments/assets/5fe5f875-835d-47c7-9ac6-518a76765165)

**Comment by ThePokerDude** [comment]
Fixed in 8642
![image](https://github.com/user-attachments/assets/e4df9b5c-b4d0-4ee7-a608-65b5b94d4cc4)
