### ISSUE TITLE
OptimumResultTable is Missing

### ISSUE THREAD

**Issue by ADavidBailey** [EdwardPiwowar/BBA#872]
My program to summarize BBA notes, used  line.startswith('[Optimum') to signal the end of the deal (acutally only one more line).  When I ran my program this morning, I noticed that those last two lines are missing.

Should I use a blank line?  Or, '[Event ' as a deal separator?

**Comment by ThorvaldAagaard** [comment]
Blank line is best

**Comment by ADavidBailey** [comment]
I was using this code to capture the Optimum result and signify the last line of the deal that I'm interested in) :

        if optimum == True:
            par = line.strip()
            txt = board.rjust(5) + declarer.rjust(6) + contract.rjust(9) + score.rjust(9) + '  ' + par.ljust(7)
            f.write(txt + '| ' + this_note + '\n')
            this_note = ''
            optimum = False
        if line.startswith('[Optimum'):
            optimum = True

Is Optimum result, gone?

**Comment by ADavidBailey** [comment]
> Blank line is best

Can I count on a blank line at the end of the file?

**Comment by ThorvaldAagaard** [comment]
Yes, it should be there

**Comment by ADavidBailey** [comment]
Thanks.
