### ISSUE TITLE
3-Spades or 4-Spades

### ISSUE THREAD

**Issue by ADavidBailey** [EdwardPiwowar/BBA#876]
Vul vs. non, 5-losers.  EPBOT and GIB both bid 4S.  On BBO, GIB bid 3-Spades and South Passed!!  I thought surely, with 2+ cover cards, South should bid 4.  

3E94323B53ED2815132E623E29BB
![Screenshot 2024-09-24 at 9 15 21 AM](https://github.com/user-attachments/assets/23ea8391-b555-4515-968c-9a3c192b2e51)

**Comment by ThorvaldAagaard** [comment]
If you force BBA to bid 3S in North South will correctly bid 4S, so I think BBA is doing fine here
![image](https://github.com/user-attachments/assets/3c4f309f-1de4-43c7-bbb5-cb9b7f87f3dc)

**Comment by ADavidBailey** [comment]
Two questions:
1. Why do you agree with the 4S bid?
2. How does one force BBA to bid 3S?

**Comment by ThorvaldAagaard** [comment]
When bidding 4Ma we always put optimum pressure on the opponents, and I am OK with most 8-card suits.

When you right click and select Gib as bidder you can instead select manual, and the BBA will ask you what to bid for that hand in each round

**Comment by ADavidBailey** [comment]
Thanks
