### ISSUE TITLE
Is it possible to bid a hand once and receive the final contract form command line? Idea for testing BBA versions.

### ISSUE THREAD

**Issue by ThePokerDude** [EdwardPiwowar/BBA#888]
I would like to create a test app for BBA.
The idea is to run the test for each new BBA version for a set of hands, so that if a new version breaks a bidding which worked previously, we would see it immidiately.

What I'd need would be a possibility to bid a hand once and write the final contract and/or the comlete bidding into a file.
At the moment I'm struggeling with the command line.

None of these worked:

bba.exe 08F293C8BE4B3E82F59A9F8384D5 ...\test.pbn
bba.exe 08F293C8BE4B3E82F59A9F8384D5 --ARCHIVE_FILE ...\test.pbn
bba.exe 08F293C8BE4B3E82F59A9F8384D5 --ARCHIVE_FILE test.pbn

Is this possible with the current command line?
If yes - could you give me the syntax?
 
For the test app I would prepare a test file with a list of boards for which I'd assign the correct final contract (and additionally the correct bidding).

For the test I would
1) run the command in a loop for all boards of the test set
2) write the results into a file or preferably database. (Database would be much cooler as we could just add test result data for new versions and reports are msch easier with SQL.)

In a second step

3) compare the result for each board to the correct final contract
4) create statistics and a report

If this works we could expand the test by additionally comparing the complete bidding to the correct one.

**Comment by ThorvaldAagaard** [comment]
Input and output from BBA is normally a file.

And I will recommend handling all deals in the same go, so assuming you have a .PBN-file with the boards you want to test, you can use this command:

https://github.com/lorserker/ben/blob/main/UCBC%202024/Boards/runBBA.cmd

BBA will save as .pbn/.ben based on what is selected in the GUI lst time.

But lets us use .PBN for input and output, so you just have to compare the deals in the files.

So you can have the right bidding in the input file as BBA will ignore that, You can also have another filw with the expected result.

I sometime bid an old file when we get a new BBA version, but for my 1 mill training deals I get to many differences to follow up, so I recommend having input files based on conventions - perhaps from Praxtice Bidding Scenarios

Playing with .PBN is simple and you can see samples in BEN-repository, or start using the Github project "Endplay"

**Comment by EdwardPiwowar** [comment]
Add
--HAND 08F293C8BE4B3E82F59A9F8384D5
This parameter is required if any other parameter is used.
(For a single hand we do not use --AUTOBID)

**Comment by EdwardPiwowar** [comment]
BBA does not return a value, therefore DLLs are available.
Here is my way of testing:
Manual registration of the library is required, which depends on the Framework version and location.
New bots have the prefix New and old ones are DLLs with the prefix Old.
20 is the DLL version.
Required files
[Test86.zip](https://github.com/user-attachments/files/17185704/Test86.zip)

![image](https://github.com/user-attachments/assets/a624fee9-8523-49ba-af76-03a60b417130)

**Comment by ThePokerDude** [comment]
@ThorvaldAagaard 

Probably I did not det up the script correctly as BBA writes BBA-Hand number into the outputfile (test.pbn.bba)

0621BC3F900EE2E4357B78964476
084D28712B98BEC61A7381D178F6
0AD5F4A2CD0B912C6C4A2A5FB2E3
....

What do I have to change so the pbn is saved instead of the  BBA-Hand number?

@echo off
setlocal enabledelayedexpansion

for /L %%i in (1,1,1) do (
    set "input_file=.\input_%%i.bba"
    set "output_file=output_%%i"
    
    set "command=start "BBA" /D . BBA.exe --CURRENT_ARCHIVE . --ARCHIVE_FILE test.pbn --AUTOBID --HAND issues.pbn --CC1 Sayc.bbsa --CC2 Sayc.bbsa --DD 0 --SD 0"
    echo !command!
    
    !command!
    echo BBA Started for input file %%i
    timeout /t 2 /nobreak >nul
)

endlocal

**Comment by ThorvaldAagaard** [comment]
Open BBA and make sure you have selected .PBN when arciving

**Comment by ThePokerDude** [comment]
Thanks, it works now.
