### ISSUE TITLE
Append vs. Replace

### ISSUE THREAD

**Issue by ADavidBailey** [EdwardPiwowar/BBA#899]
When I run BBA from the command line, deals are appended to the archive.

P:\>C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-ADB.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Minor_Suit_Opener_Inv_Raise-S.pbn --ARCHIVE_FILE P:\bba\Minor_Suit_Opener_Inv_Raise --AUTOCLOSE

Each time I run this, the archive file grows by 500 deals.

**Comment by EdwardPiwowar** [comment]
If you don't want to overwrite the file, you can delete it first.

**Comment by ADavidBailey** [comment]
I do want to overwrite the file.  I'll try to remember to delete it first.  Thanks.
