### ISSUE TITLE
2-level bid after opponents bid on the 1-level.

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#90]
02C967EC4A6A057A209FC028AE55
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f51513ac-3894-431c-99dd-2d4126b38cb8)
I think south should bid 2H instead of double. This is common for all systems

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/c9c919a7-39d2-4357-bf66-9e841f6d19c2)
