### ISSUE TITLE
Pass looks wrong here

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#92]
0FAE44638F73E12A7004B9E4E357
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c1ca028c-cf5b-4062-aa69-cb9de9a075f6)

With Lebensohl it is a 3C bid
https://bridgewinners.com/article/view/bidding-problem-2-sxd1h7wivj/

**Comment by ThePokerDude** [comment]
Fixed in 8137
![image](https://github.com/user-attachments/assets/85c51edf-04b3-4ea2-b6e8-dc7e402dcb43)
