### ISSUE TITLE
Facit Bridge

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#925]
When I try to bid this it stops at board 13 (I clicked start to let it bid all boards)

![image](https://github.com/user-attachments/assets/14c822a0-5858-458f-be8d-1819517de697)
[oct13_feb23_nov23_jun24.zip](https://github.com/user-attachments/files/17355257/oct13_feb23_nov23_jun24.zip)

If I do it manually the first 4 boards look fine, but then at board5 I get
![image](https://github.com/user-attachments/assets/ba3561d6-0650-4d89-84f7-9bad62984db5)

And board 6
![image](https://github.com/user-attachments/assets/105595cc-670c-42f3-a37e-7027f53cbb23)

And 7 show that BBA is confused
![image](https://github.com/user-attachments/assets/57c4ddbc-fdf3-4584-bb60-b05dd71368cb)

**Comment by EdwardPiwowar** [comment]
![image](https://github.com/user-attachments/assets/0fbcfd7b-7834-42d5-b12b-7c062f51c05a)

**Comment by EdwardPiwowar** [comment]
7 is ok WE bids

**Comment by EdwardPiwowar** [comment]
All by loop
![image](https://github.com/user-attachments/assets/f5b01b22-9255-444a-a31e-dff696822c00)

**Comment by ThorvaldAagaard** [comment]
There is somethink strange going on

I load the file, select the 2nd room bidding
![image](https://github.com/user-attachments/assets/736b02c6-7fc5-4d45-adc5-b2053847460a)
Enter 7 in deal number and get this:
![image](https://github.com/user-attachments/assets/5c43a7a2-67ab-4eb1-956d-b7b17c81f24c)
That is fine

Using the arrow I navigate to 8 and get this:
![image](https://github.com/user-attachments/assets/01ba9797-0c02-4c26-b34c-2fa6a0585220)

It looks like you are not resetting the Auction if there is no Auction in the pbn for the board - could also explain the loo

The loop is working, so it was probably just a glitch

**Comment by EdwardPiwowar** [comment]
I used "oct13_feb23_nov23_jun24_GIB8663.pbn"
and you used modified "oct13_feb23_nov23_jun24".
But there were also occasional bugs.
You have to decide what is the format for "Score Table", then BBA will display the score as below:
![image](https://github.com/user-attachments/assets/d4fe3847-8f14-4d39-9979-b16cb67f04b5)

**Comment by ThorvaldAagaard** [comment]
Ok, oct13_feb23_nov23_jun24 is the original problems, and scoring is for reading by an application
Auction can be of the form AC 3D AC Pass
Then the challenge was bid bid BEN creating oct13_feb23_nov23_jun24_GIB8663
As I wanted to present the score in Bridge Composer I had to apply som formatting, making it more diffciult for you to read.

When used in BBA it is a nice idea to read the file BEN have bid and show that in Room 2.

As long as we use same system you can use that bidding for EW in open (unless there are errors)

I will add the scoring as a comment to the file, so you can use that if you can't parse the one in the last file

**Comment by ThorvaldAagaard** [comment]
And I think it is a great idea to show the bidding from the PBN in the closed room, if it is present in the PBN-file.
Is it the scoring that will trigger that function?

Andreas might be able to use that for comparing different versions of BBA,

**Comment by EdwardPiwowar** [comment]
The option is only selectable from the Bidding menu.
And it is necessary for Facit.

**Comment by EdwardPiwowar** [comment]
A lot of confusion... Do you do these pbn entries manually?

**Comment by ThorvaldAagaard** [comment]
The original PBN is manually created by Eamon from the Bridge World, so that is manually. The we let BEN bid them - that is automated and the result is a PBN

**Comment by EdwardPiwowar** [comment]
But are you changing bellow?
{ 4S 10 5S 8 4H 5 3N 4 5H 3 5D 3 6S 2 6D 2 6H 1 } 
to 
{\n\n\n\nScore Table:
 7\h      10\n 6\h       6\n 7\c       3\n 6\c       3\n 5\h       2\n 6N       1\n\n\n\n\n\n\n
BBA can read both.

**Comment by ThorvaldAagaard** [comment]
Yes, when loading the file into Bridge Composer i then get this nice layout
![image](https://github.com/user-attachments/assets/3992ab5d-740c-4c94-b5ac-5592a0810278)

**Comment by EdwardPiwowar** [comment]
Instead of the current solution, it seems to me that direct bidding on the file prepared by Eamon by any robots is a better solution.

**Comment by ThorvaldAagaard** [comment]
That is what I do now, and even with the BBA-dll as a robot. Problem is when I need to find the error in the bidding.

But better you foxus on the bidding errors, so I will close this
