### ISSUE TITLE
Pasting from my Mac-computer

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#963]
What is wrong with this:
https://www.bridgebase.com/tools/handviewer.html?bbo=y&lin=pn|TWOONEBEN%2CRobot%2CRobot%2CRobot|st||md|3SKJ9HAJ43DKCQJ954%2CSQ86HK965DJ82CAT3%2CSA753HQT87D53CK76%2CST42H2DAQT9764C82|sv|N|ah|Board%205|mb|P|mb|3D|an|Preempt%20--%207%2B%20!D%3B%205-9%20HCP%3B%20!DQ%3B%206%2B%20total%20points|mb|P|mb|P|mb|P|pc|CQ|pc|CA|pc|C7|pc|C8|pc|D8|pc|D3|pc|DA|pc|DK|pc|DT|pc|C4|pc|D2|pc|D5|pc|H2|pc|HA|pc|H9|pc|HT|pc|SJ|pc|SQ|pc|SA|pc|S2|pc|S3|pc|S4|pc|S9|pc|S6|pc|SK|pc|S8|pc|S7|pc|ST|pc|C5|pc|CT|pc|CK|pc|C2|pc|H8|pc|D9|pc|H3|pc|H5|pc|D6|pc|H4|pc|DJ|pc|H7|pc|H6|pc|HQ|pc|DQ|pc|HJ|pc|D7|pc|C9|pc|C3|pc|C6|pc|D4|pc|CJ|pc|HK|pc|S5|

besides the missing T/O double :-)

**Comment by ThorvaldAagaard** [comment]
I have the same problem from Table Manager from Job Scheffers

https://www.bridgebase.com/tools/handviewer.html?lin=pn%7CBEN-R5,Lia,BEN-R5,Lia%7Cst%7C%7Cmd%7C1S75HAKQ43DQT76CAT,SAT2HJT975D53C863,SQJ8H8DAKJCQJ9754,SK9643H62D9842CK2%7Csv%7CB%7Cah%7CBoard%2055%20(Closed)%7Cmb%7C1NT%7Cmb%7CP%7Cmb%7C2S%7Cmb%7CP%7Cmb%7C3C%7Cmb%7CP%7Cmb%7C4NT%7Cmb%7CP%7Cmb%7C5H%7Cmb%7CX%7Cmb%7C6C%7Cmb%7CP%7Cmb%7CP%7Cmb%7CP%7Cpc%7ChJ%7Cpc%7Ch8%7Cpc%7Ch6%7Cpc%7ChA%7Cpc%7Cd6%7Cpc%7Cd5%7Cpc%7CdA%7Cpc%7Cd8%7Cpc%7Cc5%7Cpc%7Cc2%7Cpc%7CcT%7Cpc%7Cc3%7Cpc%7CcA%7Cpc%7Cc6%7Cpc%7Cc4%7Cpc%7CcK%7Cpc%7Ch3%7Cpc%7Ch5%7Cpc%7Cc9%7Cpc%7Ch2%7Cpc%7CcQ%7Cpc%7Cs3%7Cpc%7Cs7%7Cpc%7Cc8%7Cpc%7CdK%7Cpc%7Cd2%7Cpc%7Cd7%7Cpc%7Cd3%7Cpc%7CdJ%7Cpc%7Cd4%7Cpc%7CdQ%7Cpc%7Cs2%7Cpc%7ChK%7Cpc%7Ch7%7Cpc%7Cs8%7Cpc%7Cs4%7Cpc%7ChQ%7Cpc%7Ch9%7Cpc%7CsJ%7Cpc%7Cs6%7Cpc%7CdT%7Cpc%7ChT%7Cpc%7CsQ%7Cpc%7Cd9%7Cpc%7Ch4%7Cpc%7CsT%7Cpc%7Cc7%7Cpc%7Cs9%7Cpc%7CcJ%7Cpc%7CsK%7Cpc%7Cs5%7Cpc%7CsA%7C

**Comment by EdwardPiwowar** [comment]
In the next BBA.
