### ISSUE TITLE
Some time ago, Thorvald suggested that I send you an example of the lin files that, for a long time, I used...

### ISSUE THREAD

**Issue by ADavidBailey** [EdwardPiwowar/BBA#979]
I never had any trouble with these files.  I know I used them with BBO and Bridge Composer.  I probably used them elsewhere; but, I'm old and forgetful.

https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/lin/-mixed.lin
@thorvaldAagaard  I never know when/if I need to tag people.

**Comment by ADavidBailey** [comment]
Nothing to do.

**Comment by ThorvaldAagaard** [comment]
Don't tag me. I am getting notified when someone adds or updates an issue
